
/**
 * Title:        chartwizard<p>
 * Description:  JAVA CHART v1.0<p>
 * Copyright:    Copyright (c) juney<p>
 * Company:      JCosmos<p>
 * @author juney
 * @version 1.0
 */
package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class ChartExtentStyleEditor extends Editor {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel1 = new JPanel();
  JPanel jPanel2 = new JPanel();
  BorderLayout borderLayout2 = new BorderLayout();
  BorderLayout borderLayout3 = new BorderLayout();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JPanel jPanel3 = new JPanel();
  JPanel jPanel4 = new JPanel();
  JPanel jPanel5 = new JPanel();
  BorderLayout borderLayout4 = new BorderLayout();
  JPanel jPanel6 = new JPanel();
  JPanel jPanel7 = new JPanel();
  BorderLayout borderLayout5 = new BorderLayout();
  JPanel jPanel8 = new JPanel();
  Border border1;
  TitledBorder titledBorder1;
  BorderLayout borderLayout6 = new BorderLayout();
  JPanel jPanel9 = new JPanel();
  Border border2;
  TitledBorder titledBorder2;
  BorderLayout borderLayout7 = new BorderLayout();
  Border border3;
  Border border4;
  BorderLayout borderLayout8 = new BorderLayout();
  JPanel jPanel10 = new JPanel();
  Border border5;
  TitledBorder titledBorder3;
  Border border6;
  JPanel jPanel12 = new JPanel();
  JPanel jPanel13 = new JPanel();
  BorderLayout borderLayout10 = new BorderLayout();
  BorderLayout borderLayout11 = new BorderLayout();
  JPanel jPanel11 = new JPanel();
  BorderLayout borderLayout9 = new BorderLayout();
  JRadioButton jRadioButton1 = new JRadioButton();
  JRadioButton jRadioButton2 = new JRadioButton();
  JRadioButton jRadioButton3 = new JRadioButton();
  Border border7;
  Border border8;
  Border border9;
  Border border10;
  Border border11;
  Border border12;
  JCheckBox jCheckBox1 = new JCheckBox();
  JCheckBox jCheckBox2 = new JCheckBox();
  Border border13;
  JPanel jPanel18 = new JPanel();
  BorderLayout borderLayout16 = new BorderLayout();
  Border border14;
  Border border15;
  Border border16;
  JPanel jPanel14 = new JPanel();
  Border border17;
  BorderLayout borderLayout112 = new BorderLayout();
  JToggleButton jToggleButton6 = new JToggleButton();
  BorderLayout borderLayout19 = new BorderLayout();
  JPanel jPanel114 = new JPanel();
  JComboBox jComboBox6 = new JComboBox();
  JPanel jPanel111 = new JPanel();
  BorderLayout borderLayout114 = new BorderLayout();
  JToggleButton jToggleButton8 = new JToggleButton();
  BorderLayout borderLayout115 = new BorderLayout();
  JPanel jPanel116 = new JPanel();
  JComboBox jComboBox8 = new JComboBox();
  JPanel jPanel117 = new JPanel();
  BorderLayout borderLayout116 = new BorderLayout();
  JToggleButton jToggleButton9 = new JToggleButton();
  BorderLayout borderLayout117 = new BorderLayout();
  JPanel jPanel118 = new JPanel();
  JComboBox jComboBox9 = new JComboBox();
  JPanel jPanel119 = new JPanel();
  GridLayout gridLayout1 = new GridLayout();
  JPanel jPanel15 = new JPanel();
  Border border18;
  BorderLayout borderLayout12 = new BorderLayout();
  JPanel jPanel16 = new JPanel();
  JPanel jPanel17 = new JPanel();
  JPanel jPanel19 = new JPanel();
  BorderLayout borderLayout14 = new BorderLayout();
  JRadioButton jRadioButton4 = new JRadioButton();
  JRadioButton jRadioButton5 = new JRadioButton();
  JToggleButton jToggleButton1 = new JToggleButton();
  Border border19;
  BorderLayout borderLayout15 = new BorderLayout();
  JPanel jPanel20 = new JPanel();
  JPanel jPanel21 = new JPanel();
  JPanel jPanel22 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  GridLayout gridLayout3 = new GridLayout();
  Border border20;
  JToggleButton jToggleButton2 = new JToggleButton();
  JToggleButton jToggleButton3 = new JToggleButton();
  JToggleButton jToggleButton4 = new JToggleButton();
  JToggleButton jToggleButton5 = new JToggleButton();
  JToggleButton jToggleButton7 = new JToggleButton();
  JToggleButton jToggleButton10 = new JToggleButton();
  JToggleButton jToggleButton11 = new JToggleButton();
  JToggleButton jToggleButton12 = new JToggleButton();
  JToggleButton jToggleButton13 = new JToggleButton();
  JToggleButton jToggleButton14 = new JToggleButton();
  JToggleButton jToggleButton15 = new JToggleButton();
  JToggleButton jToggleButton16 = new JToggleButton();
  JToggleButton jToggleButton17 = new JToggleButton();
  JToggleButton jToggleButton18 = new JToggleButton();
  JToggleButton jToggleButton19 = new JToggleButton();
  JToggleButton jToggleButton20 = new JToggleButton();
  JToggleButton jToggleButton21 = new JToggleButton();
  JToggleButton jToggleButton22 = new JToggleButton();
  JToggleButton jToggleButton23 = new JToggleButton();
  JToggleButton jToggleButton24 = new JToggleButton();
  JToggleButton jToggleButton25 = new JToggleButton();
  JToggleButton jToggleButton26 = new JToggleButton();
  JToggleButton jToggleButton27 = new JToggleButton();
  JToggleButton jToggleButton28 = new JToggleButton();
  JToggleButton jToggleButton29 = new JToggleButton();
  JToggleButton jToggleButton30 = new JToggleButton();
  JToggleButton jToggleButton31 = new JToggleButton();
  JToggleButton jToggleButton32 = new JToggleButton();
  JToggleButton jToggleButton33 = new JToggleButton();
  JToggleButton jToggleButton34 = new JToggleButton();
  JToggleButton jToggleButton35 = new JToggleButton();
  JToggleButton jToggleButton36 = new JToggleButton();
  JToggleButton jToggleButton37 = new JToggleButton();
  JToggleButton jToggleButton38 = new JToggleButton();
  JToggleButton jToggleButton39 = new JToggleButton();
  JToggleButton jToggleButton40 = new JToggleButton();
  JToggleButton jToggleButton41 = new JToggleButton();
  JToggleButton jToggleButton42 = new JToggleButton();
  JToggleButton jToggleButton43 = new JToggleButton();
  JToggleButton jToggleButton44 = new JToggleButton();
  JLabel jLabel1 = new JLabel();
  JToggleButton jToggleButton45 = new JToggleButton();
  JToggleButton jToggleButton46 = new JToggleButton();
  JToggleButton jToggleButton47 = new JToggleButton();
  JToggleButton jToggleButton48 = new JToggleButton();
  JToggleButton jToggleButton49 = new JToggleButton();
  JToggleButton jToggleButton50 = new JToggleButton();
  JToggleButton jToggleButton51 = new JToggleButton();
  JToggleButton jToggleButton52 = new JToggleButton();
  JToggleButton jToggleButton53 = new JToggleButton();
  JToggleButton jToggleButton54 = new JToggleButton();
  JToggleButton jToggleButton55 = new JToggleButton();
  JToggleButton jToggleButton56 = new JToggleButton();
  JToggleButton jToggleButton57 = new JToggleButton();
  JToggleButton jToggleButton58 = new JToggleButton();
  JToggleButton jToggleButton59 = new JToggleButton();
  JToggleButton jToggleButton60 = new JToggleButton();
  JButton jButton3 = new JButton();
  BorderLayout borderLayout13 = new BorderLayout();
  Border border21;
  Border border22;
  Border border23;
  BorderLayout borderLayout17 = new BorderLayout();
  Border border24;
  JPanel jPanel23 = new JPanel();
  JPanel jPanel24 = new JPanel();
  BorderLayout borderLayout18 = new BorderLayout();
  BorderLayout borderLayout20 = new BorderLayout();
  JButton jButton1 = new JButton();
  JButton jButton2 = new JButton();
  Border border25;
  Border border26;
  BorderLayout borderLayout21 = new BorderLayout();
  JPanel jPanel25 = new JPanel();
  JPanel jPanel26 = new JPanel();
  JPanel jPanel27 = new JPanel();
  BorderLayout borderLayout22 = new BorderLayout();
  BorderLayout borderLayout23 = new BorderLayout();
  BorderLayout borderLayout24 = new BorderLayout();
  JPanel jPanel28 = new JPanel();
  JPanel jPanel29 = new JPanel();
  BorderLayout borderLayout25 = new BorderLayout();
  BorderLayout borderLayout26 = new BorderLayout();
  Border border27;
  JPanel jPanel30 = new JPanel();
  JPanel jPanel31 = new JPanel();
  JPanel jPanel32 = new JPanel();
  BorderLayout borderLayout27 = new BorderLayout();
  BorderLayout borderLayout28 = new BorderLayout();
  BorderLayout borderLayout29 = new BorderLayout();
  JToggleButton jToggleButton61 = new JToggleButton();
  JPanel jPanel33 = new JPanel();
  JPanel jPanel34 = new JPanel();
  BorderLayout borderLayout30 = new BorderLayout();
  BorderLayout borderLayout31 = new BorderLayout();
  JTextField jTextField1 = new JTextField();
  JScrollPane jScrollPane1 = new JScrollPane();
  JPanel jPanel35 = new JPanel();
  GridLayout gridLayout4 = new GridLayout();
  Border border28;
  Border border29;
  JScrollPane jScrollPane2 = new JScrollPane();
  JPanel jPanel36 = new JPanel();
  JPanel jPanel37 = new JPanel();
  JPanel jPanel38 = new JPanel();
  GridLayout gridLayout5 = new GridLayout();
  JTextField jTextField2 = new JTextField();
  BorderLayout borderLayout32 = new BorderLayout();
  BorderLayout borderLayout33 = new BorderLayout();
  JToggleButton jToggleButton62 = new JToggleButton();
  JScrollPane jScrollPane3 = new JScrollPane();
  JPanel jPanel39 = new JPanel();
  JPanel jPanel310 = new JPanel();
  JPanel jPanel311 = new JPanel();
  GridLayout gridLayout6 = new GridLayout();
  JTextField jTextField3 = new JTextField();
  BorderLayout borderLayout34 = new BorderLayout();
  BorderLayout borderLayout35 = new BorderLayout();
  JToggleButton jToggleButton63 = new JToggleButton();
  Border border30;
  JPanel jPanel40 = new JPanel();
  JPanel jPanel41 = new JPanel();
  JPanel jPanel42 = new JPanel();
  BorderLayout borderLayout36 = new BorderLayout();
  BorderLayout borderLayout37 = new BorderLayout();
  BorderLayout borderLayout38 = new BorderLayout();
  JPanel jPanel43 = new JPanel();
  JPanel jPanel44 = new JPanel();
  BorderLayout borderLayout39 = new BorderLayout();
  JToggleButton jToggleButton64 = new JToggleButton();
  JComboBox jComboBox1 = new JComboBox();
  BorderLayout borderLayout40 = new BorderLayout();
  JPanel jPanel45 = new JPanel();
  JPanel jPanel46 = new JPanel();
  BorderLayout borderLayout41 = new BorderLayout();
  BorderLayout borderLayout310 = new BorderLayout();
  JToggleButton jToggleButton65 = new JToggleButton();
  JComboBox jComboBox2 = new JComboBox();
  JPanel jPanel47 = new JPanel();
  JPanel jPanel48 = new JPanel();
  BorderLayout borderLayout42 = new BorderLayout();
  BorderLayout borderLayout311 = new BorderLayout();
  JToggleButton jToggleButton66 = new JToggleButton();
  JComboBox jComboBox3 = new JComboBox();
  Border border31;
  JPanel jPanel49 = new JPanel();
  JPanel jPanel50 = new JPanel();
  BorderLayout borderLayout43 = new BorderLayout();
  BorderLayout borderLayout44 = new BorderLayout();
  Border border32;
  TitledBorder titledBorder4;
  JCheckBox jCheckBox3 = new JCheckBox();
  Border border33;
  JCheckBox jCheckBox4 = new JCheckBox();
  JCheckBox jCheckBox5 = new JCheckBox();
  Border border34;
  TitledBorder titledBorder5;
  JCheckBox jCheckBox6 = new JCheckBox();
  Border border35;
  JLabel jLabel2 = new JLabel();
  Border border36;
  Border border37;
  Border border38;
  Border border39;
  Border border40;
  BorderLayout borderLayout45 = new BorderLayout();
  JPanel jPanel51 = new JPanel();
  JPanel jPanel52 = new JPanel();
  BorderLayout borderLayout46 = new BorderLayout();
  BorderLayout borderLayout47 = new BorderLayout();
  Border border41;
  JPanel jPanel53 = new JPanel();
  BorderLayout borderLayout48 = new BorderLayout();
  Border border42;
  TitledBorder titledBorder6;
  JRadioButton jRadioButton6 = new JRadioButton();
  JRadioButton jRadioButton8 = new JRadioButton();
  Border border43;
  JRadioButton jRadioButton9 = new JRadioButton();
  JPanel jPanel54 = new JPanel();
  BorderLayout borderLayout49 = new BorderLayout();
  JCheckBox jCheckBox7 = new JCheckBox();
  JCheckBox jCheckBox8 = new JCheckBox();
  Border border44;
  JPanel jPanel55 = new JPanel();
  BorderLayout borderLayout50 = new BorderLayout();
  JTextArea jTextArea1 = new JTextArea();
  Border border45;
  JLabel jLabel3 = new JLabel();
  JPanel jPanel56 = new JPanel();
  JPanel jPanel57 = new JPanel();
  JPanel jPanel58 = new JPanel();
  JPanel jPanel59 = new JPanel();
  JPanel jPanel60 = new JPanel();
  JLabel jLabel4 = new JLabel();
  JLabel jLabel5 = new JLabel();
  JLabel jLabel6 = new JLabel();
  JLabel jLabel7 = new JLabel();
  GridLayout gridLayout7 = new GridLayout();
  GridLayout gridLayout8 = new GridLayout();
  GridLayout gridLayout9 = new GridLayout();
  GridLayout gridLayout10 = new GridLayout();
  GridLayout gridLayout11 = new GridLayout();
  JPanel jPanel61 = new JPanel();
  JPanel jPanel62 = new JPanel();
  JPanel jPanel63 = new JPanel();
  JPanel jPanel64 = new JPanel();
  JPanel jPanel65 = new JPanel();
  JPanel jPanel66 = new JPanel();
  JPanel jPanel67 = new JPanel();
  JPanel jPanel68 = new JPanel();
  JPanel jPanel69 = new JPanel();
  JPanel jPanel610 = new JPanel();
  JPanel jPanel611 = new JPanel();
  JPanel jPanel612 = new JPanel();
  JPanel jPanel613 = new JPanel();
  JPanel jPanel614 = new JPanel();
  JPanel jPanel615 = new JPanel();
  JPanel jPanel616 = new JPanel();
  JPanel jPanel617 = new JPanel();
  JLabel jLabel8 = new JLabel();
  GridLayout gridLayout12 = new GridLayout();
  GridLayout gridLayout13 = new GridLayout();
  JLabel jLabel9 = new JLabel();
  JLabel jLabel10 = new JLabel();
  JLabel jLabel11 = new JLabel();
  JLabel jLabel12 = new JLabel();
  JLabel jLabel13 = new JLabel();
  JLabel jLabel14 = new JLabel();
  JLabel jLabel15 = new JLabel();
  JLabel jLabel16 = new JLabel();
  JLabel jLabel17 = new JLabel();
  JLabel jLabel18 = new JLabel();
  JLabel jLabel19 = new JLabel();
  JLabel jLabel110 = new JLabel();
  JLabel jLabel111 = new JLabel();
  JLabel jLabel112 = new JLabel();
  JLabel jLabel113 = new JLabel();
  JLabel jLabel114 = new JLabel();
  GridLayout gridLayout14 = new GridLayout();
  GridLayout gridLayout15 = new GridLayout();
  GridLayout gridLayout16 = new GridLayout();
  GridLayout gridLayout17 = new GridLayout();
  GridLayout gridLayout18 = new GridLayout();
  GridLayout gridLayout19 = new GridLayout();
  GridLayout gridLayout20 = new GridLayout();
  GridLayout gridLayout21 = new GridLayout();
  GridLayout gridLayout22 = new GridLayout();
  GridLayout gridLayout23 = new GridLayout();
  GridLayout gridLayout24 = new GridLayout();
  GridLayout gridLayout25 = new GridLayout();
  GridLayout gridLayout26 = new GridLayout();
  GridLayout gridLayout27 = new GridLayout();
  GridLayout gridLayout28 = new GridLayout();
  JPanel jPanel70 = new JPanel();
  BorderLayout borderLayout51 = new BorderLayout();
  JToggleButton jToggleButton67 = new JToggleButton();
  JLabel jLabel20 = new JLabel();
  BorderLayout borderLayout52 = new BorderLayout();
  JPanel jPanel71 = new JPanel();
  JToggleButton jToggleButton68 = new JToggleButton();
  JLabel jLabel21 = new JLabel();
  BorderLayout borderLayout53 = new BorderLayout();
  JPanel jPanel72 = new JPanel();
  JToggleButton jToggleButton69 = new JToggleButton();
  JLabel jLabel22 = new JLabel();
  BorderLayout borderLayout54 = new BorderLayout();
  JPanel jPanel73 = new JPanel();
  JToggleButton jToggleButton610 = new JToggleButton();
  JLabel jLabel23 = new JLabel();
  JToggleButton jToggleButton70 = new JToggleButton();
  Border border46;

  //Construct the frame
  public ChartExtentStyleEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    contentPane = (JPanel) this.getContentPane();
    border1 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder1 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"테두리");
    border2 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder2 = new TitledBorder(border2,"보기");
    border3 = BorderFactory.createEmptyBorder(5,5,0,8);
    border4 = BorderFactory.createEmptyBorder(2,3,4,3);
    border5 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder3 = new TitledBorder(border5,"영역");
    border6 = BorderFactory.createEmptyBorder(0,4,0,35);
    border7 = BorderFactory.createEmptyBorder(0,6,0,0);
    border8 = BorderFactory.createEmptyBorder(2,0,1,0);
    border9 = BorderFactory.createEmptyBorder(3,3,3,2);
    border10 = BorderFactory.createEmptyBorder(0,9,5,0);
    border11 = BorderFactory.createEmptyBorder(5,8,5,1);
    border12 = BorderFactory.createEmptyBorder(1,8,1,3);
    border13 = BorderFactory.createEmptyBorder(0,5,0,0);
    border14 = BorderFactory.createEmptyBorder(3,0,3,0);
    border15 = BorderFactory.createEmptyBorder(4,0,4,0);
    border16 = BorderFactory.createEmptyBorder(4,0,4,0);
    border17 = BorderFactory.createEmptyBorder(0,9,2,2);
    border18 = BorderFactory.createEmptyBorder(0,0,2,0);
    border19 = BorderFactory.createEmptyBorder(0,5,0,0);
    border20 = BorderFactory.createEmptyBorder(2,5,0,5);
    border21 = BorderFactory.createEmptyBorder(5,8,0,8);
    border22 = BorderFactory.createEmptyBorder();
    border23 = BorderFactory.createEmptyBorder();
    border24 = BorderFactory.createEmptyBorder(2,0,2,0);
    border25 = BorderFactory.createEmptyBorder(5,1,1,1);
    border26 = BorderFactory.createEmptyBorder(5,0,1,0);
    border27 = BorderFactory.createEmptyBorder(2,5,1,5);
    border28 = BorderFactory.createEmptyBorder(0,0,1,0);
    border29 = BorderFactory.createEmptyBorder(0,0,1,0);
    border30 = BorderFactory.createEmptyBorder(0,0,0,50);
    border31 = BorderFactory.createEmptyBorder(0,0,0,2);
    border32 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder4 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"효과");
    border33 = BorderFactory.createCompoundBorder(titledBorder4,BorderFactory.createEmptyBorder(0,5,0,0));
    border34 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder5 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"미리 보기");
    border35 = BorderFactory.createEmptyBorder(0,6,15,0);
    border36 = BorderFactory.createEmptyBorder(1,0,1,0);
    border37 = BorderFactory.createEmptyBorder(1,0,1,2);
    border38 = BorderFactory.createEmptyBorder(1,0,1,0);
    border39 = BorderFactory.createEmptyBorder(0,4,0,5);
    border40 = BorderFactory.createEmptyBorder(0,0,0,2);
    border41 = BorderFactory.createEmptyBorder(0,3,0,0);
    border42 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder6 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"개체 위치");
    border43 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"개체 위치"),BorderFactory.createEmptyBorder(0,5,0,0));
    border44 = BorderFactory.createEmptyBorder(1,0,30,70);
    border45 = BorderFactory.createEmptyBorder();
    border46 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"미리 보기"),BorderFactory.createEmptyBorder(0,0,2,0));
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(419, 368));
    this.setTitle("차트 영역 서식");
    jPanel1.setLayout(borderLayout2);
    jPanel2.setLayout(borderLayout3);
    jPanel1.setBorder(border22);
    jPanel1.setPreferredSize(new Dimension(0, 305));
    jPanel2.setBorder(border24);
    jPanel2.setPreferredSize(new Dimension(0, 30));
    jPanel3.setLayout(borderLayout4);
    jPanel6.setPreferredSize(new Dimension(180, 0));
    jPanel6.setLayout(borderLayout5);
    jPanel7.setLayout(borderLayout8);
    jPanel8.setBorder(titledBorder1);
    jPanel8.setLayout(borderLayout6);
    jPanel9.setBorder(titledBorder2);
    jPanel9.setPreferredSize(new Dimension(12, 47));
    jPanel9.setLayout(borderLayout7);
    contentPane.setBorder(border3);
    jPanel3.setBorder(border4);
    jPanel10.setBorder(titledBorder3);
    jPanel10.setLayout(borderLayout12);
    jPanel7.setBorder(border6);
    jTabbedPane1.setBorder(border22);
    jTabbedPane1.setPreferredSize(new Dimension(241, 74));
    jTabbedPane1.setRequestFocusEnabled(false);
    jPanel13.setPreferredSize(new Dimension(0, 55));
    jPanel13.setLayout(borderLayout10);
    jPanel12.setBorder(border13);
    jPanel12.setPreferredSize(new Dimension(0, 55));
    jPanel12.setLayout(borderLayout11);
    jPanel11.setBorder(border7);
    jPanel11.setPreferredSize(new Dimension(0, 57));
    jPanel11.setLayout(borderLayout9);
    jRadioButton1.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton1.setMnemonic('A');
    jRadioButton1.setText("자동(A)");
    jRadioButton1.setRequestFocusEnabled(false);
    jRadioButton2.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton2.setText("사용자 정의");
    jRadioButton2.setRequestFocusEnabled(false);
    jRadioButton3.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton3.setMnemonic('N');
    jRadioButton3.setText("없음(N)");
    jRadioButton3.setRequestFocusEnabled(false);
    jCheckBox1.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox1.setMnemonic('D');
    jCheckBox1.setText("그림자(D)");
    jCheckBox2.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox2.setMnemonic('R');
    jCheckBox2.setText("모서리를 둥글게(R)");
    jPanel18.setPreferredSize(new Dimension(10, 20));
    jPanel18.setLayout(borderLayout16);
    jPanel14.setLayout(gridLayout1);
    jPanel14.setBorder(border17);
    jPanel14.setPreferredSize(new Dimension(11, 82));
    jToggleButton6.setRequestFocusEnabled(false);
    jToggleButton6.setText("두께(W):      ");
    jToggleButton6.setMnemonic('W');
    jToggleButton6.setBorder(null);
    jToggleButton6.setMargin(new Insets(0, 0, 0, 0));
    jPanel114.setBorder(border14);
    jPanel114.setLayout(borderLayout112);
    jPanel111.setPreferredSize(new Dimension(0, 29));
    jPanel111.setBackground(Color.pink);
    jPanel111.setLayout(borderLayout19);
    jToggleButton8.setRequestFocusEnabled(false);
    jToggleButton8.setText("색(C):           ");
    jToggleButton8.setMnemonic('C');
    jToggleButton8.setBorder(null);
    jToggleButton8.setMargin(new Insets(0, 0, 0, 0));
    jPanel116.setBorder(border14);
    jPanel116.setLayout(borderLayout114);
    jPanel117.setPreferredSize(new Dimension(0, 29));
    jPanel117.setBackground(Color.pink);
    jPanel117.setLayout(borderLayout115);
    jToggleButton9.setRequestFocusEnabled(false);
    jToggleButton9.setText("스타일(S):   ");
    jToggleButton9.setMnemonic('S');
    jToggleButton9.setBorder(null);
    jToggleButton9.setMargin(new Insets(0, 0, 0, 0));
    jPanel118.setBorder(border14);
    jPanel118.setLayout(borderLayout116);
    jPanel119.setPreferredSize(new Dimension(0, 29));
    jPanel119.setBackground(Color.pink);
    jPanel119.setLayout(borderLayout117);
    gridLayout1.setColumns(1);
    gridLayout1.setRows(3);
    jPanel15.setLayout(borderLayout17);
    jPanel15.setBorder(border18);
    jPanel15.setPreferredSize(new Dimension(160, 0));
    jPanel16.setBorder(border19);
    jPanel16.setPreferredSize(new Dimension(0, 55));
    jPanel16.setLayout(borderLayout14);
    jPanel17.setBorder(border21);
    jPanel17.setPreferredSize(new Dimension(0, 47));
    jPanel17.setLayout(borderLayout13);
    jPanel19.setLayout(borderLayout15);
    jRadioButton4.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton4.setMnemonic('U');
    jRadioButton4.setText("자동(U)");
    jRadioButton4.setRequestFocusEnabled(false);
    jRadioButton5.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton5.setMnemonic('E');
    jRadioButton5.setText("없음(E)");
    jRadioButton5.setRequestFocusEnabled(false);
    jToggleButton1.setBorder(null);
    jToggleButton1.setMnemonic('O');
    jToggleButton1.setVerticalTextPosition(SwingConstants.BOTTOM);
    jToggleButton1.setText("색(O):");
    jToggleButton1.setRequestFocusEnabled(false);
    jToggleButton1.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton1.setVerticalAlignment(SwingConstants.BOTTOM);
    jPanel20.setPreferredSize(new Dimension(0, 90));
    jPanel20.setLayout(gridLayout2);
    jPanel21.setPreferredSize(new Dimension(0, 36));
    jPanel21.setLayout(gridLayout3);
    gridLayout2.setColumns(8);
    gridLayout2.setHgap(3);
    gridLayout2.setRows(5);
    gridLayout2.setVgap(3);
    jPanel19.setBorder(border20);
    jToggleButton2.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-01.gif")));
    jToggleButton2.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton2.setRequestFocusEnabled(false);
    jToggleButton3.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-39.gif")));
    jToggleButton3.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton3.setRequestFocusEnabled(false);
    jToggleButton4.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-02.gif")));
    jToggleButton4.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton4.setRequestFocusEnabled(false);
    jToggleButton5.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-04.gif")));
    jToggleButton5.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton7.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-06.gif")));
    jToggleButton7.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton7.setRequestFocusEnabled(false);
    jToggleButton10.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-03.gif")));
    jToggleButton10.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton10.setRequestFocusEnabled(false);
    jToggleButton11.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-07.gif")));
    jToggleButton11.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton11.setRequestFocusEnabled(false);
    jToggleButton12.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-05.gif")));
    jToggleButton12.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton12.setRequestFocusEnabled(false);
    jToggleButton13.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-08.gif")));
    jToggleButton13.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton13.setRequestFocusEnabled(false);
    jToggleButton14.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-11.gif")));
    jToggleButton14.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton14.setRequestFocusEnabled(false);
    jToggleButton15.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-38.gif")));
    jToggleButton15.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton15.setRequestFocusEnabled(false);
    jToggleButton16.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-10.gif")));
    jToggleButton16.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton16.setRequestFocusEnabled(false);
    jToggleButton17.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-14.gif")));
    jToggleButton17.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton17.setRequestFocusEnabled(false);
    jToggleButton18.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-17.gif")));
    jToggleButton18.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton18.setRequestFocusEnabled(false);
    jToggleButton19.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-15.gif")));
    jToggleButton19.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton19.setRequestFocusEnabled(false);
    jToggleButton20.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-18.gif")));
    jToggleButton20.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton20.setRequestFocusEnabled(false);
    jToggleButton21.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-13.gif")));
    jToggleButton21.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton21.setRequestFocusEnabled(false);
    jToggleButton22.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-37.gif")));
    jToggleButton22.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton22.setRequestFocusEnabled(false);
    jToggleButton23.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-40.gif")));
    jToggleButton23.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton23.setRequestFocusEnabled(false);
    jToggleButton24.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-35.gif")));
    jToggleButton24.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton24.setRequestFocusEnabled(false);
    jToggleButton25.setIcon(new ImageIcon(jcosmos.Utility.getResource( "chartextent1-12.gif")));
    jToggleButton25.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton25.setRequestFocusEnabled(false);
    jToggleButton26.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-20.gif")));
    jToggleButton26.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton26.setRequestFocusEnabled(false);
    jToggleButton27.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-22.gif")));
    jToggleButton27.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton27.setRequestFocusEnabled(false);
    jToggleButton28.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-23.gif")));
    jToggleButton28.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton28.setRequestFocusEnabled(false);
    jToggleButton29.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-36.gif")));
    jToggleButton29.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton29.setRequestFocusEnabled(false);
    jToggleButton30.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-19.gif")));
    jToggleButton30.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton30.setRequestFocusEnabled(false);
    jToggleButton31.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-25.gif")));
    jToggleButton31.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton31.setRequestFocusEnabled(false);
    jToggleButton32.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-26.gif")));
    jToggleButton32.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton32.setRequestFocusEnabled(false);
    jToggleButton33.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-27.gif")));
    jToggleButton33.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton33.setRequestFocusEnabled(false);
    jToggleButton34.setIcon(new ImageIcon(jcosmos.Utility.getResource( "chartextent1-29.gif")));
    jToggleButton34.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton34.setRequestFocusEnabled(false);
    jToggleButton35.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-09.gif")));
    jToggleButton35.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton35.setRequestFocusEnabled(false);
    jToggleButton36.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-24.gif")));
    jToggleButton36.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton36.setRequestFocusEnabled(false);
    jToggleButton37.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-28.gif")));
    jToggleButton37.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton37.setRequestFocusEnabled(false);
    jToggleButton38.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-34.gif")));
    jToggleButton38.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton38.setRequestFocusEnabled(false);
    jToggleButton39.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-33.gif")));
    jToggleButton39.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton39.setRequestFocusEnabled(false);
    jToggleButton40.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-16.gif")));
    jToggleButton40.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton40.setRequestFocusEnabled(false);
    jToggleButton41.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-21.gif")));
    jToggleButton41.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton41.setRequestFocusEnabled(false);
    jToggleButton42.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-30.gif")));
    jToggleButton42.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton42.setRequestFocusEnabled(false);
    jToggleButton43.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-31.gif")));
    jToggleButton43.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton43.setRequestFocusEnabled(false);
    jToggleButton44.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-32.gif")));
    jToggleButton44.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton44.setRequestFocusEnabled(false);
    jLabel1.setBorder(BorderFactory.createEtchedBorder());
    jLabel1.setPreferredSize(new Dimension(150, 2));
    gridLayout3.setColumns(8);
    gridLayout3.setHgap(3);
    gridLayout3.setRows(2);
    gridLayout3.setVgap(3);
    jToggleButton45.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-41.gif")));
    jToggleButton45.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton45.setRequestFocusEnabled(false);
    jToggleButton46.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-56.gif")));
    jToggleButton46.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton46.setRequestFocusEnabled(false);
    jToggleButton47.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-55.gif")));
    jToggleButton47.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton47.setRequestFocusEnabled(false);
    jToggleButton48.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-54.gif")));
    jToggleButton48.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton48.setRequestFocusEnabled(false);
    jToggleButton49.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-49.gif")));
    jToggleButton49.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton49.setRequestFocusEnabled(false);
    jToggleButton50.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-53.gif")));
    jToggleButton50.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton50.setRequestFocusEnabled(false);
    jToggleButton51.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-45.gif")));
    jToggleButton51.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton51.setRequestFocusEnabled(false);
    jToggleButton52.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-52.gif")));
    jToggleButton52.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton52.setRequestFocusEnabled(false);
    jToggleButton53.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-43.gif")));
    jToggleButton53.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton53.setRequestFocusEnabled(false);
    jToggleButton54.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-50.gif")));
    jToggleButton54.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton54.setRequestFocusEnabled(false);
    jToggleButton55.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-46.gif")));
    jToggleButton55.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton55.setRequestFocusEnabled(false);
    jToggleButton56.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-51.gif")));
    jToggleButton56.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton56.setRequestFocusEnabled(false);
    jToggleButton57.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-42.gif")));
    jToggleButton57.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton57.setRequestFocusEnabled(false);
    jToggleButton58.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-47.gif")));
    jToggleButton58.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton58.setRequestFocusEnabled(false);
    jToggleButton59.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-44.gif")));
    jToggleButton59.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton59.setRequestFocusEnabled(false);
    jToggleButton60.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-48.gif")));
    jToggleButton60.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton60.setRequestFocusEnabled(false);
    jButton3.setMaximumSize(new Dimension(115, 50));
    jButton3.setPreferredSize(new Dimension(115, 20));
    jButton3.setText("채우기 효과(I)..");
    borderLayout17.setHgap(5);
    jPanel23.setBorder(border25);
    jPanel23.setMinimumSize(new Dimension(50, 10));
    jPanel23.setPreferredSize(new Dimension(80, 0));
    jPanel23.setLayout(borderLayout18);
    jPanel24.setBorder(border26);
    jPanel24.setLayout(borderLayout20);
    jButton1.setText("확인");
    jButton2.setText("취소");
    jPanel22.setPreferredSize(new Dimension(160, 10));
    jPanel4.setLayout(borderLayout21);
    jPanel25.setBorder(border27);
    jPanel25.setMinimumSize(new Dimension(0, 130));
    jPanel25.setPreferredSize(new Dimension(0, 122));
    jPanel25.setLayout(borderLayout22);
    jPanel26.setBorder(border35);
    jPanel26.setMinimumSize(new Dimension(0, 50));
    jPanel26.setPreferredSize(new Dimension(0, 70));
    jPanel26.setLayout(borderLayout23);
    jPanel27.setBorder(border39);
    jPanel27.setPreferredSize(new Dimension(0, 50));
    jPanel27.setLayout(borderLayout24);
    jPanel28.setLayout(borderLayout25);
    jPanel28.setPreferredSize(new Dimension(0, 76));
    jPanel29.setLayout(borderLayout26);
    jPanel29.setBorder(border31);
    jPanel29.setPreferredSize(new Dimension(397, 35));
    jPanel30.setLayout(borderLayout27);
    jPanel30.setBackground(Color.magenta);
    jPanel30.setPreferredSize(new Dimension(155, 0));
    jPanel31.setLayout(borderLayout28);
    jPanel31.setBorder(border30);
    jPanel31.setPreferredSize(new Dimension(115, 0));
    jPanel32.setLayout(borderLayout29);
    jToggleButton61.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton61.setBorder(null);
    jToggleButton61.setMnemonic('F');
    jToggleButton61.setText("글꼴(F):");
    jToggleButton61.setRequestFocusEnabled(false);
    jToggleButton61.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel33.setLayout(borderLayout30);
    jPanel34.setLayout(borderLayout31);
    jPanel33.setBorder(border29);
    jPanel33.setPreferredSize(new Dimension(0, 40));
    jTextField1.setText(" 돋움");
    jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane1.getViewport().setBackground(Color.white);
    jScrollPane1.setBorder(BorderFactory.createLoweredBevelBorder());
    jPanel35.setLayout(gridLayout4);
    jPanel35.setBackground(Color.white);
    jPanel35.setPreferredSize(new Dimension(0, 50));
    jPanel34.setBorder(border28);
    jPanel34.setPreferredSize(new Dimension(28, 20));
    jScrollPane2.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jPanel36.setLayout(gridLayout5);
    jPanel36.setBackground(Color.white);
    jPanel36.setPreferredSize(new Dimension(10, 48));
    jPanel37.setLayout(borderLayout32);
    jPanel37.setBorder(border28);
    jPanel37.setPreferredSize(new Dimension(28, 20));
    jPanel38.setLayout(borderLayout33);
    jPanel38.setBorder(border29);
    jPanel38.setPreferredSize(new Dimension(0, 40));
    jTextField2.setText(" 보통");
    jToggleButton62.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton62.setBorder(null);
    jToggleButton62.setMnemonic('O');
    jToggleButton62.setText("글꼴 스타일(O):");
    jToggleButton62.setRequestFocusEnabled(false);
    jToggleButton62.setHorizontalAlignment(SwingConstants.LEFT);
    jScrollPane3.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane3.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jPanel39.setLayout(gridLayout6);
    jPanel39.setBackground(Color.white);
    jPanel310.setLayout(borderLayout34);
    jPanel310.setBorder(border28);
    jPanel311.setLayout(borderLayout35);
    jPanel311.setBorder(border29);
    jPanel311.setPreferredSize(new Dimension(0, 40));
    jTextField3.setText("9");
    jToggleButton63.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton63.setBorder(null);
    jToggleButton63.setMnemonic('S');
    jToggleButton63.setText("크기(S):");
    jToggleButton63.setRequestFocusEnabled(false);
    jToggleButton63.setHorizontalAlignment(SwingConstants.LEFT);
    borderLayout25.setHgap(10);
    borderLayout26.setHgap(10);
    jPanel40.setLayout(borderLayout36);
    jPanel42.setLayout(borderLayout37);
    jPanel41.setLayout(borderLayout38);
    jPanel40.setPreferredSize(new Dimension(155, 0));
    jPanel41.setBorder(border40);
    jPanel41.setPreferredSize(new Dimension(115, 0));
    jPanel43.setLayout(borderLayout39);
    jPanel43.setPreferredSize(new Dimension(0, 15));
    jToggleButton64.setBorder(null);
    jToggleButton64.setMnemonic('U');
    jToggleButton64.setText("밑줄(U):");
    jToggleButton64.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel44.setLayout(borderLayout40);
    jPanel45.setLayout(borderLayout41);
    jPanel46.setLayout(borderLayout310);
    jPanel46.setPreferredSize(new Dimension(0, 15));
    jToggleButton65.setBorder(null);
    jToggleButton65.setMnemonic('U');
    jToggleButton65.setText("배경(A):");
    jToggleButton65.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel47.setLayout(borderLayout42);
    jPanel48.setLayout(borderLayout311);
    jPanel48.setPreferredSize(new Dimension(0, 15));
    jToggleButton66.setBorder(null);
    jToggleButton66.setMnemonic('U');
    jToggleButton66.setText("색(C):");
    jToggleButton66.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel47.setBorder(border37);
    jPanel47.setPreferredSize(new Dimension(100, 22));
    jComboBox2.setPreferredSize(new Dimension(115, 22));
    borderLayout22.setVgap(5);
    jComboBox3.setMinimumSize(new Dimension(20, 2));
    jComboBox3.setPreferredSize(new Dimension(95, 22));
    jPanel49.setLayout(borderLayout43);
    jPanel50.setLayout(borderLayout44);
    jPanel49.setBorder(border33);
    jPanel49.setPreferredSize(new Dimension(157, 0));
    jPanel50.setBorder(border46);
    jPanel50.setPreferredSize(new Dimension(200, 0));
    jCheckBox3.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox3.setMnemonic('K');
    jCheckBox3.setText("취소선(K)");
    jCheckBox3.setRequestFocusEnabled(false);
    jCheckBox4.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox4.setMnemonic('E');
    jCheckBox4.setText("위 첨자(E)");
    jCheckBox4.setRequestFocusEnabled(false);
    jCheckBox5.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox5.setMnemonic('B');
    jCheckBox5.setText("아래 첨자(B)");
    jCheckBox5.setRequestFocusEnabled(false);
    borderLayout24.setHgap(8);
    jCheckBox6.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox6.setMnemonic('T');
    jCheckBox6.setText("자동 크기 조정(T)");
    jLabel2.setText("트루타입 글꼴입니다. 화면과 프린터에 사용되는 글꼴이 같습니다.");
    jLabel2.setVerticalAlignment(SwingConstants.TOP);
    jLabel2.setVerticalTextPosition(SwingConstants.TOP);
    borderLayout5.setVgap(1);
    jPanel44.setBorder(border36);
    jPanel45.setBorder(border38);
    jPanel32.setPreferredSize(new Dimension(87, 85));
    jPanel5.setLayout(borderLayout45);
    jPanel51.setLayout(borderLayout46);
    jPanel52.setLayout(borderLayout47);
    jPanel51.setPreferredSize(new Dimension(0, 80));
    jPanel5.setBorder(border41);
    jPanel53.setLayout(borderLayout48);
    jPanel53.setBorder(border43);
    jPanel53.setPreferredSize(new Dimension(230, 0));
    jRadioButton6.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton6.setPreferredSize(new Dimension(99, 22));
    jRadioButton6.setMnemonic('M');
    jRadioButton6.setText("위치만 변함(M)");
    jRadioButton8.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton8.setPreferredSize(new Dimension(99, 20));
    jRadioButton8.setMnemonic('D');
    jRadioButton8.setText("변하지 않음(D)");
    jRadioButton9.setText("위치와 크기 변함(S)");
    jRadioButton9.setMnemonic('S');
    jRadioButton9.setPreferredSize(new Dimension(99, 20));
    jRadioButton9.setMargin(new Insets(0, 0, 0, 0));
    jPanel54.setLayout(borderLayout49);
    jPanel54.setPreferredSize(new Dimension(0, 45));
    jCheckBox7.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox7.setMnemonic('P');
    jCheckBox7.setText("개체 인쇄(P)");
    jCheckBox8.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox8.setMnemonic('L');
    jCheckBox8.setText("잠금(L)");
    jPanel52.setBorder(border44);
    jPanel55.setLayout(borderLayout50);
    jTextArea1.setLineWrap(true);
    jTextArea1.setPreferredSize(new Dimension(300, 100));
    jTextArea1.setWrapStyleWord(true);
    jTextArea1.setTabSize(2);
    jTextArea1.setBackground(Color.lightGray);
    jTextArea1.setText("시트를 보호하지 않으면 개체를 잠그더라도 아무효과가 없습니다. 시트를 보호하려면 [도구] 메뉴에서 [보호] 선택한 후, " +
    "[시트 보호]를 선택하십시요. 암호를 설정할 수도 있습니다.");
    jTextArea1.setEditable(false);
    jPanel55.setBorder(border45);
    gridLayout6.setColumns(1);
    jLabel3.setText("jLabel3");
    jPanel56.setLayout(gridLayout11);
    jPanel56.setBackground(Color.white);
    jPanel56.setMinimumSize(new Dimension(10, 220));
    jPanel56.setPreferredSize(new Dimension(0, 205));
    gridLayout5.setColumns(1);
    gridLayout5.setRows(4);
    jPanel57.setBackground(Color.white);
    jPanel57.setLayout(gridLayout7);
    jLabel4.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel4.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel4.setText(" 보통");
    jPanel58.setLayout(gridLayout8);
    jPanel58.setBackground(Color.white);
    jLabel5.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel5.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel5.setText(" 기울임꼴");
    jPanel59.setLayout(gridLayout9);
    jPanel59.setBackground(Color.white);
    jPanel60.setLayout(gridLayout10);
    jLabel6.setText(" 굵게");
    jLabel7.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel7.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel7.setText(" 굵게 기울임꼴");
    gridLayout11.setColumns(1);
    gridLayout11.setRows(17);
    jLabel8.setText(" 6");
    jLabel8.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel8.setBackground(Color.white);
    jLabel8.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel61.setLayout(gridLayout12);
    jPanel61.setBackground(Color.white);
    jPanel617.setLayout(gridLayout13);
    jLabel9.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel9.setBackground(Color.white);
    jLabel9.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel9.setText(" 8");
    jPanel617.setBackground(Color.white);
    jLabel10.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel10.setBackground(Color.white);
    jLabel10.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel10.setText(" 9");
    jLabel11.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel11.setBackground(Color.white);
    jLabel11.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel11.setText(" 10");
    jLabel12.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel12.setBackground(Color.white);
    jLabel12.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel12.setText(" 11");
    jLabel13.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel13.setBackground(Color.white);
    jLabel13.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel13.setText(" 12");
    jLabel14.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel14.setBackground(Color.white);
    jLabel14.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel14.setText(" 14");
    jLabel15.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel15.setBackground(Color.white);
    jLabel15.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel15.setText(" 16");
    jLabel16.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel16.setBackground(Color.white);
    jLabel16.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel16.setText(" 18");
    jLabel17.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel17.setBackground(Color.white);
    jLabel17.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel17.setText(" 20");
    jLabel18.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel18.setBackground(Color.white);
    jLabel18.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel18.setText(" 22");
    jLabel19.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel19.setBackground(Color.white);
    jLabel19.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel19.setText(" 24");
    jLabel110.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel110.setBackground(Color.white);
    jLabel110.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel110.setText(" 26");
    jLabel111.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel111.setBackground(Color.white);
    jLabel111.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel111.setText(" 28");
    jLabel112.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel112.setBackground(Color.white);
    jLabel112.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel112.setText(" 36");
    jLabel113.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel113.setBackground(Color.white);
    jLabel113.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel113.setText(" 48");
    jLabel114.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel114.setBackground(Color.white);
    jLabel114.setHorizontalTextPosition(SwingConstants.LEFT);
    jLabel114.setText(" 72");
    jPanel616.setLayout(gridLayout14);
    jPanel616.setBackground(Color.white);
    jPanel615.setLayout(gridLayout15);
    jPanel615.setBackground(Color.white);
    jPanel614.setLayout(gridLayout16);
    jPanel614.setBackground(Color.white);
    jPanel613.setLayout(gridLayout17);
    jPanel613.setBackground(Color.white);
    jPanel612.setBackground(Color.white);
    jPanel612.setLayout(gridLayout18);
    jPanel611.setLayout(gridLayout19);
    jPanel610.setLayout(gridLayout20);
    jPanel610.setBackground(Color.white);
    jPanel62.setLayout(gridLayout21);
    jPanel62.setBackground(Color.white);
    jPanel63.setLayout(gridLayout22);
    jPanel63.setBackground(Color.white);
    jPanel64.setLayout(gridLayout23);
    jPanel64.setBackground(Color.white);
    jPanel65.setLayout(gridLayout24);
    jPanel65.setBackground(Color.white);
    jPanel66.setBackground(Color.white);
    jPanel66.setLayout(gridLayout25);
    jPanel67.setBackground(Color.white);
    jPanel67.setLayout(gridLayout26);
    jPanel68.setBackground(Color.white);
    jPanel68.setLayout(gridLayout27);
    jPanel69.setBackground(Color.white);
    jPanel69.setLayout(gridLayout28);
    jPanel611.setBackground(Color.white);
    gridLayout4.setColumns(1);
    gridLayout4.setRows(4);
    jPanel70.setLayout(borderLayout51);
    jToggleButton67.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent2-01.gif")));
    jToggleButton67.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton67.setBackground(Color.white);
    jToggleButton67.setBorder(null);
    jLabel20.setBackground(Color.white);
    jLabel20.setText("돋음");
    jPanel70.setBackground(Color.white);
    jPanel70.setPreferredSize(new Dimension(45, 15));
    jPanel71.setBackground(Color.white);
    jPanel71.setPreferredSize(new Dimension(45, 15));
    jPanel71.setLayout(borderLayout52);
    jToggleButton68.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent2-01.gif")));
    jToggleButton68.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton68.setBackground(Color.white);
    jToggleButton68.setBorder(null);
    jLabel21.setText("고딕체");
    jPanel72.setBackground(Color.white);
    jPanel72.setPreferredSize(new Dimension(45, 15));
    jPanel72.setLayout(borderLayout53);
    jToggleButton69.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent2-01.gif")));
    jToggleButton69.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton69.setBackground(Color.white);
    jToggleButton69.setBorder(null);
    jLabel22.setText("궁서체");
    jPanel73.setBackground(Color.white);
    jPanel73.setPreferredSize(new Dimension(45, 15));
    jPanel73.setLayout(borderLayout54);
    jToggleButton610.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent2-01.gif")));
    jToggleButton610.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton610.setBackground(Color.white);
    jToggleButton610.setBorder(null);
    jLabel23.setText("명조체");
    jToggleButton70.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent2-02.gif")));
    jToggleButton70.setBorder(null);
    jToggleButton70.setRequestFocusEnabled(false);
    contentPane.add(jPanel1, BorderLayout.NORTH);
    jPanel1.add(jTabbedPane1, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel3, "   무늬   ");
    jPanel3.add(jPanel6, BorderLayout.WEST);
    jPanel6.add(jPanel8, BorderLayout.CENTER);
    jPanel8.add(jPanel12, BorderLayout.SOUTH);
    jPanel12.add(jCheckBox1, BorderLayout.NORTH);
    jPanel12.add(jCheckBox2, BorderLayout.CENTER);
    jPanel12.add(jPanel18, BorderLayout.SOUTH);
    jPanel8.add(jPanel13, BorderLayout.NORTH);
    jPanel13.add(jPanel11, BorderLayout.NORTH);
    jPanel11.add(jRadioButton1, BorderLayout.NORTH);
    jPanel11.add(jRadioButton2, BorderLayout.SOUTH);
    jPanel11.add(jRadioButton3, BorderLayout.CENTER);
    jPanel8.add(jPanel14, BorderLayout.CENTER);
    jPanel14.add(jPanel119, null);
    jPanel119.add(jToggleButton9, BorderLayout.WEST);
    jPanel119.add(jPanel118, BorderLayout.CENTER);
    jPanel118.add(jComboBox9, BorderLayout.CENTER);
    jPanel14.add(jPanel117, null);
    jPanel117.add(jToggleButton8, BorderLayout.WEST);
    jPanel117.add(jPanel116, BorderLayout.CENTER);
    jPanel116.add(jComboBox8, BorderLayout.CENTER);
    jPanel14.add(jPanel111, null);
    jPanel111.add(jToggleButton6, BorderLayout.WEST);
    jPanel111.add(jPanel114, BorderLayout.CENTER);
    jPanel114.add(jComboBox6, BorderLayout.CENTER);
    jPanel6.add(jPanel9, BorderLayout.SOUTH);
    jPanel3.add(jPanel7, BorderLayout.CENTER);
    jPanel7.add(jPanel10, BorderLayout.CENTER);
    jPanel10.add(jPanel16, BorderLayout.NORTH);
    jPanel16.add(jRadioButton4, BorderLayout.NORTH);
    jPanel16.add(jRadioButton5, BorderLayout.CENTER);
    jPanel16.add(jToggleButton1, BorderLayout.SOUTH);
    jPanel10.add(jPanel17, BorderLayout.SOUTH);
    jPanel17.add(jButton3, BorderLayout.NORTH);
    jPanel10.add(jPanel19, BorderLayout.CENTER);
    jPanel19.add(jPanel20, BorderLayout.NORTH);
    jPanel20.add(jToggleButton2, null);
    jPanel20.add(jToggleButton4, null);
    jPanel20.add(jToggleButton10, null);
    jPanel20.add(jToggleButton5, null);
    jPanel20.add(jToggleButton12, null);
    jPanel20.add(jToggleButton7, null);
    jPanel20.add(jToggleButton11, null);
    jPanel20.add(jToggleButton13, null);
    jPanel20.add(jToggleButton35, null);
    jPanel20.add(jToggleButton16, null);
    jPanel20.add(jToggleButton14, null);
    jPanel20.add(jToggleButton25, null);
    jPanel20.add(jToggleButton21, null);
    jPanel20.add(jToggleButton17, null);
    jPanel20.add(jToggleButton19, null);
    jPanel20.add(jToggleButton40, null);
    jPanel20.add(jToggleButton18, null);
    jPanel20.add(jToggleButton20, null);
    jPanel20.add(jToggleButton30, null);
    jPanel20.add(jToggleButton26, null);
    jPanel20.add(jToggleButton41, null);
    jPanel20.add(jToggleButton27, null);
    jPanel20.add(jToggleButton28, null);
    jPanel20.add(jToggleButton36, null);
    jPanel20.add(jToggleButton31, null);
    jPanel20.add(jToggleButton32, null);
    jPanel20.add(jToggleButton33, null);
    jPanel20.add(jToggleButton37, null);
    jPanel20.add(jToggleButton34, null);
    jPanel20.add(jToggleButton42, null);
    jPanel20.add(jToggleButton43, null);
    jPanel20.add(jToggleButton44, null);
    jPanel20.add(jToggleButton39, null);
    jPanel20.add(jToggleButton38, null);
    jPanel20.add(jToggleButton24, null);
    jPanel20.add(jToggleButton29, null);
    jPanel20.add(jToggleButton22, null);
    jPanel20.add(jToggleButton15, null);
    jPanel20.add(jToggleButton3, null);
    jPanel20.add(jToggleButton23, null);
    jPanel19.add(jPanel21, BorderLayout.SOUTH);
    jPanel21.add(jToggleButton45, null);
    jPanel21.add(jToggleButton57, null);
    jPanel21.add(jToggleButton53, null);
    jPanel21.add(jToggleButton59, null);
    jPanel21.add(jToggleButton51, null);
    jPanel21.add(jToggleButton55, null);
    jPanel21.add(jToggleButton58, null);
    jPanel21.add(jToggleButton60, null);
    jPanel21.add(jToggleButton49, null);
    jPanel21.add(jToggleButton54, null);
    jPanel21.add(jToggleButton56, null);
    jPanel21.add(jToggleButton52, null);
    jPanel21.add(jToggleButton50, null);
    jPanel21.add(jToggleButton48, null);
    jPanel21.add(jToggleButton47, null);
    jPanel21.add(jToggleButton46, null);
    jPanel19.add(jPanel22, BorderLayout.CENTER);
    jPanel22.add(jLabel1, null);
    jTabbedPane1.add(jPanel4, "   글꼴   ");
    jPanel4.add(jPanel25, BorderLayout.NORTH);
    jPanel25.add(jPanel28, BorderLayout.NORTH);
    jPanel28.add(jPanel30, BorderLayout.WEST);
    jPanel30.add(jToggleButton61, BorderLayout.NORTH);
    jPanel30.add(jPanel33, BorderLayout.SOUTH);
    jPanel33.add(jScrollPane1, BorderLayout.CENTER);
    jScrollPane1.getViewport().add(jPanel35, null);
    jPanel35.add(jPanel70, null);
    jPanel70.add(jToggleButton67, BorderLayout.WEST);
    jPanel70.add(jLabel20, BorderLayout.CENTER);
    jPanel35.add(jPanel73, null);
    jPanel73.add(jToggleButton610, BorderLayout.WEST);
    jPanel73.add(jLabel23, BorderLayout.CENTER);
    jPanel35.add(jPanel72, null);
    jPanel72.add(jToggleButton69, BorderLayout.WEST);
    jPanel72.add(jLabel22, BorderLayout.CENTER);
    jPanel35.add(jPanel71, null);
    jPanel71.add(jToggleButton68, BorderLayout.WEST);
    jPanel71.add(jLabel21, BorderLayout.CENTER);
    jPanel30.add(jPanel34, BorderLayout.CENTER);
    jPanel34.add(jTextField1, BorderLayout.CENTER);
    jPanel28.add(jPanel31, BorderLayout.EAST);
    jPanel31.add(jPanel310, BorderLayout.CENTER);
    jPanel310.add(jTextField3, BorderLayout.CENTER);
    jPanel31.add(jPanel311, BorderLayout.SOUTH);
    jPanel311.add(jScrollPane3, BorderLayout.CENTER);
    jScrollPane3.getViewport().add(jPanel56, null);
    jPanel56.add(jPanel61, null);
    jPanel61.add(jLabel8, null);
    jPanel56.add(jPanel617, null);
    jPanel617.add(jLabel9, null);
    jPanel56.add(jPanel616, null);
    jPanel616.add(jLabel10, null);
    jPanel56.add(jPanel615, null);
    jPanel615.add(jLabel11, null);
    jPanel56.add(jPanel614, null);
    jPanel614.add(jLabel12, null);
    jPanel56.add(jPanel613, null);
    jPanel613.add(jLabel13, null);
    jPanel56.add(jPanel612, null);
    jPanel612.add(jLabel14, null);
    jPanel56.add(jPanel611, null);
    jPanel611.add(jLabel15, null);
    jPanel56.add(jPanel610, null);
    jPanel610.add(jLabel16, null);
    jPanel56.add(jPanel69, null);
    jPanel69.add(jLabel17, null);
    jPanel56.add(jPanel68, null);
    jPanel68.add(jLabel18, null);
    jPanel56.add(jPanel67, null);
    jPanel67.add(jLabel19, null);
    jPanel56.add(jPanel66, null);
    jPanel66.add(jLabel110, null);
    jPanel56.add(jPanel65, null);
    jPanel65.add(jLabel111, null);
    jPanel56.add(jPanel64, null);
    jPanel64.add(jLabel112, null);
    jPanel56.add(jPanel63, null);
    jPanel63.add(jLabel113, null);
    jPanel56.add(jPanel62, null);
    jPanel62.add(jLabel114, null);
    jPanel31.add(jToggleButton63, BorderLayout.NORTH);
    jPanel28.add(jPanel32, BorderLayout.CENTER);
    jPanel32.add(jPanel37, BorderLayout.CENTER);
    jPanel37.add(jTextField2, BorderLayout.CENTER);
    jPanel32.add(jPanel38, BorderLayout.SOUTH);
    jPanel38.add(jScrollPane2, BorderLayout.CENTER);
    jPanel32.add(jToggleButton62, BorderLayout.NORTH);
    jScrollPane2.getViewport().add(jPanel36, null);
    jPanel36.add(jPanel57, null);
    jPanel57.add(jLabel4, null);
    jPanel36.add(jPanel58, null);
    jPanel58.add(jLabel5, null);
    jPanel36.add(jPanel59, null);
    jPanel59.add(jLabel6, null);
    jPanel36.add(jPanel60, null);
    jPanel60.add(jLabel7, null);
    jPanel25.add(jPanel29, BorderLayout.CENTER);
    jPanel29.add(jPanel40, BorderLayout.WEST);
    jPanel40.add(jPanel43, BorderLayout.NORTH);
    jPanel43.add(jToggleButton64, BorderLayout.CENTER);
    jPanel40.add(jPanel44, BorderLayout.CENTER);
    jPanel44.add(jComboBox1, BorderLayout.CENTER);
    jPanel29.add(jPanel41, BorderLayout.EAST);
    jPanel41.add(jPanel45, BorderLayout.WEST);
    jPanel45.add(jComboBox2, BorderLayout.CENTER);
    jPanel41.add(jPanel46, BorderLayout.NORTH);
    jPanel46.add(jToggleButton65, BorderLayout.CENTER);
    jPanel29.add(jPanel42, BorderLayout.CENTER);
    jPanel42.add(jPanel47, BorderLayout.WEST);
    jPanel47.add(jComboBox3, BorderLayout.CENTER);
    jPanel42.add(jPanel48, BorderLayout.NORTH);
    jPanel48.add(jToggleButton66, BorderLayout.NORTH);
    jPanel4.add(jPanel26, BorderLayout.SOUTH);
    jPanel26.add(jLabel2, BorderLayout.CENTER);
    jPanel26.add(jCheckBox6, BorderLayout.NORTH);
    jPanel4.add(jPanel27, BorderLayout.CENTER);
    jPanel27.add(jPanel49, BorderLayout.WEST);
    jPanel49.add(jCheckBox3, BorderLayout.NORTH);
    jPanel49.add(jCheckBox4, BorderLayout.CENTER);
    jPanel49.add(jCheckBox5, BorderLayout.SOUTH);
    jPanel27.add(jPanel50, BorderLayout.CENTER);
    jPanel50.add(jToggleButton70, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel5, "   속성   ");
    jPanel5.add(jPanel51, BorderLayout.NORTH);
    jPanel51.add(jPanel53, BorderLayout.WEST);
    jPanel53.add(jRadioButton8, BorderLayout.SOUTH);
    jPanel53.add(jRadioButton6, BorderLayout.CENTER);
    jPanel53.add(jRadioButton9, BorderLayout.NORTH);
    jPanel5.add(jPanel52, BorderLayout.CENTER);
    jPanel52.add(jPanel54, BorderLayout.NORTH);
    jPanel54.add(jCheckBox7, BorderLayout.WEST);
    jPanel54.add(jCheckBox8, BorderLayout.SOUTH);
    jPanel52.add(jPanel55, BorderLayout.CENTER);
    jPanel55.add(jTextArea1, BorderLayout.NORTH);
    contentPane.add(jPanel2, BorderLayout.SOUTH);
    jPanel2.add(jPanel15, BorderLayout.EAST);
    jPanel15.add(jPanel23, BorderLayout.WEST);
    jPanel23.add(jButton1, BorderLayout.CENTER);
    jPanel15.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jButton2, BorderLayout.CENTER);
    jScrollPane2.getViewport();
    jScrollPane3.getViewport();
  }



}