
/**
 * Title:        chartwizard<p>
 * Description:  JAVA CHART v1.0<p>
 * Copyright:    Copyright (c) juney<p>
 * Company:      JCosmos<p>
 * @author juney
 * @version 1.0
 */
package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class DataElementStyleEditor extends Editor {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel15 = new JPanel();
  BorderLayout borderLayout20 = new BorderLayout();
  JButton jButton2 = new JButton();
  JButton jButton1 = new JButton();
  BorderLayout borderLayout18 = new BorderLayout();
  BorderLayout borderLayout17 = new BorderLayout();
  JPanel jPanel2 = new JPanel();
  JPanel jPanel24 = new JPanel();
  JPanel jPanel23 = new JPanel();
  BorderLayout borderLayout3 = new BorderLayout();
  JPanel jPanel19 = new JPanel();
  JPanel jPanel17 = new JPanel();
  JPanel jPanel16 = new JPanel();
  GridLayout gridLayout16 = new GridLayout();
  JPanel jPanel14 = new JPanel();
  GridLayout gridLayout15 = new GridLayout();
  JPanel jPanel13 = new JPanel();
  GridLayout gridLayout14 = new GridLayout();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel10 = new JPanel();
  GridLayout gridLayout11 = new GridLayout();
  JCheckBox jCheckBox5 = new JCheckBox();
  JCheckBox jCheckBox4 = new JCheckBox();
  JCheckBox jCheckBox3 = new JCheckBox();
  JCheckBox jCheckBox2 = new JCheckBox();
  JCheckBox jCheckBox1 = new JCheckBox();
  JRadioButton jRadioButton18 = new JRadioButton();
  JRadioButton jRadioButton17 = new JRadioButton();
  JRadioButton jRadioButton16 = new JRadioButton();
  JRadioButton jRadioButton15 = new JRadioButton();
  JRadioButton jRadioButton14 = new JRadioButton();
  JRadioButton jRadioButton13 = new JRadioButton();
  JPanel jPanel119 = new JPanel();
  JPanel jPanel118 = new JPanel();
  JPanel jPanel117 = new JPanel();
  JPanel jPanel116 = new JPanel();
  JPanel jPanel114 = new JPanel();
  JPanel jPanel111 = new JPanel();
  JComboBox jComboBox9 = new JComboBox();
  JComboBox jComboBox8 = new JComboBox();
  JComboBox jComboBox6 = new JComboBox();
  BorderLayout borderLayout9 = new BorderLayout();
  BorderLayout borderLayout8 = new BorderLayout();
  BorderLayout borderLayout7 = new BorderLayout();
  BorderLayout borderLayout6 = new BorderLayout();
  BorderLayout borderLayout5 = new BorderLayout();
  BorderLayout borderLayout4 = new BorderLayout();
  BorderLayout borderLayout2 = new BorderLayout();
  FlowLayout flowLayout1 = new FlowLayout();
  JLabel jLabel1 = new JLabel();
  JToggleButton jToggleButton70 = new JToggleButton();
  JButton jButton3 = new JButton();
  JPanel jPanel9 = new JPanel();
  JPanel jPanel8 = new JPanel();
  JPanel jPanel7 = new JPanel();
  JPanel jPanel6 = new JPanel();
  JPanel jPanel5 = new JPanel();
  JPanel jPanel4 = new JPanel();
  JPanel jPanel3 = new JPanel();
  JPanel jPanel1 = new JPanel();
  JRadioButton jRadioButton5 = new JRadioButton();
  JRadioButton jRadioButton4 = new JRadioButton();
  JRadioButton jRadioButton3 = new JRadioButton();
  JRadioButton jRadioButton2 = new JRadioButton();
  JToggleButton jToggleButton69 = new JToggleButton();
  JRadioButton jRadioButton1 = new JRadioButton();
  JToggleButton jToggleButton68 = new JToggleButton();
  JToggleButton jToggleButton60 = new JToggleButton();
  JPanel jPanel72 = new JPanel();
  JPanel jPanel71 = new JPanel();
  JPanel jPanel70 = new JPanel();
  JToggleButton jToggleButton59 = new JToggleButton();
  JToggleButton jToggleButton58 = new JToggleButton();
  JToggleButton jToggleButton57 = new JToggleButton();
  JToggleButton jToggleButton56 = new JToggleButton();
  JToggleButton jToggleButton55 = new JToggleButton();
  JToggleButton jToggleButton54 = new JToggleButton();
  JToggleButton jToggleButton53 = new JToggleButton();
  BorderLayout borderLayout57 = new BorderLayout();
  JToggleButton jToggleButton52 = new JToggleButton();
  BorderLayout borderLayout56 = new BorderLayout();
  JToggleButton jToggleButton51 = new JToggleButton();
  BorderLayout borderLayout55 = new BorderLayout();
  JToggleButton jToggleButton50 = new JToggleButton();
  BorderLayout borderLayout54 = new BorderLayout();
  BorderLayout borderLayout53 = new BorderLayout();
  BorderLayout borderLayout52 = new BorderLayout();
  JPanel jPanel69 = new JPanel();
  JPanel jPanel68 = new JPanel();
  JPanel jPanel67 = new JPanel();
  JPanel jPanel66 = new JPanel();
  JPanel jPanel65 = new JPanel();
  JPanel jPanel64 = new JPanel();
  JToggleButton jToggleButton9 = new JToggleButton();
  JToggleButton jToggleButton8 = new JToggleButton();
  JToggleButton jToggleButton7 = new JToggleButton();
  JToggleButton jToggleButton6 = new JToggleButton();
  JToggleButton jToggleButton49 = new JToggleButton();
  JToggleButton jToggleButton5 = new JToggleButton();
  JToggleButton jToggleButton48 = new JToggleButton();
  JToggleButton jToggleButton4 = new JToggleButton();
  JToggleButton jToggleButton47 = new JToggleButton();
  JToggleButton jToggleButton3 = new JToggleButton();
  JToggleButton jToggleButton46 = new JToggleButton();
  JToggleButton jToggleButton2 = new JToggleButton();
  JToggleButton jToggleButton45 = new JToggleButton();
  JToggleButton jToggleButton1 = new JToggleButton();
  JToggleButton jToggleButton44 = new JToggleButton();
  JToggleButton jToggleButton43 = new JToggleButton();
  JToggleButton jToggleButton42 = new JToggleButton();
  BorderLayout borderLayout46 = new BorderLayout();
  JToggleButton jToggleButton41 = new JToggleButton();
  JToggleButton jToggleButton40 = new JToggleButton();
  BorderLayout borderLayout44 = new BorderLayout();
  BorderLayout borderLayout43 = new BorderLayout();
  BorderLayout borderLayout42 = new BorderLayout();
  JPanel jPanel56 = new JPanel();
  JPanel jPanel55 = new JPanel();
  JPanel jPanel54 = new JPanel();
  JToggleButton jToggleButton39 = new JToggleButton();
  JToggleButton jToggleButton38 = new JToggleButton();
  JToggleButton jToggleButton37 = new JToggleButton();
  JToggleButton jToggleButton36 = new JToggleButton();
  JToggleButton jToggleButton35 = new JToggleButton();
  JToggleButton jToggleButton34 = new JToggleButton();
  JToggleButton jToggleButton33 = new JToggleButton();
  JToggleButton jToggleButton32 = new JToggleButton();
  JToggleButton jToggleButton31 = new JToggleButton();
  JToggleButton jToggleButton30 = new JToggleButton();
  BorderLayout borderLayout117 = new BorderLayout();
  BorderLayout borderLayout116 = new BorderLayout();
  BorderLayout borderLayout115 = new BorderLayout();
  BorderLayout borderLayout114 = new BorderLayout();
  BorderLayout borderLayout112 = new BorderLayout();
  JToggleButton jToggleButton29 = new JToggleButton();
  JToggleButton jToggleButton28 = new JToggleButton();
  JToggleButton jToggleButton27 = new JToggleButton();
  JToggleButton jToggleButton26 = new JToggleButton();
  JToggleButton jToggleButton25 = new JToggleButton();
  JToggleButton jToggleButton24 = new JToggleButton();
  JToggleButton jToggleButton23 = new JToggleButton();
  JToggleButton jToggleButton22 = new JToggleButton();
  JToggleButton jToggleButton21 = new JToggleButton();
  JToggleButton jToggleButton20 = new JToggleButton();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JToggleButton jToggleButton19 = new JToggleButton();
  JToggleButton jToggleButton18 = new JToggleButton();
  JToggleButton jToggleButton17 = new JToggleButton();
  JToggleButton jToggleButton16 = new JToggleButton();
  JToggleButton jToggleButton15 = new JToggleButton();
  BorderLayout borderLayout19 = new BorderLayout();
  JToggleButton jToggleButton14 = new JToggleButton();
  JToggleButton jToggleButton13 = new JToggleButton();
  JToggleButton jToggleButton12 = new JToggleButton();
  BorderLayout borderLayout16 = new BorderLayout();
  JToggleButton jToggleButton11 = new JToggleButton();
  BorderLayout borderLayout15 = new BorderLayout();
  JToggleButton jToggleButton10 = new JToggleButton();
  BorderLayout borderLayout14 = new BorderLayout();
  BorderLayout borderLayout13 = new BorderLayout();
  BorderLayout borderLayout12 = new BorderLayout();
  BorderLayout borderLayout11 = new BorderLayout();
  BorderLayout borderLayout10 = new BorderLayout();
  JPanel jPanel27 = new JPanel();
  JPanel jPanel25 = new JPanel();
  JPanel jPanel22 = new JPanel();
  JScrollPane jScrollPane6 = new JScrollPane();
  JPanel jPanel21 = new JPanel();
  GridLayout gridLayout3 = new GridLayout();
  JScrollPane jScrollPane5 = new JScrollPane();
  JPanel jPanel20 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  GridLayout gridLayout1 = new GridLayout();
  Border border1;
  Border border2;
  TitledBorder titledBorder1;
  Border border3;
  TitledBorder titledBorder2;
  Border border4;
  TitledBorder titledBorder3;
  Border border5;
  TitledBorder titledBorder4;
  Border border6;
  Border border7;
  Border border8;
  Border border9;
  Border border10;
  Border border11;
  Border border12;
  Border border13;
  Border border14;
  Border border15;
  Border border16;
  TitledBorder titledBorder5;
  Border border17;
  Border border18;
  Border border19;
  Border border20;
  Border border21;
  Border border22;
  Border border23;
  Border border24;
  Border border25;
  Border border26;
  Border border27;

  //Construct the frame
  public DataElementStyleEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    border1 = BorderFactory.createEmptyBorder(5,5,5,5);
    border2 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder1 = new TitledBorder(border2,"테두리");
    border3 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder2 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"테두리");
    border4 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder3 = new TitledBorder(border4,"보기");
    border5 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder4 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"영역");
    border6 = BorderFactory.createEmptyBorder(0,0,0,100);
    border7 = BorderFactory.createEmptyBorder(13,3,3,0);
    border8 = BorderFactory.createCompoundBorder(titledBorder2,BorderFactory.createEmptyBorder(0,5,0,0));
    border9 = BorderFactory.createCompoundBorder(titledBorder4,BorderFactory.createEmptyBorder(0,5,0,0));
    border10 = BorderFactory.createEmptyBorder(5,0,0,0);
    border11 = BorderFactory.createEmptyBorder(0,8,0,2);
    border12 = BorderFactory.createEmptyBorder(0,3,0,3);
    border13 = BorderFactory.createEmptyBorder(3,0,3,0);
    border14 = BorderFactory.createEmptyBorder(2,0,4,0);
    border15 = BorderFactory.createEmptyBorder(2,0,4,0);
    border16 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder5 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"데이터 레이블");
    border17 = BorderFactory.createEmptyBorder(13,5,0,220);
    border18 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"데이터 레이블"),BorderFactory.createEmptyBorder(0,7,0,0));
    border19 = BorderFactory.createEmptyBorder(20,3,0,0);
    border20 = BorderFactory.createEmptyBorder(10,5,15,8);
    border21 = BorderFactory.createEmptyBorder(0,0,20,0);
    border22 = BorderFactory.createEmptyBorder(0,0,17,0);
    border23 = BorderFactory.createEmptyBorder(5,0,24,0);
    border24 = BorderFactory.createEmptyBorder(1,0,0,0);
    border25 = BorderFactory.createEmptyBorder(3,0,12,0);
    border26 = BorderFactory.createEmptyBorder(2,0,3,0);
    border27 = BorderFactory.createEmptyBorder(0,0,5,0);
    jPanel15.setPreferredSize(new Dimension(148, 0));
    jPanel15.setLayout(borderLayout17);
    contentPane = (JPanel) this.getContentPane();
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(461, 392));
    this.setTitle("데이터 요소 서식");
    jButton2.setText("취소");
    jButton1.setMinimumSize(new Dimension(10, 10));
    jButton1.setPreferredSize(new Dimension(55, 29));
    jButton1.setText("확인");
    borderLayout17.setHgap(5);
    jPanel2.setLayout(borderLayout3);
    jPanel2.setBorder(border24);
    jPanel2.setPreferredSize(new Dimension(0, 22));
    jPanel24.setLayout(borderLayout20);
    jPanel23.setMinimumSize(new Dimension(50, 10));
    jPanel23.setPreferredSize(new Dimension(75, 0));
    jPanel23.setLayout(borderLayout18);
    jPanel19.setLayout(borderLayout15);
    jPanel17.setBorder(border10);
    jPanel17.setPreferredSize(new Dimension(0, 60));
    jPanel17.setLayout(borderLayout13);
    jPanel16.setPreferredSize(new Dimension(0, 60));
    jPanel16.setLayout(borderLayout14);
    jPanel14.setLayout(gridLayout1);
    jPanel14.setBorder(border11);
    jPanel14.setPreferredSize(new Dimension(11, 80));
    jPanel13.setPreferredSize(new Dimension(0, 55));
    jPanel13.setLayout(borderLayout10);
    gridLayout14.setColumns(1);
    gridLayout14.setRows(2);
    gridLayout14.setVgap(2);
    jPanel11.setPreferredSize(new Dimension(0, 57));
    jPanel11.setLayout(borderLayout9);
    jPanel10.setLayout(borderLayout12);
    jPanel10.setBorder(border9);
    jPanel10.setMinimumSize(new Dimension(182, 200));
    jPanel10.setPreferredSize(new Dimension(187, 250));
    gridLayout11.setColumns(1);
    gridLayout11.setRows(6);
    jCheckBox5.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox5.setMnemonic('V');
    jCheckBox5.setText("요소마다 다른 색 사용(V)");
    jCheckBox5.setRequestFocusEnabled(false);
    jCheckBox4.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox4.setMnemonic('S');
    jCheckBox4.setText("계열선(S)");
    jCheckBox4.setRequestFocusEnabled(false);
    jCheckBox3.setText("레이블 옆에 범례 표시(K)");
    jCheckBox2.setPreferredSize(new Dimension(115, 29));
    jCheckBox2.setMnemonic('V');
    jCheckBox2.setText("음수이면 반전(V)");
    jCheckBox2.setVerticalAlignment(SwingConstants.TOP);
    jCheckBox1.setMnemonic('D');
    jCheckBox1.setText("그림자(D)");
    jRadioButton18.setText("거품 크기 표시(B) ");
    jRadioButton17.setText("레이블과 백분율 표시(A)");
    jRadioButton16.setMnemonic('L');
    jRadioButton16.setText("레이블 표시(L)");
    jRadioButton15.setMnemonic('P');
    jRadioButton15.setText("백분율 표시(P)");
    jRadioButton14.setMnemonic('V');
    jRadioButton14.setText("값 표시(V)");
    jRadioButton13.setMnemonic('N');
    jRadioButton13.setText("없음(N)");
    jPanel119.setPreferredSize(new Dimension(0, 29));
    jPanel119.setLayout(borderLayout117);
    jPanel118.setLayout(borderLayout116);
    jPanel117.setPreferredSize(new Dimension(0, 29));
    jPanel117.setLayout(borderLayout115);
    jPanel116.setLayout(borderLayout114);
    jPanel114.setLayout(borderLayout112);
    jPanel111.setPreferredSize(new Dimension(0, 29));
    jPanel111.setLayout(borderLayout19);
    borderLayout5.setVgap(2);
    borderLayout4.setHgap(5);
    flowLayout1.setVgap(2);
    jLabel1.setBorder(BorderFactory.createEtchedBorder());
    jLabel1.setPreferredSize(new Dimension(142, 2));
    jLabel1.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel1.setVerticalAlignment(SwingConstants.TOP);
    jToggleButton70.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton70.setBorder(null);
    jToggleButton70.setMnemonic('W');
    jToggleButton70.setText("간격 너비(W):");
    jToggleButton70.setRequestFocusEnabled(false);
    jButton3.setText("채우기 효과(I)...");
    jPanel9.setBorder(titledBorder3);
    jPanel9.setPreferredSize(new Dimension(12, 51));
    jPanel9.setLayout(borderLayout7);
    jPanel8.setLayout(borderLayout6);
    jPanel7.setLayout(borderLayout8);
    jPanel6.setPreferredSize(new Dimension(178, 0));
    jPanel6.setLayout(borderLayout5);
    jPanel5.setLayout(borderLayout16);
    jPanel5.setBorder(border12);
    jPanel5.setPreferredSize(new Dimension(0, 19));
    jPanel4.setLayout(borderLayout11);
    jPanel4.setPreferredSize(new Dimension(0, 60));
    jPanel3.setLayout(borderLayout4);
    jPanel1.setLayout(borderLayout2);
    jPanel1.setPreferredSize(new Dimension(0, 328));
    jRadioButton5.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton5.setMnemonic('E');
    jRadioButton5.setText("없음(E)");
    jRadioButton5.setRequestFocusEnabled(false);
    jRadioButton4.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton4.setMnemonic('U');
    jRadioButton4.setText("자동(U)");
    jRadioButton4.setRequestFocusEnabled(false);
    jRadioButton3.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton3.setMnemonic('N');
    jRadioButton3.setText("없음(N)");
    jRadioButton3.setRequestFocusEnabled(false);
    jRadioButton2.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton2.setText("사용자 정의");
    jRadioButton2.setRequestFocusEnabled(false);
    jToggleButton69.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton69.setBorder(null);
    jToggleButton69.setMnemonic('O');
    jToggleButton69.setText("겹치기(O):   ");
    jToggleButton69.setRequestFocusEnabled(false);
    jRadioButton1.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton1.setMnemonic('A');
    jRadioButton1.setText("자동(A)");
    jRadioButton1.setRequestFocusEnabled(false);
    jToggleButton68.setIcon(new ImageIcon(jcosmos.Utility.getResource("data01.gif")));
    jToggleButton68.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton68.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton68.setRequestFocusEnabled(false);
    jToggleButton60.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-48.gif")));
    jToggleButton60.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton60.setRequestFocusEnabled(false);
    jPanel72.setBackground(Color.white);
    jPanel72.setLayout(gridLayout16);
    jPanel71.setLayout(gridLayout15);
    jPanel71.setBackground(Color.white);
    jPanel70.setLayout(borderLayout57);
    jToggleButton59.setRequestFocusEnabled(false);
    jToggleButton59.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton59.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-44.gif")));
    jToggleButton58.setRequestFocusEnabled(false);
    jToggleButton58.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton58.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-47.gif")));
    jToggleButton57.setRequestFocusEnabled(false);
    jToggleButton57.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton57.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-42.gif")));
    jToggleButton56.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-51.gif")));
    jToggleButton56.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton56.setRequestFocusEnabled(false);
    jToggleButton55.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-46.gif")));
    jToggleButton55.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton55.setRequestFocusEnabled(false);
    jToggleButton54.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-50.gif")));
    jToggleButton54.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton54.setRequestFocusEnabled(false);
    jToggleButton53.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-43.gif")));
    jToggleButton53.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton53.setRequestFocusEnabled(false);
    jToggleButton52.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-52.gif")));
    jToggleButton52.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton52.setRequestFocusEnabled(false);
    jToggleButton51.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-45.gif")));
    jToggleButton51.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton51.setRequestFocusEnabled(false);
    jToggleButton50.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-53.gif")));
    jToggleButton50.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton50.setRequestFocusEnabled(false);
    jPanel69.setLayout(borderLayout56);
    jPanel68.setLayout(gridLayout14);
    jPanel67.setLayout(borderLayout55);
    jPanel67.setBorder(border23);
    jPanel67.setPreferredSize(new Dimension(160, 0));
    jPanel66.setLayout(borderLayout54);
    jPanel66.setBorder(border25);
    jPanel66.setPreferredSize(new Dimension(170, 0));
    jPanel65.setLayout(borderLayout53);
    jPanel65.setBorder(border21);
    jPanel65.setPreferredSize(new Dimension(435, 205));
    jPanel64.setLayout(borderLayout52);
    jPanel64.setBorder(border22);
    jPanel64.setPreferredSize(new Dimension(0, 80));
    jToggleButton9.setRequestFocusEnabled(false);
    jToggleButton9.setText("스타일(S):   ");
    jToggleButton9.setMnemonic('S');
    jToggleButton9.setBorder(null);
    jToggleButton9.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton8.setRequestFocusEnabled(false);
    jToggleButton8.setText("색(C):           ");
    jToggleButton8.setMnemonic('C');
    jToggleButton8.setBorder(null);
    jToggleButton8.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton7.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-06.gif")));
    jToggleButton7.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton7.setRequestFocusEnabled(false);
    jToggleButton6.setRequestFocusEnabled(false);
    jToggleButton6.setText("두께(W):      ");
    jToggleButton6.setMnemonic('W');
    jToggleButton6.setBorder(null);
    jToggleButton6.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton49.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-49.gif")));
    jToggleButton49.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton49.setRequestFocusEnabled(false);
    jToggleButton5.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-04.gif")));
    jToggleButton5.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton48.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-54.gif")));
    jToggleButton48.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton48.setRequestFocusEnabled(false);
    jToggleButton4.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-02.gif")));
    jToggleButton4.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton4.setRequestFocusEnabled(false);
    jToggleButton47.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-55.gif")));
    jToggleButton47.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton47.setRequestFocusEnabled(false);
    jToggleButton3.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-39.gif")));
    jToggleButton3.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton3.setRequestFocusEnabled(false);
    jToggleButton46.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-56.gif")));
    jToggleButton46.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton46.setRequestFocusEnabled(false);
    jToggleButton2.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-01.gif")));
    jToggleButton2.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton2.setRequestFocusEnabled(false);
    jToggleButton45.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-41.gif")));
    jToggleButton45.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton45.setRequestFocusEnabled(false);
    jToggleButton1.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton1.setPreferredSize(new Dimension(65, 25));
    jToggleButton1.setBorder(null);
    jToggleButton1.setMnemonic('O');
    jToggleButton1.setText("색(O):");
    jToggleButton1.setRequestFocusEnabled(false);
    jToggleButton1.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton44.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-32.gif")));
    jToggleButton44.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton44.setRequestFocusEnabled(false);
    jToggleButton43.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-31.gif")));
    jToggleButton43.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton43.setRequestFocusEnabled(false);
    jToggleButton42.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-30.gif")));
    jToggleButton42.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton42.setRequestFocusEnabled(false);
    jToggleButton41.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-21.gif")));
    jToggleButton41.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton41.setRequestFocusEnabled(false);
    jToggleButton40.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-16.gif")));
    jToggleButton40.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton40.setRequestFocusEnabled(false);
    jPanel56.setLayout(gridLayout11);
    jPanel55.setLayout(borderLayout43);
    jPanel55.setBorder(border19);
    jPanel55.setPreferredSize(new Dimension(0, 150));
    jPanel54.setLayout(borderLayout44);
    jPanel54.setBorder(border18);
    jPanel54.setPreferredSize(new Dimension(171, 180));
    jToggleButton39.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-33.gif")));
    jToggleButton39.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton39.setRequestFocusEnabled(false);
    jToggleButton38.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-34.gif")));
    jToggleButton38.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton38.setRequestFocusEnabled(false);
    jToggleButton37.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-28.gif")));
    jToggleButton37.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton37.setRequestFocusEnabled(false);
    jToggleButton36.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-24.gif")));
    jToggleButton36.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton36.setRequestFocusEnabled(false);
    jToggleButton35.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-09.gif")));
    jToggleButton35.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton35.setRequestFocusEnabled(false);
    jToggleButton34.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-29.gif")));
    jToggleButton34.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton34.setRequestFocusEnabled(false);
    jToggleButton33.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-27.gif")));
    jToggleButton33.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton33.setRequestFocusEnabled(false);
    jToggleButton32.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-26.gif")));
    jToggleButton32.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton32.setRequestFocusEnabled(false);
    jToggleButton31.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-25.gif")));
    jToggleButton31.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton31.setRequestFocusEnabled(false);
    jToggleButton30.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-19.gif")));
    jToggleButton30.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton30.setRequestFocusEnabled(false);
    jToggleButton29.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-36.gif")));
    jToggleButton29.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton29.setRequestFocusEnabled(false);
    jToggleButton28.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-23.gif")));
    jToggleButton28.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton28.setRequestFocusEnabled(false);
    jToggleButton27.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-22.gif")));
    jToggleButton27.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton27.setRequestFocusEnabled(false);
    jToggleButton26.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-20.gif")));
    jToggleButton26.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton26.setRequestFocusEnabled(false);
    jToggleButton25.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-12.gif")));
    jToggleButton25.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton25.setRequestFocusEnabled(false);
    jToggleButton24.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-35.gif")));
    jToggleButton24.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton24.setRequestFocusEnabled(false);
    jToggleButton23.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-40.gif")));
    jToggleButton23.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton23.setRequestFocusEnabled(false);
    jToggleButton22.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-37.gif")));
    jToggleButton22.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton22.setRequestFocusEnabled(false);
    jToggleButton21.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-13.gif")));
    jToggleButton21.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton21.setRequestFocusEnabled(false);
    jToggleButton20.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-18.gif")));
    jToggleButton20.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton20.setRequestFocusEnabled(false);
    jTabbedPane1.setPreferredSize(new Dimension(241, 74));
    jTabbedPane1.setRequestFocusEnabled(false);
    jToggleButton19.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-15.gif")));
    jToggleButton19.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton19.setRequestFocusEnabled(false);
    jToggleButton18.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-17.gif")));
    jToggleButton18.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton18.setRequestFocusEnabled(false);
    jToggleButton17.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-14.gif")));
    jToggleButton17.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton17.setRequestFocusEnabled(false);
    jToggleButton16.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-10.gif")));
    jToggleButton16.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton16.setRequestFocusEnabled(false);
    jToggleButton15.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-38.gif")));
    jToggleButton15.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton15.setRequestFocusEnabled(false);
    jToggleButton14.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-11.gif")));
    jToggleButton14.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton14.setRequestFocusEnabled(false);
    jToggleButton13.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-08.gif")));
    jToggleButton13.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton13.setRequestFocusEnabled(false);
    jToggleButton12.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-05.gif")));
    jToggleButton12.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton12.setRequestFocusEnabled(false);
    jToggleButton11.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-07.gif")));
    jToggleButton11.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton11.setRequestFocusEnabled(false);
    jToggleButton10.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-03.gif")));
    jToggleButton10.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton10.setRequestFocusEnabled(false);
    jPanel27.setLayout(borderLayout46);
    jPanel25.setLayout(borderLayout42);
    jPanel22.setPreferredSize(new Dimension(140, 2));
    jPanel22.setLayout(flowLayout1);
    jScrollPane6.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane6.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane6.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane6.setMinimumSize(new Dimension(24, 2));
    jScrollPane6.setPreferredSize(new Dimension(60, 4));
    jPanel21.setPreferredSize(new Dimension(0, 36));
    jPanel21.setLayout(gridLayout3);
    gridLayout3.setVgap(3);
    gridLayout3.setRows(2);
    gridLayout3.setHgap(3);
    gridLayout3.setColumns(8);
    jScrollPane5.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane5.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane5.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane5.setPreferredSize(new Dimension(60, 4));
    jPanel20.setPreferredSize(new Dimension(0, 90));
    jPanel20.setLayout(gridLayout2);
    gridLayout2.setVgap(3);
    gridLayout2.setRows(5);
    gridLayout2.setHgap(3);
    gridLayout2.setColumns(8);
    gridLayout1.setVgap(1);
    gridLayout1.setRows(3);
    gridLayout1.setColumns(1);
    contentPane.setBorder(border1);
    jPanel8.setBorder(border8);
    jPanel7.setBorder(border6);
    jPanel3.setBorder(border7);
    jPanel118.setBorder(border13);
    jPanel116.setBorder(border14);
    jPanel114.setBorder(border15);
    jPanel19.setPreferredSize(new Dimension(140, 127));
    jPanel25.setBorder(border17);
    jPanel27.setBorder(border20);
    jPanel69.setBorder(border26);
    jPanel70.setBorder(border27);
    contentPane.add(jPanel2, BorderLayout.SOUTH);
    jPanel2.add(jPanel15, BorderLayout.EAST);
    jPanel15.add(jPanel23, BorderLayout.WEST);
    jPanel23.add(jButton1, BorderLayout.CENTER);
    jPanel15.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jButton2, BorderLayout.CENTER);
    contentPane.add(jPanel1, BorderLayout.NORTH);
    jPanel1.add(jTabbedPane1, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel3, "   무늬   ");
    jPanel3.add(jPanel6, BorderLayout.WEST);
    jPanel6.add(jPanel8, BorderLayout.CENTER);
    jPanel8.add(jPanel13, BorderLayout.NORTH);
    jPanel13.add(jPanel11, BorderLayout.NORTH);
    jPanel11.add(jRadioButton1, BorderLayout.NORTH);
    jPanel11.add(jRadioButton2, BorderLayout.SOUTH);
    jPanel11.add(jRadioButton3, BorderLayout.CENTER);
    jPanel8.add(jPanel14, BorderLayout.CENTER);
    jPanel14.add(jPanel119, null);
    jPanel119.add(jToggleButton9, BorderLayout.WEST);
    jPanel119.add(jPanel118, BorderLayout.CENTER);
    jPanel118.add(jComboBox9, BorderLayout.CENTER);
    jPanel14.add(jPanel117, null);
    jPanel117.add(jToggleButton8, BorderLayout.WEST);
    jPanel117.add(jPanel116, BorderLayout.CENTER);
    jPanel116.add(jComboBox8, BorderLayout.CENTER);
    jPanel14.add(jPanel111, null);
    jPanel111.add(jToggleButton6, BorderLayout.WEST);
    jPanel111.add(jPanel114, BorderLayout.CENTER);
    jPanel114.add(jComboBox6, BorderLayout.CENTER);
    jPanel8.add(jPanel4, BorderLayout.SOUTH);
    jPanel4.add(jCheckBox1, BorderLayout.CENTER);
    jPanel6.add(jPanel9, BorderLayout.SOUTH);
    jPanel3.add(jPanel7, BorderLayout.CENTER);
    jPanel7.add(jPanel10, BorderLayout.CENTER);
    jPanel10.add(jPanel16, BorderLayout.NORTH);
    jPanel16.add(jRadioButton4, BorderLayout.NORTH);
    jPanel16.add(jRadioButton5, BorderLayout.CENTER);
    jPanel16.add(jToggleButton1, BorderLayout.SOUTH);
    jPanel10.add(jPanel17, BorderLayout.SOUTH);
    jPanel17.add(jCheckBox2, BorderLayout.SOUTH);
    jPanel17.add(jPanel5, BorderLayout.NORTH);
    jPanel5.add(jButton3, BorderLayout.CENTER);
    jPanel10.add(jPanel19, BorderLayout.CENTER);
    jPanel19.add(jPanel20, BorderLayout.NORTH);
    jPanel20.add(jToggleButton2, null);
    jPanel20.add(jToggleButton4, null);
    jPanel20.add(jToggleButton10, null);
    jPanel20.add(jToggleButton5, null);
    jPanel20.add(jToggleButton12, null);
    jPanel20.add(jToggleButton7, null);
    jPanel20.add(jToggleButton11, null);
    jPanel20.add(jToggleButton13, null);
    jPanel20.add(jToggleButton35, null);
    jPanel20.add(jToggleButton16, null);
    jPanel20.add(jToggleButton14, null);
    jPanel20.add(jToggleButton25, null);
    jPanel20.add(jToggleButton21, null);
    jPanel20.add(jToggleButton17, null);
    jPanel20.add(jToggleButton19, null);
    jPanel20.add(jToggleButton40, null);
    jPanel20.add(jToggleButton18, null);
    jPanel20.add(jToggleButton20, null);
    jPanel20.add(jToggleButton30, null);
    jPanel20.add(jToggleButton26, null);
    jPanel20.add(jToggleButton41, null);
    jPanel20.add(jToggleButton27, null);
    jPanel20.add(jToggleButton28, null);
    jPanel20.add(jToggleButton36, null);
    jPanel20.add(jToggleButton31, null);
    jPanel20.add(jToggleButton32, null);
    jPanel20.add(jToggleButton33, null);
    jPanel20.add(jToggleButton37, null);
    jPanel20.add(jToggleButton34, null);
    jPanel20.add(jToggleButton42, null);
    jPanel20.add(jToggleButton43, null);
    jPanel20.add(jToggleButton44, null);
    jPanel20.add(jToggleButton39, null);
    jPanel20.add(jToggleButton38, null);
    jPanel20.add(jToggleButton24, null);
    jPanel20.add(jToggleButton29, null);
    jPanel20.add(jToggleButton22, null);
    jPanel20.add(jToggleButton15, null);
    jPanel20.add(jToggleButton3, null);
    jPanel20.add(jToggleButton23, null);
    jPanel19.add(jPanel21, BorderLayout.SOUTH);
    jPanel21.add(jToggleButton45, null);
    jPanel21.add(jToggleButton57, null);
    jPanel21.add(jToggleButton53, null);
    jPanel21.add(jToggleButton59, null);
    jPanel21.add(jToggleButton51, null);
    jPanel21.add(jToggleButton55, null);
    jPanel21.add(jToggleButton58, null);
    jPanel21.add(jToggleButton60, null);
    jPanel21.add(jToggleButton49, null);
    jPanel21.add(jToggleButton54, null);
    jPanel21.add(jToggleButton56, null);
    jPanel21.add(jToggleButton52, null);
    jPanel21.add(jToggleButton50, null);
    jPanel21.add(jToggleButton48, null);
    jPanel21.add(jToggleButton47, null);
    jPanel21.add(jToggleButton46, null);
    jPanel19.add(jPanel22, BorderLayout.WEST);
    jPanel22.add(jLabel1, null);
    jTabbedPane1.add(jPanel25, "  데이터 레이블  ");
    jPanel25.add(jPanel54, BorderLayout.CENTER);
    jPanel54.add(jPanel56, BorderLayout.CENTER);
    jPanel56.add(jRadioButton13, null);
    jPanel56.add(jRadioButton14, null);
    jPanel56.add(jRadioButton15, null);
    jPanel56.add(jRadioButton16, null);
    jPanel56.add(jRadioButton17, null);
    jPanel56.add(jRadioButton18, null);
    jPanel25.add(jPanel55, BorderLayout.SOUTH);
    jPanel55.add(jCheckBox3, BorderLayout.NORTH);
    jTabbedPane1.add(jPanel27, "   옵션   ");
    jPanel27.add(jPanel64, BorderLayout.NORTH);
    jPanel64.add(jPanel66, BorderLayout.WEST);
    jPanel66.add(jPanel68, BorderLayout.CENTER);
    jPanel68.add(jPanel69, null);
    jPanel69.add(jToggleButton69, BorderLayout.WEST);
    jPanel69.add(jScrollPane5, BorderLayout.EAST);
    jPanel68.add(jPanel70, null);
    jPanel70.add(jToggleButton70, BorderLayout.WEST);
    jPanel70.add(jScrollPane6, BorderLayout.EAST);
    jPanel64.add(jPanel67, BorderLayout.EAST);
    jPanel67.add(jCheckBox4, BorderLayout.NORTH);
    jPanel67.add(jCheckBox5, BorderLayout.CENTER);
    jPanel27.add(jPanel65, BorderLayout.CENTER);
    jPanel65.add(jToggleButton68, BorderLayout.WEST);
    jScrollPane6.getViewport().add(jPanel72, null);
    jScrollPane5.getViewport().add(jPanel71, null);
  }


}