
/**
 * Title:        chartwizard<p>
 * Description:  JAVA CHART v1.0<p>
 * Copyright:    Copyright (c) juney<p>
 * Company:      JCosmos<p>
 * @author juney
 * @version 1.0
 */
package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class DataSeriesStyleEditor extends Editor {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  GridLayout gridLayout3 = new GridLayout();
  GridLayout gridLayout2 = new GridLayout();
  GridLayout gridLayout1 = new GridLayout();
  JToggleButton jToggleButton59 = new JToggleButton();
  JToggleButton jToggleButton58 = new JToggleButton();
  JToggleButton jToggleButton57 = new JToggleButton();
  JPanel jPanel19 = new JPanel();
  JToggleButton jToggleButton56 = new JToggleButton();
  JToggleButton jToggleButton55 = new JToggleButton();
  JPanel jPanel17 = new JPanel();
  JToggleButton jToggleButton54 = new JToggleButton();
  JPanel jPanel16 = new JPanel();
  JToggleButton jToggleButton53 = new JToggleButton();
  JPanel jPanel15 = new JPanel();
  JToggleButton jToggleButton52 = new JToggleButton();
  JPanel jPanel14 = new JPanel();
  JToggleButton jToggleButton51 = new JToggleButton();
  JPanel jPanel13 = new JPanel();
  JToggleButton jToggleButton50 = new JToggleButton();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel10 = new JPanel();
  JRadioButton jRadioButton5 = new JRadioButton();
  JRadioButton jRadioButton4 = new JRadioButton();
  JRadioButton jRadioButton3 = new JRadioButton();
  JRadioButton jRadioButton2 = new JRadioButton();
  JRadioButton jRadioButton1 = new JRadioButton();
  BorderLayout borderLayout117 = new BorderLayout();
  BorderLayout borderLayout116 = new BorderLayout();
  BorderLayout borderLayout115 = new BorderLayout();
  BorderLayout borderLayout114 = new BorderLayout();
  BorderLayout borderLayout112 = new BorderLayout();
  JToggleButton jToggleButton49 = new JToggleButton();
  JToggleButton jToggleButton48 = new JToggleButton();
  BorderLayout borderLayout9 = new BorderLayout();
  JToggleButton jToggleButton47 = new JToggleButton();
  BorderLayout borderLayout8 = new BorderLayout();
  JToggleButton jToggleButton46 = new JToggleButton();
  BorderLayout borderLayout7 = new BorderLayout();
  JToggleButton jToggleButton45 = new JToggleButton();
  BorderLayout borderLayout6 = new BorderLayout();
  JToggleButton jToggleButton44 = new JToggleButton();
  BorderLayout borderLayout5 = new BorderLayout();
  JToggleButton jToggleButton43 = new JToggleButton();
  BorderLayout borderLayout4 = new BorderLayout();
  JToggleButton jToggleButton42 = new JToggleButton();
  BorderLayout borderLayout3 = new BorderLayout();
  JToggleButton jToggleButton41 = new JToggleButton();
  BorderLayout borderLayout2 = new BorderLayout();
  JToggleButton jToggleButton40 = new JToggleButton();
  JPanel jPanel9 = new JPanel();
  FlowLayout flowLayout1 = new FlowLayout();
  JPanel jPanel8 = new JPanel();
  JPanel jPanel7 = new JPanel();
  JToggleButton jToggleButton39 = new JToggleButton();
  JPanel jPanel6 = new JPanel();
  JToggleButton jToggleButton38 = new JToggleButton();
  JToggleButton jToggleButton37 = new JToggleButton();
  JPanel jPanel4 = new JPanel();
  JToggleButton jToggleButton36 = new JToggleButton();
  JPanel jPanel3 = new JPanel();
  JToggleButton jToggleButton35 = new JToggleButton();
  JPanel jPanel2 = new JPanel();
  JToggleButton jToggleButton34 = new JToggleButton();
  JPanel jPanel1 = new JPanel();
  JToggleButton jToggleButton33 = new JToggleButton();
  JToggleButton jToggleButton32 = new JToggleButton();
  JToggleButton jToggleButton31 = new JToggleButton();
  JButton jButton2 = new JButton();
  JToggleButton jToggleButton30 = new JToggleButton();
  JButton jButton1 = new JButton();
  JToggleButton jToggleButton29 = new JToggleButton();
  JToggleButton jToggleButton28 = new JToggleButton();
  JToggleButton jToggleButton27 = new JToggleButton();
  JToggleButton jToggleButton26 = new JToggleButton();
  JToggleButton jToggleButton25 = new JToggleButton();
  JToggleButton jToggleButton24 = new JToggleButton();
  JToggleButton jToggleButton23 = new JToggleButton();
  JToggleButton jToggleButton22 = new JToggleButton();
  JToggleButton jToggleButton21 = new JToggleButton();
  JToggleButton jToggleButton20 = new JToggleButton();
  JPanel jPanel119 = new JPanel();
  JLabel jLabel1 = new JLabel();
  JPanel jPanel118 = new JPanel();
  JPanel jPanel117 = new JPanel();
  JPanel jPanel116 = new JPanel();
  JPanel jPanel114 = new JPanel();
  JToggleButton jToggleButton19 = new JToggleButton();
  JPanel jPanel111 = new JPanel();
  JToggleButton jToggleButton18 = new JToggleButton();
  JToggleButton jToggleButton17 = new JToggleButton();
  JToggleButton jToggleButton16 = new JToggleButton();
  JToggleButton jToggleButton15 = new JToggleButton();
  JToggleButton jToggleButton14 = new JToggleButton();
  JToggleButton jToggleButton13 = new JToggleButton();
  JToggleButton jToggleButton12 = new JToggleButton();
  JComboBox jComboBox9 = new JComboBox();
  JToggleButton jToggleButton11 = new JToggleButton();
  JComboBox jComboBox8 = new JComboBox();
  JToggleButton jToggleButton10 = new JToggleButton();
  JComboBox jComboBox6 = new JComboBox();
  BorderLayout borderLayout20 = new BorderLayout();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  BorderLayout borderLayout19 = new BorderLayout();
  BorderLayout borderLayout18 = new BorderLayout();
  JToggleButton jToggleButton9 = new JToggleButton();
  BorderLayout borderLayout17 = new BorderLayout();
  JToggleButton jToggleButton8 = new JToggleButton();
  JToggleButton jToggleButton7 = new JToggleButton();
  BorderLayout borderLayout15 = new BorderLayout();
  JToggleButton jToggleButton6 = new JToggleButton();
  BorderLayout borderLayout14 = new BorderLayout();
  JToggleButton jToggleButton5 = new JToggleButton();
  BorderLayout borderLayout13 = new BorderLayout();
  JToggleButton jToggleButton4 = new JToggleButton();
  JToggleButton jToggleButton3 = new JToggleButton();
  BorderLayout borderLayout12 = new BorderLayout();
  BorderLayout borderLayout11 = new BorderLayout();
  JToggleButton jToggleButton2 = new JToggleButton();
  BorderLayout borderLayout10 = new BorderLayout();
  JToggleButton jToggleButton1 = new JToggleButton();
  JPanel jPanel24 = new JPanel();
  JPanel jPanel23 = new JPanel();
  JPanel jPanel22 = new JPanel();
  JToggleButton jToggleButton60 = new JToggleButton();
  JPanel jPanel21 = new JPanel();
  JPanel jPanel20 = new JPanel();
  Border border1;
  TitledBorder titledBorder1;
  Border border2;
  Border border3;
  TitledBorder titledBorder2;
  Border border4;
  TitledBorder titledBorder3;
  Border border5;
  TitledBorder titledBorder4;
  JCheckBox jCheckBox1 = new JCheckBox();
  JCheckBox jCheckBox2 = new JCheckBox();
  Border border6;
  Border border7;
  Border border8;
  Border border9;
  Border border10;
  Border border11;
  Border border12;
  Border border13;
  Border border14;
  Border border15;
  Border border16;
  JPanel jPanel5 = new JPanel();
  BorderLayout borderLayout16 = new BorderLayout();
  Border border17;
  JButton jButton3 = new JButton();
  JPanel jPanel12 = new JPanel();
  JPanel jPanel18 = new JPanel();
  JPanel jPanel25 = new JPanel();
  JPanel jPanel26 = new JPanel();
  JPanel jPanel27 = new JPanel();
  BorderLayout borderLayout21 = new BorderLayout();
  JPanel jPanel28 = new JPanel();
  BorderLayout borderLayout22 = new BorderLayout();
  Border border18;
  JPanel jPanel29 = new JPanel();
  BorderLayout borderLayout23 = new BorderLayout();
  JPanel jPanel30 = new JPanel();
  BorderLayout borderLayout24 = new BorderLayout();
  Border border19;
  TitledBorder titledBorder5;
  JRadioButton jRadioButton6 = new JRadioButton();
  JRadioButton jRadioButton7 = new JRadioButton();
  Border border20;
  Border border21;
  JToggleButton jToggleButton61 = new JToggleButton();
  JPanel jPanel31 = new JPanel();
  BorderLayout borderLayout25 = new BorderLayout();
  BorderLayout borderLayout26 = new BorderLayout();
  JPanel jPanel32 = new JPanel();
  JPanel jPanel33 = new JPanel();
  BorderLayout borderLayout27 = new BorderLayout();
  Border border22;
  TitledBorder titledBorder6;
  Border border23;
  TitledBorder titledBorder7;
  Border border24;
  JPanel jPanel34 = new JPanel();
  GridLayout gridLayout4 = new GridLayout();
  JPanel jPanel35 = new JPanel();
  GridLayout gridLayout5 = new GridLayout();
  JToggleButton jToggleButton62 = new JToggleButton();
  JToggleButton jToggleButton63 = new JToggleButton();
  JToggleButton jToggleButton64 = new JToggleButton();
  JToggleButton jToggleButton65 = new JToggleButton();
  JLabel jLabel2 = new JLabel();
  JLabel jLabel3 = new JLabel();
  JLabel jLabel4 = new JLabel();
  JLabel jLabel5 = new JLabel();
  BorderLayout borderLayout28 = new BorderLayout();
  Border border25;
  JPanel jPanel36 = new JPanel();
  JPanel jPanel37 = new JPanel();
  BorderLayout borderLayout29 = new BorderLayout();
  BorderLayout borderLayout30 = new BorderLayout();
  JPanel jPanel38 = new JPanel();
  GridLayout gridLayout6 = new GridLayout();
  JPanel jPanel39 = new JPanel();
  JPanel jPanel40 = new JPanel();
  JPanel jPanel41 = new JPanel();
  JPanel jPanel42 = new JPanel();
  JPanel jPanel43 = new JPanel();
  GridLayout gridLayout7 = new GridLayout();
  JPanel jPanel44 = new JPanel();
  BorderLayout borderLayout31 = new BorderLayout();
  BorderLayout borderLayout32 = new BorderLayout();
  BorderLayout borderLayout33 = new BorderLayout();
  BorderLayout borderLayout34 = new BorderLayout();
  JPanel jPanel45 = new JPanel();
  BorderLayout borderLayout35 = new BorderLayout();
  BorderLayout borderLayout36 = new BorderLayout();
  JRadioButton jRadioButton8 = new JRadioButton();
  JRadioButton jRadioButton9 = new JRadioButton();
  JRadioButton jRadioButton10 = new JRadioButton();
  JRadioButton jRadioButton11 = new JRadioButton();
  JRadioButton jRadioButton12 = new JRadioButton();
  JPanel jPanel46 = new JPanel();
  BorderLayout borderLayout37 = new BorderLayout();
  JScrollPane jScrollPane1 = new JScrollPane();
  JPanel jPanel47 = new JPanel();
  GridLayout gridLayout8 = new GridLayout();
  JPanel jPanel48 = new JPanel();
  BorderLayout borderLayout38 = new BorderLayout();
  JScrollPane jScrollPane2 = new JScrollPane();
  JPanel jPanel49 = new JPanel();
  GridLayout gridLayout9 = new GridLayout();
  JLabel jLabel6 = new JLabel();
  JPanel jPanel50 = new JPanel();
  BorderLayout borderLayout39 = new BorderLayout();
  JScrollPane jScrollPane3 = new JScrollPane();
  JPanel jPanel51 = new JPanel();
  GridLayout gridLayout10 = new GridLayout();
  JPanel jPanel52 = new JPanel();
  BorderLayout borderLayout40 = new BorderLayout();
  JTextField jTextField1 = new JTextField();
  JLabel jLabel7 = new JLabel();
  JPanel jPanel53 = new JPanel();
  BorderLayout borderLayout41 = new BorderLayout();
  JTextField jTextField2 = new JTextField();
  JLabel jLabel8 = new JLabel();
  Border border26;
  Border border27;
  Border border28;
  Border border29;
  Border border30;
  Border border31;
  JButton jButton4 = new JButton();
  JButton jButton5 = new JButton();
  Border border32;
  Border border33;
  BorderLayout borderLayout42 = new BorderLayout();
  Border border34;
  JPanel jPanel54 = new JPanel();
  JPanel jPanel55 = new JPanel();
  BorderLayout borderLayout43 = new BorderLayout();
  BorderLayout borderLayout44 = new BorderLayout();
  Border border35;
  TitledBorder titledBorder8;
  JCheckBox jCheckBox3 = new JCheckBox();
  JPanel jPanel56 = new JPanel();
  GridLayout gridLayout11 = new GridLayout();
  JRadioButton jRadioButton13 = new JRadioButton();
  JRadioButton jRadioButton14 = new JRadioButton();
  JRadioButton jRadioButton15 = new JRadioButton();
  JRadioButton jRadioButton16 = new JRadioButton();
  JRadioButton jRadioButton17 = new JRadioButton();
  JRadioButton jRadioButton18 = new JRadioButton();
  Border border36;
  Border border37;
  Border border38;
  BorderLayout borderLayout45 = new BorderLayout();
  BorderLayout borderLayout46 = new BorderLayout();
  JPanel jPanel57 = new JPanel();
  JPanel jPanel58 = new JPanel();
  BorderLayout borderLayout47 = new BorderLayout();
  BorderLayout borderLayout48 = new BorderLayout();
  Border border39;
  JPanel jPanel59 = new JPanel();
  JPanel jPanel60 = new JPanel();
  BorderLayout borderLayout49 = new BorderLayout();
  BorderLayout borderLayout50 = new BorderLayout();
  JToggleButton jToggleButton66 = new JToggleButton();
  JScrollPane jScrollPane4 = new JScrollPane();
  JPanel jPanel61 = new JPanel();
  GridLayout gridLayout12 = new GridLayout();
  JPanel jPanel62 = new JPanel();
  GridLayout gridLayout13 = new GridLayout();
  JLabel jLabel9 = new JLabel();
  JLabel jLabel10 = new JLabel();
  JLabel jLabel11 = new JLabel();
  JPanel jPanel63 = new JPanel();
  BorderLayout borderLayout51 = new BorderLayout();
  JButton jButton6 = new JButton();
  JButton jButton7 = new JButton();
  Border border40;
  Border border41;
  JToggleButton jToggleButton67 = new JToggleButton();
  Border border42;
  Border border43;
  JPanel jPanel64 = new JPanel();
  JPanel jPanel65 = new JPanel();
  BorderLayout borderLayout52 = new BorderLayout();
  BorderLayout borderLayout53 = new BorderLayout();
  Border border44;
  JPanel jPanel66 = new JPanel();
  BorderLayout borderLayout54 = new BorderLayout();
  JToggleButton jToggleButton68 = new JToggleButton();
  Border border45;
  JPanel jPanel68 = new JPanel();
  GridLayout gridLayout14 = new GridLayout();
  JPanel jPanel69 = new JPanel();
  BorderLayout borderLayout56 = new BorderLayout();
  JPanel jPanel70 = new JPanel();
  BorderLayout borderLayout57 = new BorderLayout();
  Border border46;
  JToggleButton jToggleButton69 = new JToggleButton();
  JScrollPane jScrollPane5 = new JScrollPane();
  JToggleButton jToggleButton70 = new JToggleButton();
  JScrollPane jScrollPane6 = new JScrollPane();
  JPanel jPanel67 = new JPanel();
  BorderLayout borderLayout55 = new BorderLayout();
  JCheckBox jCheckBox4 = new JCheckBox();
  JCheckBox jCheckBox5 = new JCheckBox();
  Border border47;
  Border border48;
  JPanel jPanel71 = new JPanel();
  GridLayout gridLayout15 = new GridLayout();
  JPanel jPanel72 = new JPanel();
  GridLayout gridLayout16 = new GridLayout();

  //Construct the frame
  public DataSeriesStyleEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    border1 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder1 = new TitledBorder(border1,"테두리");
    border2 = BorderFactory.createEmptyBorder();
    border3 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder2 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"테두리");
    border4 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder3 = new TitledBorder(border4,"보기");
    border5 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder4 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"영역");
    border6 = BorderFactory.createEmptyBorder(5,5,0,0);
    border7 = BorderFactory.createEmptyBorder(0,3,5,5);
    border8 = BorderFactory.createEmptyBorder(0,0,0,90);
    border9 = BorderFactory.createEmptyBorder(13,2,6,0);
    border10 = BorderFactory.createCompoundBorder(titledBorder2,BorderFactory.createEmptyBorder(0,5,0,0));
    border11 = BorderFactory.createEmptyBorder(0,5,0,0);
    border12 = BorderFactory.createEmptyBorder(5,0,0,0);
    border13 = BorderFactory.createEmptyBorder(2,0,2,0);
    border14 = BorderFactory.createEmptyBorder(2,0,2,0);
    border15 = BorderFactory.createEmptyBorder(2,0,2,0);
    border16 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"영역"),BorderFactory.createEmptyBorder(0,4,0,2));
    border17 = BorderFactory.createEmptyBorder(1,3,0,3);
    border18 = BorderFactory.createEmptyBorder(5,4,0,0);
    border19 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder5 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"데이터 계열 지정");
    border20 = BorderFactory.createEmptyBorder(10,0,0,0);
    border21 = BorderFactory.createCompoundBorder(titledBorder5,BorderFactory.createEmptyBorder(0,5,0,0));
    border22 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder6 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"화면 표시(D)");
    border23 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder7 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"오차량");
    border24 = BorderFactory.createEmptyBorder(15,4,48,186);
    border25 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"오차량"),BorderFactory.createEmptyBorder(0,5,2,6));
    border26 = BorderFactory.createEmptyBorder();
    border27 = BorderFactory.createEmptyBorder(0,0,0,5);
    border28 = BorderFactory.createEmptyBorder(0,0,0,15);
    border29 = BorderFactory.createEmptyBorder();
    border30 = BorderFactory.createBevelBorder(BevelBorder.LOWERED,Color.white,Color.white,new Color(134, 134, 134),Color.black);
    border31 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"화면 표시(D)"),BorderFactory.createEmptyBorder(0,4,0,2));
    border32 = BorderFactory.createEmptyBorder(1,0,1,0);
    border33 = BorderFactory.createEmptyBorder(1,0,1,0);
    border34 = BorderFactory.createEmptyBorder(10,5,0,225);
    border35 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder8 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"데이터 레이블");
    border36 = BorderFactory.createCompoundBorder(titledBorder8,BorderFactory.createEmptyBorder(0,5,0,0));
    border38 = BorderFactory.createEmptyBorder(23,0,0,0);
    border39 = BorderFactory.createEmptyBorder(10,5,0,0);
    border40 = BorderFactory.createEmptyBorder(0,0,6,173);
    border41 = BorderFactory.createEmptyBorder();
    border42 = BorderFactory.createEmptyBorder(0,0,30,100);
    border43 = BorderFactory.createEmptyBorder(0,0,2,0);
    border44 = BorderFactory.createEmptyBorder(17,5,0,0);
    border45 = BorderFactory.createEmptyBorder(0,0,35,100);
    border46 = BorderFactory.createEmptyBorder(0,0,20,0);
    border47 = BorderFactory.createEmptyBorder(0,0,16,0);
    border48 = BorderFactory.createEmptyBorder(0,0,30,0);
    jPanel19.setLayout(borderLayout15);
    jToggleButton57.setRequestFocusEnabled(false);
    jToggleButton57.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton57.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-42.gif")));
    jToggleButton58.setRequestFocusEnabled(false);
    jToggleButton58.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton58.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-47.gif")));
    jToggleButton59.setRequestFocusEnabled(false);
    jToggleButton59.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton59.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-44.gif")));
    gridLayout1.setVgap(2);
    gridLayout1.setRows(3);
    gridLayout1.setColumns(1);
    gridLayout2.setVgap(3);
    gridLayout2.setRows(5);
    gridLayout2.setHgap(3);
    gridLayout2.setColumns(8);
    gridLayout3.setVgap(3);
    gridLayout3.setRows(2);
    gridLayout3.setHgap(3);
    gridLayout3.setColumns(8);
    contentPane = (JPanel) this.getContentPane();
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(460, 391));
    this.setTitle("데이터 계열 서식");
    jToggleButton56.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-51.gif")));
    jToggleButton56.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton56.setRequestFocusEnabled(false);
    jToggleButton55.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-46.gif")));
    jToggleButton55.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton55.setRequestFocusEnabled(false);
    jPanel17.setBorder(border12);
    jPanel17.setPreferredSize(new Dimension(0, 55));
    jPanel17.setLayout(borderLayout13);
    jToggleButton54.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-50.gif")));
    jToggleButton54.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton54.setRequestFocusEnabled(false);
    jPanel16.setPreferredSize(new Dimension(0, 60));
    jPanel16.setLayout(borderLayout14);
    jToggleButton53.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-43.gif")));
    jToggleButton53.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton53.setRequestFocusEnabled(false);
    jPanel15.setLayout(borderLayout17);
    jPanel15.setPreferredSize(new Dimension(148, 0));
    jToggleButton52.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-52.gif")));
    jToggleButton52.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton52.setRequestFocusEnabled(false);
    jPanel14.setLayout(gridLayout1);
    jPanel14.setBorder(border11);
    jPanel14.setPreferredSize(new Dimension(11, 80));
    jToggleButton51.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-45.gif")));
    jToggleButton51.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton51.setRequestFocusEnabled(false);
    jPanel13.setPreferredSize(new Dimension(0, 55));
    jPanel13.setLayout(borderLayout10);
    jToggleButton50.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-53.gif")));
    jToggleButton50.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton50.setRequestFocusEnabled(false);
    jPanel11.setBorder(border2);
    jPanel11.setPreferredSize(new Dimension(0, 57));
    jPanel11.setLayout(borderLayout9);
    jPanel10.setLayout(borderLayout12);
    jPanel10.setBorder(border16);
    jPanel10.setMinimumSize(new Dimension(182, 200));
    jPanel10.setPreferredSize(new Dimension(187, 250));
    jRadioButton5.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton5.setMnemonic('E');
    jRadioButton5.setText("없음(E)");
    jRadioButton5.setRequestFocusEnabled(false);
    jRadioButton4.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton4.setMnemonic('U');
    jRadioButton4.setText("자동(U)");
    jRadioButton4.setRequestFocusEnabled(false);
    jRadioButton3.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton3.setMnemonic('N');
    jRadioButton3.setText("없음(N)");
    jRadioButton3.setRequestFocusEnabled(false);
    jRadioButton2.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton2.setText("사용자 정의");
    jRadioButton2.setRequestFocusEnabled(false);
    jRadioButton1.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton1.setMnemonic('A');
    jRadioButton1.setText("자동(A)");
    jRadioButton1.setRequestFocusEnabled(false);
    jToggleButton49.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-49.gif")));
    jToggleButton49.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton49.setRequestFocusEnabled(false);
    jToggleButton48.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-54.gif")));
    jToggleButton48.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton48.setRequestFocusEnabled(false);
    jToggleButton47.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-55.gif")));
    jToggleButton47.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton47.setRequestFocusEnabled(false);
    jToggleButton46.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-56.gif")));
    jToggleButton46.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton46.setRequestFocusEnabled(false);
    jToggleButton45.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-41.gif")));
    jToggleButton45.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton45.setRequestFocusEnabled(false);
    jToggleButton44.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-32.gif")));
    jToggleButton44.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton44.setRequestFocusEnabled(false);
    borderLayout5.setVgap(2);
    jToggleButton43.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-31.gif")));
    jToggleButton43.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton43.setRequestFocusEnabled(false);
    borderLayout4.setHgap(5);
    jToggleButton42.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-30.gif")));
    jToggleButton42.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton42.setRequestFocusEnabled(false);
    jToggleButton41.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-21.gif")));
    jToggleButton41.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton41.setRequestFocusEnabled(false);
    jToggleButton40.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-16.gif")));
    jToggleButton40.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton40.setRequestFocusEnabled(false);
    jPanel9.setBorder(titledBorder3);
    jPanel9.setPreferredSize(new Dimension(12, 51));
    jPanel9.setLayout(borderLayout7);
    flowLayout1.setVgap(2);
    jPanel8.setLayout(borderLayout6);
    jPanel7.setLayout(borderLayout8);
    jToggleButton39.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-33.gif")));
    jToggleButton39.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton39.setRequestFocusEnabled(false);
    jPanel6.setPreferredSize(new Dimension(178, 0));
    jPanel6.setLayout(borderLayout5);
    jToggleButton38.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-34.gif")));
    jToggleButton38.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton38.setRequestFocusEnabled(false);
    jToggleButton37.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-28.gif")));
    jToggleButton37.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton37.setRequestFocusEnabled(false);
    jPanel4.setLayout(borderLayout11);
    jPanel4.setPreferredSize(new Dimension(0, 60));
    jToggleButton36.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-24.gif")));
    jToggleButton36.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton36.setRequestFocusEnabled(false);
    jPanel3.setLayout(borderLayout4);
    jToggleButton35.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-09.gif")));
    jToggleButton35.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton35.setRequestFocusEnabled(false);
    jPanel2.setLayout(borderLayout3);
    jPanel2.setPreferredSize(new Dimension(0, 20));
    jToggleButton34.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-29.gif")));
    jToggleButton34.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton34.setRequestFocusEnabled(false);
    jPanel1.setLayout(borderLayout2);
    jPanel1.setBorder(border6);
    jPanel1.setPreferredSize(new Dimension(0, 330));
    jToggleButton33.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-27.gif")));
    jToggleButton33.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton33.setRequestFocusEnabled(false);
    jToggleButton32.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-26.gif")));
    jToggleButton32.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton32.setRequestFocusEnabled(false);
    jToggleButton31.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-25.gif")));
    jToggleButton31.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton31.setRequestFocusEnabled(false);
    jButton2.setText("취소");
    jToggleButton30.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-19.gif")));
    jToggleButton30.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton30.setRequestFocusEnabled(false);
    jButton1.setMinimumSize(new Dimension(10, 10));
    jButton1.setPreferredSize(new Dimension(55, 29));
    jButton1.setText("확인");
    jToggleButton29.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-36.gif")));
    jToggleButton29.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton29.setRequestFocusEnabled(false);
    jToggleButton28.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-23.gif")));
    jToggleButton28.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton28.setRequestFocusEnabled(false);
    jToggleButton27.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-22.gif")));
    jToggleButton27.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton27.setRequestFocusEnabled(false);
    jToggleButton26.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-20.gif")));
    jToggleButton26.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton26.setRequestFocusEnabled(false);
    jToggleButton25.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-12.gif")));
    jToggleButton25.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton25.setRequestFocusEnabled(false);
    jToggleButton24.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-35.gif")));
    jToggleButton24.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton24.setRequestFocusEnabled(false);
    jToggleButton23.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-40.gif")));
    jToggleButton23.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton23.setRequestFocusEnabled(false);
    jToggleButton22.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-37.gif")));
    jToggleButton22.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton22.setRequestFocusEnabled(false);
    jToggleButton21.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-13.gif")));
    jToggleButton21.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton21.setRequestFocusEnabled(false);
    jToggleButton20.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-18.gif")));
    jToggleButton20.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton20.setRequestFocusEnabled(false);
    jPanel119.setBorder(border13);
    jPanel119.setPreferredSize(new Dimension(0, 29));
    jPanel119.setLayout(borderLayout117);
    jLabel1.setBorder(BorderFactory.createEtchedBorder());
    jLabel1.setPreferredSize(new Dimension(142, 2));
    jLabel1.setHorizontalAlignment(SwingConstants.LEFT);
    jLabel1.setVerticalAlignment(SwingConstants.TOP);
    jPanel118.setLayout(borderLayout116);
    jPanel117.setBorder(border14);
    jPanel117.setPreferredSize(new Dimension(0, 29));
    jPanel117.setLayout(borderLayout115);
    jPanel116.setLayout(borderLayout114);
    jPanel114.setLayout(borderLayout112);
    jToggleButton19.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-15.gif")));
    jToggleButton19.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton19.setRequestFocusEnabled(false);
    jPanel111.setBorder(border15);
    jPanel111.setPreferredSize(new Dimension(0, 29));
    jPanel111.setLayout(borderLayout19);
    jToggleButton18.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-17.gif")));
    jToggleButton18.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton18.setRequestFocusEnabled(false);
    jToggleButton17.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-14.gif")));
    jToggleButton17.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton17.setRequestFocusEnabled(false);
    jToggleButton16.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-10.gif")));
    jToggleButton16.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton16.setRequestFocusEnabled(false);
    jToggleButton15.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-38.gif")));
    jToggleButton15.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton15.setRequestFocusEnabled(false);
    jToggleButton14.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-11.gif")));
    jToggleButton14.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton14.setRequestFocusEnabled(false);
    jToggleButton13.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-08.gif")));
    jToggleButton13.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton13.setRequestFocusEnabled(false);
    jToggleButton12.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-05.gif")));
    jToggleButton12.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton12.setRequestFocusEnabled(false);
    jToggleButton11.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-07.gif")));
    jToggleButton11.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton11.setRequestFocusEnabled(false);
    jToggleButton10.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-03.gif")));
    jToggleButton10.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton10.setRequestFocusEnabled(false);
    jTabbedPane1.setPreferredSize(new Dimension(241, 74));
    jTabbedPane1.setRequestFocusEnabled(false);
    jToggleButton9.setRequestFocusEnabled(false);
    jToggleButton9.setText("스타일(S):   ");
    jToggleButton9.setMnemonic('S');
    jToggleButton9.setBorder(null);
    jToggleButton9.setMargin(new Insets(0, 0, 0, 0));
    borderLayout17.setHgap(5);
    jToggleButton8.setRequestFocusEnabled(false);
    jToggleButton8.setText("색(C):           ");
    jToggleButton8.setMnemonic('C');
    jToggleButton8.setBorder(null);
    jToggleButton8.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton7.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-06.gif")));
    jToggleButton7.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton7.setRequestFocusEnabled(false);
    jToggleButton6.setRequestFocusEnabled(false);
    jToggleButton6.setText("두께(W):      ");
    jToggleButton6.setMnemonic('W');
    jToggleButton6.setBorder(null);
    jToggleButton6.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton5.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-04.gif")));
    jToggleButton5.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton4.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-02.gif")));
    jToggleButton4.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton4.setRequestFocusEnabled(false);
    jToggleButton3.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-39.gif")));
    jToggleButton3.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton3.setRequestFocusEnabled(false);
    jToggleButton2.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-01.gif")));
    jToggleButton2.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton2.setRequestFocusEnabled(false);
    jToggleButton1.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton1.setPreferredSize(new Dimension(65, 25));
    jToggleButton1.setBorder(null);
    jToggleButton1.setMnemonic('O');
    jToggleButton1.setText("색(O):");
    jToggleButton1.setRequestFocusEnabled(false);
    jToggleButton1.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel24.setLayout(borderLayout20);
    jPanel23.setMinimumSize(new Dimension(50, 10));
    jPanel23.setPreferredSize(new Dimension(75, 0));
    jPanel23.setLayout(borderLayout18);
    jPanel22.setPreferredSize(new Dimension(140, 2));
    jPanel22.setLayout(flowLayout1);
    jToggleButton60.setIcon(new ImageIcon(jcosmos.Utility.getResource("chartextent1-48.gif")));
    jToggleButton60.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton60.setRequestFocusEnabled(false);
    jPanel21.setPreferredSize(new Dimension(0, 36));
    jPanel21.setLayout(gridLayout3);
    jPanel20.setPreferredSize(new Dimension(0, 90));
    jPanel20.setLayout(gridLayout2);
    jPanel8.setBorder(border10);
    jCheckBox1.setMnemonic('D');
    jCheckBox1.setText("그림자(D)");
    jCheckBox2.setPreferredSize(new Dimension(115, 29));
    jCheckBox2.setMnemonic('V');
    jCheckBox2.setText("음수이면 반전(V)");
    jCheckBox2.setVerticalAlignment(SwingConstants.TOP);
    contentPane.setBorder(border7);
    jPanel7.setBorder(border8);
    jPanel3.setBorder(border9);
    jPanel5.setLayout(borderLayout16);
    jPanel5.setBorder(border17);
    jPanel5.setPreferredSize(new Dimension(0, 19));
    jButton3.setText("채우기 효과(I)...");
    jPanel12.setLayout(borderLayout21);
    jPanel28.setLayout(borderLayout22);
    jPanel12.setBorder(border18);
    jPanel29.setLayout(borderLayout23);
    jPanel28.setBorder(border20);
    jPanel28.setPreferredSize(new Dimension(0, 73));
    jPanel30.setLayout(borderLayout24);
    jPanel30.setBorder(border21);
    jPanel30.setMinimumSize(new Dimension(50, 0));
    jPanel30.setPreferredSize(new Dimension(150, 0));
    jRadioButton6.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton6.setMnemonic('P');
    jRadioButton6.setText("기본 축(P)");
    jRadioButton7.setMnemonic('S');
    jRadioButton7.setText("보조 축(S)");
    jToggleButton61.setIcon(new ImageIcon(jcosmos.Utility.getResource("data01.gif")));
    jToggleButton61.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton61.setPreferredSize(new Dimension(330, 177));
    jToggleButton61.setBackground(Color.white);
    jToggleButton61.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton61.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel31.setLayout(borderLayout25);
    jPanel31.setPreferredSize(new Dimension(0, 33));
    borderLayout21.setVgap(10);
    jPanel18.setLayout(borderLayout26);
    jPanel32.setLayout(borderLayout27);
    jPanel32.setBorder(border31);
    jPanel32.setPreferredSize(new Dimension(12, 84));
    jPanel33.setBorder(border25);
    jPanel33.setLayout(borderLayout28);
    jPanel18.setBorder(border24);
    borderLayout26.setVgap(3);
    jPanel34.setLayout(gridLayout4);
    jPanel35.setLayout(gridLayout5);
    jPanel34.setPreferredSize(new Dimension(0, 15));
    gridLayout5.setColumns(4);
    gridLayout5.setHgap(13);
    jToggleButton62.setIcon(new ImageIcon(jcosmos.Utility.getResource("data02.gif")));
    jToggleButton62.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton62.setPreferredSize(new Dimension(40, 39));
    jToggleButton62.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton63.setIcon(new ImageIcon(jcosmos.Utility.getResource("data05.gif")));
    jToggleButton63.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton63.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton64.setIcon(new ImageIcon(jcosmos.Utility.getResource("data04.gif")));
    jToggleButton64.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton64.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton65.setIcon(new ImageIcon(jcosmos.Utility.getResource("data03.gif")));
    jToggleButton65.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton65.setBorder(BorderFactory.createLoweredBevelBorder());
    gridLayout4.setColumns(4);
    gridLayout4.setHgap(11);
    jLabel2.setText("   모두");
    jLabel3.setText("    없음");
    jLabel4.setText("  음의 값");
    jLabel5.setText(" 양의  값");
    borderLayout28.setVgap(4);
    jPanel36.setLayout(borderLayout29);
    jPanel37.setLayout(borderLayout30);
    jPanel37.setBackground(Color.orange);
    jPanel37.setPreferredSize(new Dimension(0, 39));
    jPanel36.setBackground(Color.pink);
    jPanel38.setLayout(gridLayout6);
    gridLayout6.setColumns(1);
    gridLayout6.setRows(4);
    gridLayout6.setVgap(3);
    jPanel43.setLayout(gridLayout7);
    gridLayout7.setColumns(1);
    gridLayout7.setRows(2);
    gridLayout7.setVgap(2);
    jPanel39.setLayout(borderLayout31);
    jPanel42.setLayout(borderLayout32);
    jPanel41.setLayout(borderLayout33);
    jPanel40.setLayout(borderLayout34);
    jPanel44.setLayout(borderLayout35);
    jPanel45.setLayout(borderLayout36);
    jRadioButton8.setMnemonic('F');
    jRadioButton8.setText("고정값(F):            ");
    jRadioButton9.setMnemonic('P');
    jRadioButton9.setText("백분율(P):            ");
    jRadioButton10.setToolTipText("");
    jRadioButton10.setMnemonic('S');
    jRadioButton10.setText("표준 편차(S):       ");
    jRadioButton11.setMnemonic('E');
    jRadioButton11.setText("표준 오차(E)");
    jRadioButton12.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton12.setMnemonic('C');
    jRadioButton12.setText("사용자 정의(C):");
    jPanel46.setLayout(borderLayout37);
    jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane1.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane1.setPreferredSize(new Dimension(85, 4));
    jPanel47.setLayout(gridLayout8);
    jPanel47.setBackground(Color.white);
    jPanel48.setLayout(borderLayout38);
    jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane2.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane2.setPreferredSize(new Dimension(85, 4));
    jPanel49.setBackground(Color.white);
    jPanel49.setLayout(gridLayout9);
    jLabel6.setText("%");
    jPanel50.setLayout(borderLayout39);
    jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane3.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane3.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane3.setPreferredSize(new Dimension(85, 4));
    jPanel51.setLayout(gridLayout10);
    jPanel51.setBackground(Color.white);
    jPanel52.setLayout(borderLayout40);
    jLabel7.setText("+  ");
    jPanel53.setLayout(borderLayout41);
    jPanel53.setBorder(border33);
    jPanel53.setPreferredSize(new Dimension(125, 0));
    jTextField2.setPreferredSize(new Dimension(55, 22));
    jLabel8.setText(" -  ");
    borderLayout30.setVgap(2);
    jPanel46.setBorder(border26);
    jPanel39.setBorder(border27);
    jPanel48.setBorder(border28);
    jPanel50.setBorder(border29);
    jPanel35.setPreferredSize(new Dimension(692, 45));
    jButton4.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton4.setPreferredSize(new Dimension(20, 21));
    jButton4.setIcon(new ImageIcon(jcosmos.Utility.getResource("data06.gif")));
    jButton4.setMargin(new Insets(0, 0, 0, 0));
    jButton5.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton5.setPreferredSize(new Dimension(20, 15));
    jButton5.setHorizontalTextPosition(SwingConstants.LEADING);
    jButton5.setIcon(new ImageIcon(jcosmos.Utility.getResource("data06.gif")));
    jButton5.setMargin(new Insets(0, 0, 0, 0));
    jPanel52.setBorder(border32);
    jPanel38.setPreferredSize(new Dimension(219, 115));
    jPanel43.setPreferredSize(new Dimension(141, 48));
    jPanel25.setLayout(borderLayout42);
    jPanel25.setBorder(border34);
    jPanel55.setLayout(borderLayout43);
    jPanel54.setLayout(borderLayout44);
    jPanel55.setBorder(border38);
    jPanel55.setPreferredSize(new Dimension(0, 150));
    jPanel54.setBorder(border36);
    jPanel54.setPreferredSize(new Dimension(171, 180));
    jCheckBox3.setText("레이블 옆에 범례 표시(K)");
    jPanel56.setLayout(gridLayout11);
    gridLayout11.setColumns(1);
    gridLayout11.setRows(6);
    jRadioButton13.setMnemonic('N');
    jRadioButton13.setText("없음(N)");
    jRadioButton14.setMnemonic('V');
    jRadioButton14.setText("값 표시(V)");
    jRadioButton15.setMnemonic('P');
    jRadioButton15.setText("백분율 표시(P)");
    jRadioButton16.setMnemonic('L');
    jRadioButton16.setText("레이블 표시(L)");
    jRadioButton17.setText("레이블과 백분율 표시(A)");
    jRadioButton18.setText("거품 크기 표시(B) ");
    jPanel26.setLayout(borderLayout45);
    jPanel27.setLayout(borderLayout46);
    jPanel57.setLayout(borderLayout47);
    jPanel58.setLayout(borderLayout48);
    jPanel57.setBorder(border43);
    jPanel57.setPreferredSize(new Dimension(0, 83));
    jPanel26.setBorder(border39);
    jPanel59.setLayout(borderLayout49);
    jPanel60.setLayout(borderLayout50);
    jPanel59.setPreferredSize(new Dimension(0, 30));
    jToggleButton66.setBorder(null);
    jToggleButton66.setMnemonic('S');
    jToggleButton66.setText("계열 순서(S):");
    jToggleButton66.setRequestFocusEnabled(false);
    jToggleButton66.setVerticalAlignment(SwingConstants.BOTTOM);
    jScrollPane4.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane4.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane4.setPreferredSize(new Dimension(150, 4));
    jPanel61.setBackground(Color.white);
    jPanel61.setLayout(gridLayout12);
    gridLayout12.setColumns(1);
    gridLayout12.setRows(3);
    jPanel62.setLayout(gridLayout13);
    jPanel62.setBackground(Color.white);
    jPanel62.setPreferredSize(new Dimension(27, 45));
    gridLayout13.setColumns(1);
    gridLayout13.setRows(3);
    jLabel9.setText(" 동부");
    jLabel10.setText(" 북부");
    jLabel11.setText(" 서부");
    jPanel63.setLayout(borderLayout51);
    jButton6.setPreferredSize(new Dimension(75, 20));
    jButton6.setMargin(new Insets(0, 0, 0, 0));
    jButton6.setMnemonic('U');
    jButton6.setText("위로 이동(U)");
    jButton7.setPreferredSize(new Dimension(115, 35));
    jButton7.setMargin(new Insets(0, 0, 0, 0));
    jButton7.setMnemonic('D');
    jButton7.setText("아래로 이동(D)");
    jPanel63.setBorder(border40);
    borderLayout50.setHgap(15);
    borderLayout51.setVgap(5);
    jPanel60.setBorder(border2);
    jPanel60.setPreferredSize(new Dimension(455, 67));
    jToggleButton67.setIcon(new ImageIcon(jcosmos.Utility.getResource("data01.gif")));
    jToggleButton67.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton67.setBorder(BorderFactory.createLoweredBevelBorder());
    borderLayout45.setVgap(8);
    jPanel58.setBorder(border42);
    jPanel58.setPreferredSize(new Dimension(435, 208));
    jPanel64.setLayout(borderLayout52);
    jPanel65.setLayout(borderLayout53);
    jPanel64.setBorder(border47);
    jPanel64.setPreferredSize(new Dimension(0, 80));
    jPanel27.setBorder(border44);
    jPanel66.setLayout(borderLayout54);
    jPanel66.setBorder(border46);
    jPanel66.setPreferredSize(new Dimension(170, 0));
    jToggleButton68.setIcon(new ImageIcon(jcosmos.Utility.getResource("data01.gif")));
    jToggleButton68.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton68.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton68.setRequestFocusEnabled(false);
    jPanel65.setBorder(border45);
    jPanel65.setPreferredSize(new Dimension(435, 200));
    jPanel68.setLayout(gridLayout14);
    gridLayout14.setColumns(1);
    gridLayout14.setRows(2);
    gridLayout14.setVgap(5);
    jPanel69.setLayout(borderLayout56);
    jPanel70.setLayout(borderLayout57);
    jToggleButton69.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton69.setBorder(null);
    jToggleButton69.setMnemonic('O');
    jToggleButton69.setText("겹치기(O):   ");
    jToggleButton69.setRequestFocusEnabled(false);
    jScrollPane5.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane5.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane5.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane5.setPreferredSize(new Dimension(60, 4));
    jToggleButton70.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton70.setBorder(null);
    jToggleButton70.setMnemonic('W');
    jToggleButton70.setText("간격 너비(W):");
    jToggleButton70.setRequestFocusEnabled(false);
    jScrollPane6.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane6.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane6.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane6.setMinimumSize(new Dimension(24, 2));
    jScrollPane6.setPreferredSize(new Dimension(60, 4));
    jPanel67.setLayout(borderLayout55);
    jPanel67.setBorder(border48);
    jPanel67.setPreferredSize(new Dimension(160, 0));
    jCheckBox4.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox4.setMnemonic('S');
    jCheckBox4.setText("계열선(S)");
    jCheckBox4.setRequestFocusEnabled(false);
    jCheckBox5.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox5.setMnemonic('V');
    jCheckBox5.setText("요소마다 다른 색 사용(V)");
    jCheckBox5.setRequestFocusEnabled(false);
    jPanel71.setLayout(gridLayout15);
    jPanel71.setBackground(Color.white);
    jPanel72.setBackground(Color.white);
    jPanel72.setLayout(gridLayout16);
    contentPane.add(jPanel1, BorderLayout.NORTH);
    jPanel1.add(jTabbedPane1, BorderLayout.CENTER);
    contentPane.add(jPanel2, BorderLayout.SOUTH);
    jPanel2.add(jPanel15, BorderLayout.EAST);
    jPanel15.add(jPanel23, BorderLayout.WEST);
    jPanel23.add(jButton1, BorderLayout.CENTER);
    jPanel15.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jButton2, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel3, "   무늬   ");
    jPanel3.add(jPanel6, BorderLayout.WEST);
    jPanel6.add(jPanel8, BorderLayout.CENTER);
    jPanel8.add(jPanel13, BorderLayout.NORTH);
    jPanel13.add(jPanel11, BorderLayout.NORTH);
    jPanel11.add(jRadioButton1, BorderLayout.NORTH);
    jPanel11.add(jRadioButton2, BorderLayout.SOUTH);
    jPanel11.add(jRadioButton3, BorderLayout.CENTER);
    jPanel8.add(jPanel14, BorderLayout.CENTER);
    jPanel14.add(jPanel119, null);
    jPanel119.add(jToggleButton9, BorderLayout.WEST);
    jPanel119.add(jPanel118, BorderLayout.CENTER);
    jPanel118.add(jComboBox9, BorderLayout.CENTER);
    jPanel14.add(jPanel117, null);
    jPanel117.add(jToggleButton8, BorderLayout.WEST);
    jPanel117.add(jPanel116, BorderLayout.CENTER);
    jPanel116.add(jComboBox8, BorderLayout.CENTER);
    jPanel14.add(jPanel111, null);
    jPanel111.add(jToggleButton6, BorderLayout.WEST);
    jPanel111.add(jPanel114, BorderLayout.CENTER);
    jPanel114.add(jComboBox6, BorderLayout.CENTER);
    jPanel8.add(jPanel4, BorderLayout.SOUTH);
    jPanel4.add(jCheckBox1, BorderLayout.CENTER);
    jPanel6.add(jPanel9, BorderLayout.SOUTH);
    jPanel3.add(jPanel7, BorderLayout.CENTER);
    jPanel7.add(jPanel10, BorderLayout.CENTER);
    jPanel10.add(jPanel16, BorderLayout.NORTH);
    jPanel16.add(jRadioButton4, BorderLayout.NORTH);
    jPanel16.add(jRadioButton5, BorderLayout.CENTER);
    jPanel16.add(jToggleButton1, BorderLayout.SOUTH);
    jPanel10.add(jPanel17, BorderLayout.SOUTH);
    jPanel17.add(jCheckBox2, BorderLayout.SOUTH);
    jPanel17.add(jPanel5, BorderLayout.NORTH);
    jPanel5.add(jButton3, BorderLayout.CENTER);
    jPanel10.add(jPanel19, BorderLayout.CENTER);
    jPanel19.add(jPanel20, BorderLayout.NORTH);
    jPanel20.add(jToggleButton2, null);
    jPanel20.add(jToggleButton4, null);
    jPanel20.add(jToggleButton10, null);
    jPanel20.add(jToggleButton5, null);
    jPanel20.add(jToggleButton12, null);
    jPanel20.add(jToggleButton7, null);
    jPanel20.add(jToggleButton11, null);
    jPanel20.add(jToggleButton13, null);
    jPanel20.add(jToggleButton35, null);
    jPanel20.add(jToggleButton16, null);
    jPanel20.add(jToggleButton14, null);
    jPanel20.add(jToggleButton25, null);
    jPanel20.add(jToggleButton21, null);
    jPanel20.add(jToggleButton17, null);
    jPanel20.add(jToggleButton19, null);
    jPanel20.add(jToggleButton40, null);
    jPanel20.add(jToggleButton18, null);
    jPanel20.add(jToggleButton20, null);
    jPanel20.add(jToggleButton30, null);
    jPanel20.add(jToggleButton26, null);
    jPanel20.add(jToggleButton41, null);
    jPanel20.add(jToggleButton27, null);
    jPanel20.add(jToggleButton28, null);
    jPanel20.add(jToggleButton36, null);
    jPanel20.add(jToggleButton31, null);
    jPanel20.add(jToggleButton32, null);
    jPanel20.add(jToggleButton33, null);
    jPanel20.add(jToggleButton37, null);
    jPanel20.add(jToggleButton34, null);
    jPanel20.add(jToggleButton42, null);
    jPanel20.add(jToggleButton43, null);
    jPanel20.add(jToggleButton44, null);
    jPanel20.add(jToggleButton39, null);
    jPanel20.add(jToggleButton38, null);
    jPanel20.add(jToggleButton24, null);
    jPanel20.add(jToggleButton29, null);
    jPanel20.add(jToggleButton22, null);
    jPanel20.add(jToggleButton15, null);
    jPanel20.add(jToggleButton3, null);
    jPanel20.add(jToggleButton23, null);
    jPanel19.add(jPanel21, BorderLayout.SOUTH);
    jPanel21.add(jToggleButton45, null);
    jPanel21.add(jToggleButton57, null);
    jPanel21.add(jToggleButton53, null);
    jPanel21.add(jToggleButton59, null);
    jPanel21.add(jToggleButton51, null);
    jPanel21.add(jToggleButton55, null);
    jPanel21.add(jToggleButton58, null);
    jPanel21.add(jToggleButton60, null);
    jPanel21.add(jToggleButton49, null);
    jPanel21.add(jToggleButton54, null);
    jPanel21.add(jToggleButton56, null);
    jPanel21.add(jToggleButton52, null);
    jPanel21.add(jToggleButton50, null);
    jPanel21.add(jToggleButton48, null);
    jPanel21.add(jToggleButton47, null);
    jPanel21.add(jToggleButton46, null);
    jPanel19.add(jPanel22, BorderLayout.WEST);
    jPanel22.add(jLabel1, null);
    jTabbedPane1.add(jPanel12, "     축     ");
    jPanel12.add(jPanel28, BorderLayout.NORTH);
    jPanel28.add(jPanel30, BorderLayout.WEST);
    jPanel30.add(jRadioButton6, BorderLayout.NORTH);
    jPanel30.add(jRadioButton7, BorderLayout.CENTER);
    jPanel12.add(jPanel29, BorderLayout.CENTER);
    jPanel29.add(jToggleButton61, BorderLayout.WEST);
    jPanel29.add(jPanel31, BorderLayout.SOUTH);
    jTabbedPane1.add(jPanel18, "  Y오차 막대  ");
    jPanel18.add(jPanel32, BorderLayout.NORTH);
    jPanel32.add(jPanel34, BorderLayout.SOUTH);
    jPanel34.add(jLabel2, null);
    jPanel34.add(jLabel5, null);
    jPanel34.add(jLabel4, null);
    jPanel34.add(jLabel3, null);
    jPanel32.add(jPanel35, BorderLayout.CENTER);
    jPanel35.add(jToggleButton62, null);
    jPanel35.add(jToggleButton65, null);
    jPanel35.add(jToggleButton64, null);
    jPanel35.add(jToggleButton63, null);
    jPanel18.add(jPanel33, BorderLayout.CENTER);
    jPanel33.add(jPanel36, BorderLayout.CENTER);
    jPanel36.add(jPanel38, BorderLayout.CENTER);
    jPanel38.add(jPanel39, null);
    jPanel39.add(jRadioButton8, BorderLayout.WEST);
    jPanel39.add(jPanel46, BorderLayout.CENTER);
    jPanel46.add(jScrollPane1, BorderLayout.WEST);
    jScrollPane1.getViewport().add(jPanel47, null);
    jPanel38.add(jPanel42, null);
    jPanel42.add(jRadioButton9, BorderLayout.WEST);
    jPanel42.add(jPanel48, BorderLayout.CENTER);
    jPanel48.add(jScrollPane2, BorderLayout.WEST);
    jPanel48.add(jLabel6, BorderLayout.EAST);
    jScrollPane2.getViewport().add(jPanel49, null);
    jPanel38.add(jPanel41, null);
    jPanel41.add(jRadioButton10, BorderLayout.WEST);
    jPanel41.add(jPanel50, BorderLayout.CENTER);
    jPanel50.add(jScrollPane3, BorderLayout.WEST);
    jScrollPane3.getViewport().add(jPanel51, null);
    jPanel38.add(jPanel40, null);
    jPanel40.add(jRadioButton11, BorderLayout.WEST);
    jPanel33.add(jPanel37, BorderLayout.SOUTH);
    jPanel37.add(jPanel43, BorderLayout.CENTER);
    jPanel43.add(jPanel44, null);
    jPanel44.add(jRadioButton12, BorderLayout.WEST);
    jPanel44.add(jPanel52, BorderLayout.CENTER);
    jPanel52.add(jTextField1, BorderLayout.CENTER);
    jPanel52.add(jLabel7, BorderLayout.WEST);
    jPanel52.add(jButton4, BorderLayout.EAST);
    jPanel43.add(jPanel45, null);
    jPanel45.add(jPanel53, BorderLayout.EAST);
    jPanel53.add(jLabel8, BorderLayout.WEST);
    jPanel53.add(jTextField2, BorderLayout.CENTER);
    jPanel53.add(jButton5, BorderLayout.EAST);
    jTabbedPane1.add(jPanel25, "  데이터 레이블  ");
    jPanel25.add(jPanel54, BorderLayout.CENTER);
    jPanel54.add(jPanel56, BorderLayout.CENTER);
    jPanel56.add(jRadioButton13, null);
    jPanel56.add(jRadioButton14, null);
    jPanel56.add(jRadioButton15, null);
    jPanel56.add(jRadioButton16, null);
    jPanel56.add(jRadioButton17, null);
    jPanel56.add(jRadioButton18, null);
    jPanel25.add(jPanel55, BorderLayout.SOUTH);
    jPanel55.add(jCheckBox3, BorderLayout.NORTH);
    jTabbedPane1.add(jPanel26, " 계열 순서 ");
    jPanel26.add(jPanel57, BorderLayout.NORTH);
    jPanel57.add(jPanel59, BorderLayout.NORTH);
    jPanel59.add(jToggleButton66, BorderLayout.WEST);
    jPanel57.add(jPanel60, BorderLayout.CENTER);
    jPanel60.add(jScrollPane4, BorderLayout.WEST);
    jPanel60.add(jPanel63, BorderLayout.CENTER);
    jPanel63.add(jButton6, BorderLayout.NORTH);
    jPanel63.add(jButton7, BorderLayout.CENTER);
    jScrollPane4.getViewport().add(jPanel62, null);
    jPanel62.add(jLabel9, null);
    jPanel62.add(jLabel11, null);
    jPanel62.add(jLabel10, null);
    jPanel26.add(jPanel58, BorderLayout.CENTER);
    jPanel58.add(jToggleButton67, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel27, "  옵션  ");
    jPanel27.add(jPanel64, BorderLayout.NORTH);
    jPanel64.add(jPanel66, BorderLayout.WEST);
    jPanel66.add(jPanel68, BorderLayout.CENTER);
    jPanel68.add(jPanel69, null);
    jPanel69.add(jToggleButton69, BorderLayout.WEST);
    jPanel69.add(jScrollPane5, BorderLayout.EAST);
    jScrollPane5.getViewport().add(jPanel71, null);
    jPanel68.add(jPanel70, null);
    jPanel70.add(jToggleButton70, BorderLayout.WEST);
    jPanel70.add(jScrollPane6, BorderLayout.EAST);
    jScrollPane6.getViewport().add(jPanel72, null);
    jPanel64.add(jPanel67, BorderLayout.EAST);
    jPanel67.add(jCheckBox4, BorderLayout.NORTH);
    jPanel67.add(jCheckBox5, BorderLayout.CENTER);
    jPanel27.add(jPanel65, BorderLayout.CENTER);
    jPanel65.add(jToggleButton68, BorderLayout.CENTER);
  }



}