package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class DataTableStyleEditor extends JFrame {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  BorderLayout borderLayout27 = new BorderLayout();
  BorderLayout borderLayout26 = new BorderLayout();
  BorderLayout borderLayout25 = new BorderLayout();
  BorderLayout borderLayout24 = new BorderLayout();
  BorderLayout borderLayout23 = new BorderLayout();
  BorderLayout borderLayout22 = new BorderLayout();
  JPanel jPanel10 = new JPanel();
  JRadioButton jRadioButton3 = new JRadioButton();
  JRadioButton jRadioButton2 = new JRadioButton();
  JRadioButton jRadioButton1 = new JRadioButton();
  JToggleButton jToggleButton3 = new JToggleButton();
  JToggleButton jToggleButton2 = new JToggleButton();
  JToggleButton jToggleButton1 = new JToggleButton();
  JPanel jPanel9 = new JPanel();
  JPanel jPanel7 = new JPanel();
  JPanel jPanel6 = new JPanel();
  JPanel jPanel1 = new JPanel();
  GridLayout gridLayout1 = new GridLayout();
  JPanel jPanel28 = new JPanel();
  JPanel jPanel27 = new JPanel();
  JPanel jPanel26 = new JPanel();
  JPanel jPanel25 = new JPanel();
  JPanel jPanel22 = new JPanel();
  JPanel jPanel21 = new JPanel();
  BorderLayout borderLayout7 = new BorderLayout();
  BorderLayout borderLayout6 = new BorderLayout();
  JPanel jPanel20 = new JPanel();
  BorderLayout borderLayout5 = new BorderLayout();
  BorderLayout borderLayout3 = new BorderLayout();
  BorderLayout borderLayout2 = new BorderLayout();
  JComboBox jComboBox3 = new JComboBox();
  JComboBox jComboBox2 = new JComboBox();
  JComboBox jComboBox1 = new JComboBox();
  JPanel jPanel19 = new JPanel();
  BorderLayout borderLayout28 = new BorderLayout();
  JPanel jPanel15 = new JPanel();
  BorderLayout borderLayout20 = new BorderLayout();
  JButton jButton2 = new JButton();
  JButton jButton1 = new JButton();
  BorderLayout borderLayout18 = new BorderLayout();
  BorderLayout borderLayout17 = new BorderLayout();
  JPanel jPanel8 = new JPanel();
  JPanel jPanel24 = new JPanel();
  JPanel jPanel23 = new JPanel();
  BorderLayout borderLayout4 = new BorderLayout();
  Border border1;
  TitledBorder titledBorder1;
  Border border2;
  TitledBorder titledBorder2;
  JPanel jPanel2 = new JPanel();
  BorderLayout borderLayout8 = new BorderLayout();
  JCheckBox jCheckBox1 = new JCheckBox();
  Border border3;
  Border border4;
  Border border5;
  Border border6;
  Border border7;
  Border border8;
  JPanel jPanel3 = new JPanel();
  JPanel jPanel4 = new JPanel();
  BorderLayout borderLayout10 = new BorderLayout();
  Border border9;
  TitledBorder titledBorder3;
  GridLayout gridLayout2 = new GridLayout();
  JPanel jPanel5 = new JPanel();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel12 = new JPanel();
  Border border10;
  Border border11;
  BorderLayout borderLayout9 = new BorderLayout();
  BorderLayout borderLayout11 = new BorderLayout();
  BorderLayout borderLayout12 = new BorderLayout();
  JCheckBox jCheckBox2 = new JCheckBox();
  JCheckBox jCheckBox3 = new JCheckBox();
  JCheckBox jCheckBox4 = new JCheckBox();
  JToggleButton jToggleButton4 = new JToggleButton();
  JToggleButton jToggleButton5 = new JToggleButton();
  JToggleButton jToggleButton6 = new JToggleButton();
  Border border12;
  JLabel jLabel1 = new JLabel();
  Border border13;
  TitledBorder titledBorder4;

  //Construct the frame
  public DataTableStyleEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    contentPane = (JPanel) this.getContentPane();
    border1 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder1 = new TitledBorder(border1,"선");
    border2 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder2 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"선");
    border3 = BorderFactory.createEmptyBorder(5,5,5,8);
    border4 = BorderFactory.createEmptyBorder(7,0,0,0);
    border5 = BorderFactory.createEmptyBorder(0,5,50,0);
    border6 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"선"),BorderFactory.createEmptyBorder(0,3,0,0));
    border7 = BorderFactory.createEmptyBorder(0,2,0,0);
    border8 = BorderFactory.createEmptyBorder(0,6,0,0);
    border9 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder3 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"보기");
    border10 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"보기");
    border11 = BorderFactory.createEmptyBorder(0,7,50,35);
    border12 = BorderFactory.createEmptyBorder(8,8,0,0);
    border13 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"보기"),BorderFactory.createEmptyBorder(0,2,3,2));
    titledBorder4 = new TitledBorder("");
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(406, 338));
    this.setTitle("DataTableStyle");
    jPanel10.setLayout(borderLayout7);
    jPanel10.setBorder(border6);
    jPanel10.setPreferredSize(new Dimension(0, 156));
    jRadioButton3.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton3.setPreferredSize(new Dimension(99, 20));
    jRadioButton3.setText("사용자 정의");
    jRadioButton2.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton2.setPreferredSize(new Dimension(99, 20));
    jRadioButton2.setMnemonic('A');
    jRadioButton2.setText("자동(A)");
    jRadioButton2.setVerticalAlignment(SwingConstants.TOP);
    jRadioButton1.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton1.setPreferredSize(new Dimension(99, 20));
    jRadioButton1.setMnemonic('N');
    jRadioButton1.setText("없음(N)");
    jToggleButton3.setBorder(null);
    jToggleButton3.setText("두께(W):        ");
    jToggleButton3.setRequestFocusEnabled(false);
    jToggleButton2.setBorder(null);
    jToggleButton2.setText("색(C):             ");
    jToggleButton2.setRequestFocusEnabled(false);
    jToggleButton1.setBorder(null);
    jToggleButton1.setText("스타일(S):     ");
    jToggleButton1.setRequestFocusEnabled(false);
    jPanel9.setLayout(borderLayout6);
    jPanel9.setBorder(border11);
    jPanel9.setPreferredSize(new Dimension(350, 0));
    jPanel7.setLayout(borderLayout3);
    jPanel6.setLayout(borderLayout5);
    jPanel6.setBorder(border7);
    jPanel6.setPreferredSize(new Dimension(195, 0));
    jPanel1.setLayout(borderLayout2);
    gridLayout1.setColumns(1);
    gridLayout1.setRows(3);
    gridLayout1.setVgap(1);
    jPanel28.setLayout(borderLayout28);
    jPanel27.setLayout(borderLayout27);
    jPanel26.setLayout(borderLayout26);
    jPanel25.setLayout(borderLayout25);
    jPanel22.setLayout(borderLayout24);
    jPanel21.setLayout(borderLayout23);
    jPanel20.setLayout(gridLayout1);
    jPanel20.setBorder(border8);
    jPanel20.setPreferredSize(new Dimension(0, 20));
    jPanel19.setLayout(borderLayout22);
    jPanel19.setMinimumSize(new Dimension(0, 30));
    jPanel19.setPreferredSize(new Dimension(0, 58));
    jPanel15.setPreferredSize(new Dimension(160, 0));
    jPanel15.setLayout(borderLayout17);
    jButton2.setText("취소");
    jButton1.setText("확인");
    borderLayout17.setHgap(5);
    jPanel8.setLayout(borderLayout4);
    jPanel8.setBorder(border4);
    jPanel8.setPreferredSize(new Dimension(0, 27));
    jPanel24.setLayout(borderLayout20);
    jPanel23.setMinimumSize(new Dimension(50, 10));
    jPanel23.setPreferredSize(new Dimension(80, 0));
    jPanel23.setLayout(borderLayout18);
    jPanel2.setLayout(borderLayout8);
    jCheckBox1.setMnemonic('E');
    jCheckBox1.setText("범례 표식 표시(E)");
    contentPane.setBorder(border3);
    jTabbedPane1.setRequestFocusEnabled(false);
    jPanel2.setBorder(border5);
    jPanel2.setPreferredSize(new Dimension(119, 100));
    jPanel3.setLayout(gridLayout2);
    jPanel4.setLayout(borderLayout10);
    jPanel3.setBorder(border12);
    jPanel3.setPreferredSize(new Dimension(0, 100));
    jPanel4.setBorder(border13);
    gridLayout2.setRows(3);
    gridLayout2.setHgap(2);
    jPanel5.setLayout(borderLayout9);
    jPanel11.setLayout(borderLayout11);
    jPanel12.setLayout(borderLayout12);
    jCheckBox2.setMnemonic('H');
    jCheckBox2.setText("가로( H)   ");
    jCheckBox3.setMnemonic('V');
    jCheckBox3.setText("세로(V)    ");
    jCheckBox4.setMnemonic('O');
    jCheckBox4.setText("윤곽선(O)");
    jToggleButton4.setIcon(new ImageIcon(jcosmos.Utility.getResource("h.gif")));
    jToggleButton4.setBorder(null);
    jToggleButton4.setRequestFocusEnabled(false);
    jToggleButton5.setIcon(new ImageIcon(jcosmos.Utility.getResource("v.gif")));
    jToggleButton5.setBorder(null);
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton6.setIcon(new ImageIcon(jcosmos.Utility.getResource("hv.gif")));
    jToggleButton6.setBorder(null);
    jToggleButton6.setRequestFocusEnabled(false);
    jLabel1.setBackground(Color.white);
    jLabel1.setBorder(BorderFactory.createLoweredBevelBorder());
    contentPane.add(jTabbedPane1, BorderLayout.CENTER);
    contentPane.add(jPanel8, BorderLayout.SOUTH);
    jPanel8.add(jPanel15, BorderLayout.EAST);
    jPanel15.add(jPanel23, BorderLayout.WEST);
    jPanel23.add(jButton1, BorderLayout.CENTER);
    jPanel15.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jButton2, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel1, "  무늬  ");
    jPanel1.add(jPanel7, BorderLayout.CENTER);
    jPanel7.add(jPanel6, BorderLayout.WEST);
    jPanel6.add(jPanel10, BorderLayout.NORTH);
    jPanel10.add(jPanel19, BorderLayout.NORTH);
    jPanel19.add(jRadioButton1, BorderLayout.CENTER);
    jPanel19.add(jRadioButton2, BorderLayout.NORTH);
    jPanel19.add(jRadioButton3, BorderLayout.SOUTH);
    jPanel10.add(jPanel20, BorderLayout.CENTER);
    jPanel20.add(jPanel21, null);
    jPanel21.add(jToggleButton1, BorderLayout.WEST);
    jPanel21.add(jPanel26, BorderLayout.CENTER);
    jPanel26.add(jComboBox1, BorderLayout.CENTER);
    jPanel20.add(jPanel22, null);
    jPanel22.add(jToggleButton2, BorderLayout.WEST);
    jPanel22.add(jPanel27, BorderLayout.CENTER);
    jPanel27.add(jComboBox2, BorderLayout.CENTER);
    jPanel20.add(jPanel25, null);
    jPanel25.add(jToggleButton3, BorderLayout.WEST);
    jPanel25.add(jPanel28, BorderLayout.CENTER);
    jPanel28.add(jComboBox3, BorderLayout.CENTER);
    jPanel6.add(jPanel2, BorderLayout.SOUTH);
    jPanel2.add(jCheckBox1, BorderLayout.CENTER);
    jPanel7.add(jPanel9, BorderLayout.CENTER);
    jPanel9.add(jPanel3, BorderLayout.NORTH);
    jPanel3.add(jPanel5, null);
    jPanel5.add(jCheckBox2, BorderLayout.WEST);
    jPanel5.add(jToggleButton4, BorderLayout.CENTER);
    jPanel3.add(jPanel11, null);
    jPanel11.add(jCheckBox3, BorderLayout.WEST);
    jPanel11.add(jToggleButton5, BorderLayout.CENTER);
    jPanel3.add(jPanel12, null);
    jPanel12.add(jCheckBox4, BorderLayout.WEST);
    jPanel12.add(jToggleButton6, BorderLayout.CENTER);
    jPanel9.add(jPanel4, BorderLayout.CENTER);
    jPanel4.add(jLabel1, BorderLayout.CENTER);
  }

  //Overridden so we can exit when window is closed
  protected void processWindowEvent(WindowEvent e) {
    super.processWindowEvent(e);
    if (e.getID() == WindowEvent.WINDOW_CLOSING) {
      System.exit(0);
    }
  }
}