
/**
 * Title:        chartwizard<p>
 * Description:  JAVA CHART v1.0<p>
 * Copyright:    Copyright (c) juney<p>
 * Company:      JCosmos<p>
 * @author juney
 * @version 1.0
 */
package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class GridLineStyleEditor extends Editor {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel15 = new JPanel();
  BorderLayout borderLayout20 = new BorderLayout();
  JButton jButton2 = new JButton();
  JButton jButton1 = new JButton();
  BorderLayout borderLayout18 = new BorderLayout();
  BorderLayout borderLayout17 = new BorderLayout();
  JPanel jPanel8 = new JPanel();
  JPanel jPanel24 = new JPanel();
  JPanel jPanel23 = new JPanel();
  BorderLayout borderLayout4 = new BorderLayout();
  BorderLayout borderLayout8 = new BorderLayout();
  BorderLayout borderLayout7 = new BorderLayout();
  BorderLayout borderLayout5 = new BorderLayout();
  BorderLayout borderLayout3 = new BorderLayout();
  BorderLayout borderLayout2 = new BorderLayout();
  JPanel jPanel42 = new JPanel();
  JPanel jPanel41 = new JPanel();
  JPanel jPanel40 = new JPanel();
  JPanel jPanel39 = new JPanel();
  JPanel jPanel38 = new JPanel();
  JPanel jPanel37 = new JPanel();
  JPanel jPanel36 = new JPanel();
  JPanel jPanel35 = new JPanel();
  JPanel jPanel34 = new JPanel();
  JPanel jPanel33 = new JPanel();
  JPanel jPanel32 = new JPanel();
  JPanel jPanel31 = new JPanel();
  JPanel jPanel30 = new JPanel();
  JPanel jPanel29 = new JPanel();
  JPanel jPanel28 = new JPanel();
  JPanel jPanel27 = new JPanel();
  JPanel jPanel26 = new JPanel();
  JPanel jPanel25 = new JPanel();
  JPanel jPanel22 = new JPanel();
  JPanel jPanel21 = new JPanel();
  JPanel jPanel20 = new JPanel();
  JPanel jPanel19 = new JPanel();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel10 = new JPanel();
  JLabel jLabel4 = new JLabel();
  JLabel jLabel3 = new JLabel();
  JLabel jLabel2 = new JLabel();
  JLabel jLabel1 = new JLabel();
  BorderLayout borderLayout36 = new BorderLayout();
  BorderLayout borderLayout35 = new BorderLayout();
  BorderLayout borderLayout34 = new BorderLayout();
  BorderLayout borderLayout33 = new BorderLayout();
  BorderLayout borderLayout32 = new BorderLayout();
  BorderLayout borderLayout31 = new BorderLayout();
  BorderLayout borderLayout30 = new BorderLayout();
  JToggleButton jToggleButton5 = new JToggleButton();
  JToggleButton jToggleButton4 = new JToggleButton();
  JToggleButton jToggleButton3 = new JToggleButton();
  JToggleButton jToggleButton2 = new JToggleButton();
  JToggleButton jToggleButton1 = new JToggleButton();
  BorderLayout borderLayout29 = new BorderLayout();
  BorderLayout borderLayout28 = new BorderLayout();
  BorderLayout borderLayout27 = new BorderLayout();
  BorderLayout borderLayout26 = new BorderLayout();
  BorderLayout borderLayout25 = new BorderLayout();
  FlowLayout flowLayout2 = new FlowLayout();
  BorderLayout borderLayout24 = new BorderLayout();
  FlowLayout flowLayout1 = new FlowLayout();
  BorderLayout borderLayout23 = new BorderLayout();
  JRadioButton jRadioButton3 = new JRadioButton();
  BorderLayout borderLayout22 = new BorderLayout();
  JRadioButton jRadioButton2 = new JRadioButton();
  JRadioButton jRadioButton1 = new JRadioButton();
  JPanel jPanel7 = new JPanel();
  JPanel jPanel6 = new JPanel();
  JPanel jPanel2 = new JPanel();
  JPanel jPanel1 = new JPanel();
  BorderLayout borderLayout15 = new BorderLayout();
  BorderLayout borderLayout14 = new BorderLayout();
  BorderLayout borderLayout13 = new BorderLayout();
  BorderLayout borderLayout12 = new BorderLayout();
  JComboBox jComboBox4 = new JComboBox();
  JComboBox jComboBox3 = new JComboBox();
  JComboBox jComboBox2 = new JComboBox();
  JComboBox jComboBox1 = new JComboBox();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JCheckBox jCheckBox9 = new JCheckBox();
  JCheckBox jCheckBox8 = new JCheckBox();
  JCheckBox jCheckBox7 = new JCheckBox();
  JCheckBox jCheckBox6 = new JCheckBox();
  JCheckBox jCheckBox5 = new JCheckBox();
  JCheckBox jCheckBox4 = new JCheckBox();
  JCheckBox jCheckBox3 = new JCheckBox();
  JCheckBox jCheckBox2 = new JCheckBox();
  JCheckBox jCheckBox1 = new JCheckBox();
  GridLayout gridLayout5 = new GridLayout();
  GridLayout gridLayout1 = new GridLayout();
  JTextField jTextField5 = new JTextField();
  JTextField jTextField4 = new JTextField();
  JTextField jTextField3 = new JTextField();
  JTextField jTextField2 = new JTextField();
  JTextField jTextField1 = new JTextField();
  Border border1;
  Border border2;
  TitledBorder titledBorder1;
  Border border3;
  TitledBorder titledBorder2;
  Border border4;
  Border border5;
  Border border6;
  Border border7;
  Border border8;
  Border border9;
  Border border10;
  Border border11;
  Border border12;
  Border border13;
  Border border14;

  //Construct the frame
  public GridLineStyleEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    border1 = BorderFactory.createEmptyBorder(5,5,1,8);
    border2 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder1 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"선");
    border3 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder2 = new TitledBorder(border3,"보기");
    border4 = BorderFactory.createEmptyBorder(0,5,0,0);
    border5 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"선"),BorderFactory.createEmptyBorder(0,5,15,0));
    border6 = BorderFactory.createEmptyBorder(0,5,0,3);
    border7 = BorderFactory.createEmptyBorder(0,0,50,0);
    border8 = BorderFactory.createEmptyBorder(1,0,1,0);
    border9 = BorderFactory.createEmptyBorder(1,0,1,0);
    border10 = BorderFactory.createEmptyBorder(1,0,1,0);
    border11 = BorderFactory.createEmptyBorder(7,0,2,0);
    border12 = BorderFactory.createEmptyBorder(0,5,0,0);
    border13 = BorderFactory.createEmptyBorder(0,0,0,190);
    border14 = BorderFactory.createEmptyBorder(0,0,15,0);
    jPanel15.setLayout(borderLayout17);
    jPanel15.setPreferredSize(new Dimension(160, 0));
    contentPane = (JPanel) this.getContentPane();
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(423, 364));
    this.setTitle("눈금선 서식");
    jButton2.setText("취소");
    jButton1.setText("확인");
    borderLayout17.setHgap(5);
    jPanel8.setLayout(borderLayout4);
    jPanel8.setBorder(border11);
    jPanel8.setPreferredSize(new Dimension(0, 30));
    jPanel24.setLayout(borderLayout20);
    jPanel23.setMinimumSize(new Dimension(50, 10));
    jPanel23.setPreferredSize(new Dimension(80, 0));
    jPanel23.setLayout(borderLayout18);
    jPanel42.setLayout(borderLayout36);
    jPanel42.setPreferredSize(new Dimension(403, 20));
    jPanel41.setLayout(flowLayout2);
    jPanel40.setLayout(flowLayout1);
    jPanel39.setLayout(borderLayout35);
    jPanel38.setLayout(borderLayout34);
    jPanel37.setLayout(borderLayout33);
    jPanel36.setLayout(borderLayout32);
    jPanel35.setLayout(borderLayout31);
    jPanel34.setLayout(borderLayout30);
    jPanel33.setLayout(gridLayout5);
    jPanel32.setLayout(borderLayout29);
    jPanel32.setPreferredSize(new Dimension(0, 35));
    jPanel31.setLayout(borderLayout14);
    jPanel31.setPreferredSize(new Dimension(410, 40));
    jPanel30.setLayout(borderLayout13);
    jPanel30.setBorder(border14);
    jPanel30.setPreferredSize(new Dimension(0, 73));
    jPanel29.setLayout(borderLayout12);
    jPanel29.setBorder(border13);
    jPanel29.setPreferredSize(new Dimension(0, 147));
    jPanel28.setLayout(borderLayout28);
    jPanel27.setLayout(borderLayout27);
    jPanel26.setLayout(borderLayout26);
    jPanel25.setLayout(borderLayout25);
    jPanel22.setLayout(borderLayout24);
    jPanel21.setLayout(borderLayout23);
    jPanel20.setLayout(gridLayout1);
    jPanel20.setBorder(border6);
    jPanel20.setPreferredSize(new Dimension(0, 20));
    jPanel19.setLayout(borderLayout22);
    jPanel19.setMinimumSize(new Dimension(0, 30));
    jPanel19.setPreferredSize(new Dimension(0, 55));
    jPanel11.setLayout(borderLayout8);
    jPanel11.setBorder(titledBorder2);
    jPanel11.setPreferredSize(new Dimension(0, 105));
    jPanel10.setLayout(borderLayout7);
    jPanel10.setBorder(border5);
    jPanel10.setPreferredSize(new Dimension(0, 165));
    jLabel4.setBorder(BorderFactory.createEtchedBorder());
    jLabel4.setPreferredSize(new Dimension(400, 2));
    jLabel3.setBorder(BorderFactory.createEtchedBorder());
    jLabel3.setPreferredSize(new Dimension(400, 2));
    jLabel2.setRequestFocusEnabled(false);
    jLabel2.setText("자동");
    jLabel1.setRequestFocusEnabled(false);
    jLabel1.setText("Y(값) 축 눈금");
    borderLayout36.setHgap(10);
    jToggleButton5.setBorder(null);
    jToggleButton5.setMnemonic('U');
    jToggleButton5.setText("표시 단위(U):  ");
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton4.setBorder(null);
    jToggleButton4.setMnemonic('C');
    jToggleButton4.setText("       교점(C):                ");
    jToggleButton4.setRequestFocusEnabled(false);
    jToggleButton3.setBorder(null);
    jToggleButton3.setText("두께(W):        ");
    jToggleButton3.setRequestFocusEnabled(false);
    jToggleButton2.setBorder(null);
    jToggleButton2.setText("색(C):             ");
    jToggleButton2.setRequestFocusEnabled(false);
    jToggleButton1.setBorder(null);
    jToggleButton1.setText("스타일(S):     ");
    jToggleButton1.setRequestFocusEnabled(false);
    jRadioButton3.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton3.setPreferredSize(new Dimension(99, 20));
    jRadioButton3.setText("사용자 정의");
    jRadioButton2.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton2.setPreferredSize(new Dimension(99, 20));
    jRadioButton2.setMnemonic('A');
    jRadioButton2.setText("자동(A)");
    jRadioButton2.setVerticalAlignment(SwingConstants.TOP);
    jRadioButton1.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton1.setPreferredSize(new Dimension(99, 20));
    jRadioButton1.setMnemonic('N');
    jRadioButton1.setText("없음(N)");
    jPanel7.setLayout(borderLayout3);
    jPanel6.setLayout(borderLayout5);
    jPanel6.setBorder(border7);
    jPanel6.setPreferredSize(new Dimension(192, 0));
    jPanel2.setLayout(borderLayout15);
    jPanel1.setLayout(borderLayout2);
    jCheckBox9.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox9.setMnemonic('R');
    jCheckBox9.setText("축 반전(R)");
    jCheckBox9.setRequestFocusEnabled(false);
    jCheckBox8.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox8.setMnemonic('M');
    jCheckBox8.setText("최대값에서 X(항목) 축 교차(M)");
    jCheckBox8.setRequestFocusEnabled(false);
    jCheckBox7.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox7.setMnemonic('L');
    jCheckBox7.setText("로그 눈금 간격(L)");
    jCheckBox7.setRequestFocusEnabled(false);
    jCheckBox6.setPreferredSize(new Dimension(190, 26));
    jCheckBox6.setSelected(true);
    jCheckBox6.setEnabled(false);
    jCheckBox6.setText("차트에 단위 레이블 표시(D)");
    jCheckBox6.setRequestFocusEnabled(false);
    jCheckBox5.setText(" X(항목) 축 ");
    jCheckBox5.setRequestFocusEnabled(false);
    jCheckBox4.setMnemonic('I');
    jCheckBox4.setText(" 보조 단위(I):       ");
    jCheckBox4.setRequestFocusEnabled(false);
    jCheckBox3.setMnemonic('A');
    jCheckBox3.setText(" 주 단위(A):          ");
    jCheckBox3.setRequestFocusEnabled(false);
    jCheckBox2.setMnemonic('X');
    jCheckBox2.setText(" 최대값(X):           ");
    jCheckBox2.setRequestFocusEnabled(false);
    jCheckBox1.setMnemonic('N');
    jCheckBox1.setText(" 최소값(N):          ");
    jCheckBox1.setRequestFocusEnabled(false);
    gridLayout5.setColumns(1);
    gridLayout5.setRows(6);
    gridLayout5.setVgap(1);
    gridLayout1.setColumns(1);
    gridLayout1.setRows(3);
    jTextField5.setText(" 0");
    jTextField4.setText(" 2");
    jTextField3.setText(" 10");
    jTextField2.setText(" 100");
    jTextField1.setText(" 0");
    contentPane.setBorder(border1);
    jPanel7.setBorder(border4);
    jPanel26.setBorder(border8);
    jPanel27.setBorder(border9);
    jPanel28.setBorder(border10);
    jPanel2.setBorder(border12);
    jTabbedPane1.setPreferredSize(new Dimension(430, 290));
    jPanel1.setMinimumSize(new Dimension(200, 10));
    jPanel1.setPreferredSize(new Dimension(210, 0));
    contentPane.add(jPanel8, BorderLayout.SOUTH);
    jPanel8.add(jPanel15, BorderLayout.EAST);
    jPanel15.add(jPanel23, BorderLayout.WEST);
    jPanel23.add(jButton1, BorderLayout.CENTER);
    jPanel15.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jButton2, BorderLayout.CENTER);
    contentPane.add(jTabbedPane1, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel1, "   무늬   ");
    jPanel1.add(jPanel7, BorderLayout.CENTER);
    jPanel7.add(jPanel6, BorderLayout.WEST);
    jPanel6.add(jPanel11, BorderLayout.CENTER);
    jPanel6.add(jPanel10, BorderLayout.NORTH);
    jPanel10.add(jPanel19, BorderLayout.NORTH);
    jPanel19.add(jRadioButton1, BorderLayout.CENTER);
    jPanel19.add(jRadioButton2, BorderLayout.NORTH);
    jPanel19.add(jRadioButton3, BorderLayout.SOUTH);
    jPanel10.add(jPanel20, BorderLayout.CENTER);
    jPanel20.add(jPanel21, null);
    jPanel21.add(jToggleButton1, BorderLayout.WEST);
    jPanel21.add(jPanel26, BorderLayout.CENTER);
    jPanel26.add(jComboBox1, BorderLayout.CENTER);
    jPanel20.add(jPanel22, null);
    jPanel22.add(jToggleButton2, BorderLayout.WEST);
    jPanel22.add(jPanel27, BorderLayout.CENTER);
    jPanel27.add(jComboBox2, BorderLayout.CENTER);
    jPanel20.add(jPanel25, null);
    jPanel25.add(jToggleButton3, BorderLayout.WEST);
    jPanel25.add(jPanel28, BorderLayout.CENTER);
    jPanel28.add(jComboBox3, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel2, "   눈금    ");
    jPanel2.add(jPanel29, BorderLayout.NORTH);
    jPanel29.add(jPanel32, BorderLayout.NORTH);
    jPanel32.add(jLabel1, BorderLayout.NORTH);
    jPanel32.add(jLabel2, BorderLayout.WEST);
    jPanel29.add(jPanel33, BorderLayout.CENTER);
    jPanel33.add(jPanel34, null);
    jPanel34.add(jCheckBox1, BorderLayout.WEST);
    jPanel34.add(jTextField1, BorderLayout.CENTER);
    jPanel33.add(jPanel35, null);
    jPanel35.add(jCheckBox2, BorderLayout.WEST);
    jPanel35.add(jTextField2, BorderLayout.CENTER);
    jPanel33.add(jPanel36, null);
    jPanel36.add(jCheckBox3, BorderLayout.WEST);
    jPanel36.add(jTextField3, BorderLayout.CENTER);
    jPanel33.add(jPanel37, null);
    jPanel37.add(jCheckBox4, BorderLayout.WEST);
    jPanel37.add(jTextField4, BorderLayout.CENTER);
    jPanel33.add(jPanel38, null);
    jPanel38.add(jCheckBox5, BorderLayout.WEST);
    jPanel33.add(jPanel39, null);
    jPanel39.add(jToggleButton4, BorderLayout.WEST);
    jPanel39.add(jTextField5, BorderLayout.CENTER);
    jPanel2.add(jPanel30, BorderLayout.SOUTH);
    jPanel30.add(jCheckBox7, BorderLayout.NORTH);
    jPanel30.add(jCheckBox8, BorderLayout.SOUTH);
    jPanel30.add(jCheckBox9, BorderLayout.WEST);
    jPanel2.add(jPanel31, BorderLayout.CENTER);
    jPanel31.add(jPanel40, BorderLayout.NORTH);
    jPanel40.add(jLabel3, null);
    jPanel31.add(jPanel41, BorderLayout.SOUTH);
    jPanel41.add(jLabel4, null);
    jPanel31.add(jPanel42, BorderLayout.CENTER);
    jPanel42.add(jToggleButton5, BorderLayout.WEST);
    jPanel42.add(jCheckBox6, BorderLayout.EAST);
    jPanel42.add(jComboBox4, BorderLayout.CENTER);
  }


}