
/**
 * Title:        chartwizard<p>
 * Description:  JAVA CHART v1.0<p>
 * Copyright:    Copyright (c) juney<p>
 * Company:      JCosmos<p>
 * @author juney
 * @version 1.0
 */
package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class OriginalSourceDataEditor extends Editor {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  JPanel jPanel1 = new JPanel();
  BorderLayout borderLayout2 = new BorderLayout();
  Border border1;
  JPanel jPanel2 = new JPanel();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JPanel nameEnglish = new JPanel();
  JPanel userDefined = new JPanel();
  Border border2;
  Border border3;
  BorderLayout borderLayout3 = new BorderLayout();
  JPanel jPanel5 = new JPanel();
  Border border4;
  TitledBorder titledBorder1;
  BorderLayout borderLayout4 = new BorderLayout();
  Border border5;
  TitledBorder titledBorder2;
  TitledBorder titledBorder3;
  Border border6;
  Border border7;
  Border border8;
  Border border9;
  TitledBorder titledBorder4;
  Border border10;
  Border border11;
  Border border12;
  Border border13;
  Border border14;
  BorderLayout borderLayout8 = new BorderLayout();
  Border border15;
  Border border16;
  Border border17;
  TitledBorder titledBorder5;
  Border border18;
  TitledBorder titledBorder6;
  Border border19;
  Border border20;
  Border border21;
  Border border22;
  TitledBorder titledBorder7;
  Border border23;
  BorderLayout borderLayout14 = new BorderLayout();
  JPanel jPanel4 = new JPanel();
  JPanel jPanel17 = new JPanel();
  JPanel jPanel18 = new JPanel();
  JButton jButton1 = new JButton();
  FlowLayout flowLayout1 = new FlowLayout();
  Border border24;
  FlowLayout flowLayout2 = new FlowLayout();
  JButton jButton2 = new JButton();
  JButton jButton3 = new JButton();
  JButton jButton4 = new JButton();
  JButton jButton7 = new JButton();
  Border border25;
  Border border26;
  JPanel jPanel6 = new JPanel();
  BorderLayout borderLayout6 = new BorderLayout();
  JPanel jPanel7 = new JPanel();
  Border border27;
  JPanel jPanel19 = new JPanel();
  Border border28;
  JPanel jPanel20 = new JPanel();
  Border border29;
  GridLayout gridLayout1 = new GridLayout();
  JToggleButton jToggleButton3 = new JToggleButton();
  JToggleButton jToggleButton4 = new JToggleButton();
  JRadioButton jRadioButton1 = new JRadioButton();
  JRadioButton jRadioButton4 = new JRadioButton();
  JPanel jPanel9 = new JPanel();
  JPanel jPanel10 = new JPanel();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel12 = new JPanel();
  JPanel jPanel13 = new JPanel();
  BorderLayout borderLayout9 = new BorderLayout();
  JPanel jPanel23 = new JPanel();
  BorderLayout borderLayout10 = new BorderLayout();
  BorderLayout borderLayout11 = new BorderLayout();
  BorderLayout borderLayout12 = new BorderLayout();
  JToggleButton jToggleButton5 = new JToggleButton();
  BorderLayout borderLayout13 = new BorderLayout();
  JPanel jPanel14 = new JPanel();
  BorderLayout borderLayout15 = new BorderLayout();
  JPanel jPanel15 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  JPanel jPanel16 = new JPanel();
  BorderLayout borderLayout16 = new BorderLayout();
  JPanel jPanel25 = new JPanel();
  JPanel jPanel26 = new JPanel();
  JScrollPane jScrollPane1 = new JScrollPane();
  BorderLayout borderLayout17 = new BorderLayout();
  JButton jButton5 = new JButton();
  JButton jButton6 = new JButton();
  BorderLayout borderLayout18 = new BorderLayout();
  Border border30;
  JPanel jPanel27 = new JPanel();
  JToggleButton jToggleButton7 = new JToggleButton();
  JToggleButton jToggleButton9 = new JToggleButton();
  FlowLayout flowLayout3 = new FlowLayout();
  JToggleButton jToggleButton10 = new JToggleButton();
  JPanel jPanel24 = new JPanel();
  BorderLayout borderLayout19 = new BorderLayout();
  JPanel jPanel28 = new JPanel();
  JPanel jPanel29 = new JPanel();
  JToggleButton jToggleButton11 = new JToggleButton();
  JToggleButton jToggleButton12 = new JToggleButton();
  Border border31;
  BorderLayout borderLayout21 = new BorderLayout();
  Border border32;
  BorderLayout borderLayout20 = new BorderLayout();
  JPanel jPanel30 = new JPanel();
  JPanel jPanel31 = new JPanel();
  BorderLayout borderLayout22 = new BorderLayout();
  BorderLayout borderLayout23 = new BorderLayout();
  JTextField jTextField2 = new JTextField();
  Border border33;
  JTextField jTextField3 = new JTextField();
  JPanel jPanel32 = new JPanel();
  TitledBorder titledBorder8;
  JToggleButton jToggleButton15 = new JToggleButton();
  JTextField jTextField4 = new JTextField();
  JPanel jPanel22 = new JPanel();
  BorderLayout borderLayout24 = new BorderLayout();
  JPanel jPanel3 = new JPanel();
  BorderLayout borderLayout5 = new BorderLayout();
  JToggleButton jToggleButton1 = new JToggleButton();
  Border border34;
  Border border35;
  JPanel jPanel33 = new JPanel();
  Border border36;
  JToggleButton jToggleButton8 = new JToggleButton();
  Border border37;
  JPanel jPanel8 = new JPanel();
  JToggleButton jToggleButton2 = new JToggleButton();
  BorderLayout borderLayout7 = new BorderLayout();
  JTextField jTextField1 = new JTextField();
  JButton jButton8 = new JButton();
  Border border38;
  JButton jButton9 = new JButton();
  Border border39;
  JButton jButton10 = new JButton();
  Border border40;
  JButton jButton11 = new JButton();
  Border border41;
  Border border42;
  JLabel jLabel1 = new JLabel();
  Border border43;
  JLabel jLabel2 = new JLabel();

  //Construct the frame
  public OriginalSourceDataEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    contentPane = (JPanel) this.getContentPane();
    border1 = BorderFactory.createEmptyBorder(5,5,2,5);
    border2 = BorderFactory.createEmptyBorder(3,2,3,0);
    border3 = BorderFactory.createCompoundBorder(BorderFactory.createEtchedBorder(Color.lightGray,Color.lightGray),border1);
    border4 = BorderFactory.createEmptyBorder();
    titledBorder1 = new TitledBorder("");
    border5 = BorderFactory.createEmptyBorder(2,10,5,10);
    titledBorder2 = new TitledBorder("");
    titledBorder3 = new TitledBorder("");
    border7 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    border8 = BorderFactory.createBevelBorder(BevelBorder.LOWERED,Color.white,Color.white,new Color(134, 134, 134),new Color(93, 93, 93));
    border9 = BorderFactory.createBevelBorder(BevelBorder.RAISED,Color.white,Color.white,new Color(178, 178, 178),new Color(124, 124, 124));
    titledBorder4 = new TitledBorder("");
    border10 = BorderFactory.createEmptyBorder(0,0,0,5);
    border11 = BorderFactory.createCompoundBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED,Color.white,Color.white,new Color(134, 134, 134),new Color(93, 93, 93)),BorderFactory.createEmptyBorder(0,0,0,30));
    border12 = BorderFactory.createEmptyBorder(10,0,0,0);
    border13 = BorderFactory.createEmptyBorder(5,0,0,0);
    border14 = BorderFactory.createBevelBorder(BevelBorder.LOWERED,Color.white,SystemColor.activeCaption,Color.white,SystemColor.activeCaption);
    border15 = BorderFactory.createEmptyBorder(0,5,5,5);
    border16 = BorderFactory.createEmptyBorder(0,10,0,0);
    border17 = BorderFactory.createEmptyBorder(1,0,0,0);
    titledBorder5 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(178, 178, 178)),"");
    border18 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder6 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"사용할 서식");
    border19 = BorderFactory.createEmptyBorder(3,0,0,0);
    titledBorder7 = new TitledBorder("");
    border23 = BorderFactory.createCompoundBorder(new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"사용할 서식"),BorderFactory.createEmptyBorder(0,6,0,0));
    border24 = BorderFactory.createEmptyBorder();
    border25 = BorderFactory.createEmptyBorder();
    border26 = BorderFactory.createBevelBorder(BevelBorder.LOWERED,Color.white,Color.white,new Color(134, 134, 134),new Color(93, 93, 93));
    border27 = BorderFactory.createEmptyBorder(0,0,5,0);
    border28 = BorderFactory.createEmptyBorder(5,0,0,0);
    border29 = BorderFactory.createEmptyBorder(5,0,0,0);
    border30 = BorderFactory.createEmptyBorder(3,0,3,0);
    border31 = BorderFactory.createEmptyBorder(3,0,1,0);
    border32 = BorderFactory.createEmptyBorder(3,0,10,0);
    border33 = BorderFactory.createEmptyBorder(22,0,22,0);
    titledBorder8 = new TitledBorder("");
    border34 = BorderFactory.createEmptyBorder(5,20,5,20);
    border35 = BorderFactory.createCompoundBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED,Color.white,Color.white,new Color(178, 178, 178),new Color(124, 124, 124)),BorderFactory.createEmptyBorder(0,20,0,20));
    border36 = BorderFactory.createEmptyBorder(0,20,5,20);
    border37 = BorderFactory.createEtchedBorder(Color.white,new Color(178, 178, 178));
    border38 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    border39 = BorderFactory.createEtchedBorder(Color.white,new Color(178, 178, 178));
    border40 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    border41 = BorderFactory.createEtchedBorder(Color.white,new Color(178, 178, 178));
    border42 = BorderFactory.createEmptyBorder(2,0,3,0);
    border43 = BorderFactory.createEmptyBorder(2,0,0,0);
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(418, 428));
    this.setTitle("차트 마법사 - 4 단계 중 2 단계");
    jPanel1.setLayout(borderLayout2);
    jPanel1.setBorder(border1);
    jPanel1.setPreferredSize(new Dimension(0, 370));
    contentPane.setPreferredSize(new Dimension(0, 71));
    jPanel2.setBorder(border4);
    jPanel2.setPreferredSize(new Dimension(10, 20));
    jPanel2.setLayout(borderLayout14);
    nameEnglish.setLayout(borderLayout3);
    jPanel5.setBorder(border5);
    jPanel5.setPreferredSize(new Dimension(385, 10));
    jPanel5.setLayout(borderLayout4);
    jTabbedPane1.setPreferredSize(new Dimension(385, 90));
    jTabbedPane1.setRequestFocusEnabled(false);
    userDefined.setRequestFocusEnabled(false);
    userDefined.setLayout(borderLayout8);
    jPanel17.setBorder(border4);
    jPanel17.setPreferredSize(new Dimension(318, 20));
    jPanel17.setLayout(flowLayout2);
    jPanel4.setLayout(flowLayout1);
    jPanel4.setBorder(border17);
    jPanel4.setPreferredSize(new Dimension(40, 20));
    jButton1.setPreferredSize(new Dimension(27, 21));
    jButton1.setIcon(new ImageIcon(jcosmos.Utility.getResource("01.gif")));
    jButton2.setPreferredSize(new Dimension(74, 21));
    jButton2.setMargin(new Insets(2, 10, 2, 10));
    jButton2.setMnemonic('F');
    jButton2.setText("마침(F)");
    jButton3.setPreferredSize(new Dimension(74, 21));
    jButton3.setText("다음>");
    jButton4.setPreferredSize(new Dimension(74, 21));
    jButton4.setHorizontalAlignment(SwingConstants.LEFT);
    jButton4.setMargin(new Insets(2, 10, 2, 10));
    jButton4.setMnemonic('B');
    jButton4.setText("<뒤로(B)");
    jButton7.setPreferredSize(new Dimension(74, 21));
    jButton7.setText("취소");
    flowLayout2.setHgap(4);
    jPanel6.setLayout(borderLayout6);
    jPanel6.setBorder(border28);
    jPanel6.setPreferredSize(new Dimension(0, 150));
    nameEnglish.setPreferredSize(new Dimension(385, 90));
    jPanel19.setLayout(gridLayout1);
    jPanel20.setPreferredSize(new Dimension(10, 80));
    jPanel19.setBorder(border29);
    jPanel19.setPreferredSize(new Dimension(130, 0));
    jToggleButton3.setMargin(new Insets(0, 14, 0, 14));
    jToggleButton3.setPreferredSize(new Dimension(70, 23));
    jToggleButton3.setBorder(null);
    jToggleButton3.setMnemonic('R');
    jToggleButton3.setText("계열 위치: ");
    jToggleButton3.setRequestFocusEnabled(false);
    jToggleButton3.setHorizontalAlignment(SwingConstants.LEFT);
    gridLayout1.setColumns(2);
    gridLayout1.setRows(2);
    jToggleButton4.setMargin(new Insets(0, 14, 0, 14));
    jToggleButton4.setBorder(null);
    jRadioButton1.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton1.setPreferredSize(new Dimension(50, 18));
    jRadioButton1.setMnemonic('R');
    jRadioButton1.setText("행(R)");
    jRadioButton1.setHorizontalAlignment(SwingConstants.CENTER);
    jRadioButton4.setMargin(new Insets(0, 0, 0, 0));
    jRadioButton4.setPreferredSize(new Dimension(48, 18));
    jRadioButton4.setMnemonic('L');
    jRadioButton4.setText("열(L)");
    jRadioButton4.setHorizontalAlignment(SwingConstants.CENTER);
    jPanel9.setLayout(borderLayout9);
    jPanel9.setBorder(border27);
    jPanel9.setPreferredSize(new Dimension(10, 95));
    jPanel10.setBorder(BorderFactory.createEtchedBorder());
    jPanel11.setLayout(borderLayout10);
    jPanel11.setBorder(border28);
    jPanel11.setPreferredSize(new Dimension(0, 174));
    jPanel12.setBorder(border5);
    jPanel12.setPreferredSize(new Dimension(385, 350));
    jPanel12.setLayout(borderLayout12);
    jPanel13.setLayout(borderLayout11);
    jPanel13.setBorder(border27);
    jPanel13.setPreferredSize(new Dimension(0, 167));
    jPanel23.setBorder(border43);
    jPanel23.setPreferredSize(new Dimension(10, 56));
    jPanel23.setLayout(borderLayout13);
    jToggleButton5.setPreferredSize(new Dimension(41, 15));
    jToggleButton5.setBorder(null);
    jToggleButton5.setMnemonic('S');
    jToggleButton5.setText("계열(S)");
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton5.setHorizontalAlignment(SwingConstants.LEFT);
    jPanel14.setPreferredSize(new Dimension(10, 85));
    jPanel14.setLayout(borderLayout15);
    jPanel15.setLayout(gridLayout2);
    borderLayout15.setHgap(2);
    jPanel16.setPreferredSize(new Dimension(125, 50));
    jPanel16.setLayout(borderLayout16);
    jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane1.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane1.setPreferredSize(new Dimension(50, 65));
    jPanel25.setLayout(borderLayout17);
    jButton5.setPreferredSize(new Dimension(60, 23));
    jButton5.setRequestFocusEnabled(false);
    jButton5.setHorizontalAlignment(SwingConstants.LEFT);
    jButton5.setMargin(new Insets(0, 5, 0, 5));
    jButton5.setMnemonic('A');
    jButton5.setText("추가(A)");
    jButton6.setPreferredSize(new Dimension(60, 23));
    jButton6.setRequestFocusEnabled(false);
    jButton6.setHorizontalAlignment(SwingConstants.LEFT);
    jButton6.setMargin(new Insets(0, 5, 0, 5));
    jButton6.setMnemonic('R');
    jButton6.setText("제거(R)");
    jPanel26.setLayout(borderLayout18);
    jPanel26.setBorder(border30);
    jPanel26.setPreferredSize(new Dimension(116, 25));
    jPanel27.setBackground(Color.white);
    jPanel27.setPreferredSize(new Dimension(100, 80));
    jPanel27.setLayout(flowLayout3);
    jToggleButton7.setMargin(new Insets(0, 10, 0, 10));
    jToggleButton7.setPreferredSize(new Dimension(73, 20));
    jToggleButton7.setBackground(Color.white);
    jToggleButton7.setBorder(null);
    jToggleButton7.setText("동부        ");
    jToggleButton7.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton9.setMargin(new Insets(0, 10, 0, 10));
    jToggleButton9.setPreferredSize(new Dimension(103, 20));
    jToggleButton9.setBackground(Color.white);
    jToggleButton9.setBorder(null);
    jToggleButton9.setText("북부                  ");
    jToggleButton9.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton10.setMargin(new Insets(0, 10, 0, 10));
    jToggleButton10.setPreferredSize(new Dimension(79, 20));
    jToggleButton10.setBackground(Color.white);
    jToggleButton10.setBorder(null);
    jToggleButton10.setText("서부          ");
    jToggleButton10.setHorizontalAlignment(SwingConstants.LEFT);
    flowLayout3.setAlignment(FlowLayout.LEFT);
    flowLayout3.setHgap(0);
    flowLayout3.setVgap(0);
    jPanel25.setPreferredSize(new Dimension(50, 63));
    jPanel24.setLayout(borderLayout19);
    jPanel28.setBorder(border32);
    jPanel28.setPreferredSize(new Dimension(70, 10));
    jPanel28.setLayout(borderLayout21);
    jPanel29.setBorder(border31);
    jPanel29.setPreferredSize(new Dimension(81, 40));
    jPanel29.setLayout(borderLayout20);
    jToggleButton11.setBorder(null);
    jToggleButton11.setMnemonic('N');
    jToggleButton11.setText("이름(N):");
    jToggleButton11.setRequestFocusEnabled(false);
    jToggleButton12.setBorder(null);
    jToggleButton12.setMnemonic('V');
    jToggleButton12.setText(" 값(V):     ");
    jToggleButton12.setRequestFocusEnabled(false);
    borderLayout21.setVgap(10);
    jPanel24.setPreferredSize(new Dimension(151, 40));
    jPanel30.setBorder(border42);
    jPanel30.setPreferredSize(new Dimension(0, 22));
    jPanel30.setLayout(borderLayout22);
    jPanel31.setBorder(border33);
    jPanel31.setPreferredSize(new Dimension(0, 44));
    jPanel31.setLayout(borderLayout23);
    jTextField2.setText("=Sheet1!$A$4");
    jTextField2.addActionListener(new java.awt.event.ActionListener() {

      public void actionPerformed(ActionEvent e) {
        jTextField2_actionPerformed(e);
      }
    });
    jTextField3.setPreferredSize(new Dimension(114, 17));
    jTextField3.setText("=Sheet1!$B$4:$E$4");
    jPanel32.setPreferredSize(new Dimension(14, 3));
    jToggleButton15.setBorder(null);
    jToggleButton15.setMnemonic('T');
    jToggleButton15.setText("X(항목) 축 레이블(T):                     ");
    jToggleButton15.setRequestFocusEnabled(false);
    jTextField4.setPreferredSize(new Dimension(100, 22));
    jTextField4.setText("=Sheet1!$B$1:$E$1");
    jPanel22.setPreferredSize(new Dimension(10, 38));
    jPanel22.setLayout(borderLayout24);
    jPanel3.setBorder(border34);
    jPanel3.setPreferredSize(new Dimension(10, 168));
    jPanel3.setLayout(borderLayout5);
    jToggleButton1.setIcon(new ImageIcon(jcosmos.Utility.getResource("step2-01.gif")));
    jToggleButton1.setBackground(Color.white);
    jToggleButton1.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton1.setRequestFocusEnabled(false);
    jPanel33.setBorder(border36);
    jPanel33.setPreferredSize(new Dimension(385, 170));
    jToggleButton8.setRequestFocusEnabled(false);
    jToggleButton8.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton8.setBackground(Color.white);
    jToggleButton8.setPreferredSize(new Dimension(335, 162));
    jToggleButton8.setIcon(new ImageIcon(jcosmos.Utility.getResource("step2-01.gif")));
    jToggleButton2.setBorder(null);
    jToggleButton2.setMnemonic('D');
    jToggleButton2.setText("데이터 범위(D):   ");
    jToggleButton2.setRequestFocusEnabled(false);
    jPanel8.setLayout(borderLayout7);
    jTextField1.setText("=Sheet1!$A$1:$E$4");
    jButton8.setBackground(Color.white);
    jButton8.setBorder(border38);
    jButton8.setRequestFocusEnabled(false);
    jButton8.setIcon(new ImageIcon(jcosmos.Utility.getResource("step2-02.gif")));
    jButton8.setMargin(new Insets(0, 0, 0, 0));
    jPanel8.setPreferredSize(new Dimension(175, 17));
    jButton9.setBackground(Color.white);
    jButton9.setBorder(border39);
    jButton9.setRequestFocusEnabled(false);
    jButton9.setIcon(new ImageIcon(jcosmos.Utility.getResource("step2-02.gif")));
    jButton9.setMargin(new Insets(0, 0, 0, 0));
    jButton9.addActionListener(new java.awt.event.ActionListener() {

      public void actionPerformed(ActionEvent e) {
        jButton9_actionPerformed(e);
      }
    });
    jButton10.setBackground(Color.white);
    jButton10.setBorder(border40);
    jButton10.setIcon(new ImageIcon(jcosmos.Utility.getResource("step2-02.gif")));
    jButton10.setMargin(new Insets(0, 0, 0, 0));
    jButton11.setBackground(Color.white);
    jButton11.setBorder(border41);
    jButton11.setRequestFocusEnabled(false);
    jButton11.setIcon(new ImageIcon(jcosmos.Utility.getResource("step2-02.gif")));
    jButton11.setMargin(new Insets(0, 0, 0, 0));
    jLabel1.setBorder(BorderFactory.createEtchedBorder());
    jLabel1.setMaximumSize(new Dimension(400, 2));
    jLabel1.setMinimumSize(new Dimension(400, 2));
    jLabel1.setPreferredSize(new Dimension(400, 2));
    jLabel2.setBorder(BorderFactory.createEtchedBorder());
    jLabel2.setMaximumSize(new Dimension(400, 2));
    jLabel2.setMinimumSize(new Dimension(400, 2));
    jLabel2.setPreferredSize(new Dimension(400, 2));
    jLabel2.setText("jLabel2");
    contentPane.add(jPanel1, BorderLayout.NORTH);
    jPanel1.add(jTabbedPane1, BorderLayout.CENTER);
    jTabbedPane1.add(nameEnglish, " 데이터 범위 ");
    nameEnglish.add(jPanel5, BorderLayout.CENTER);
    jPanel5.add(jPanel6, BorderLayout.SOUTH);
    jPanel6.add(jPanel19, BorderLayout.WEST);
    jPanel19.add(jToggleButton3, null);
    jPanel19.add(jRadioButton1, null);
    jPanel19.add(jToggleButton4, null);
    jPanel19.add(jRadioButton4, null);
    jPanel6.add(jPanel20, BorderLayout.SOUTH);
    jPanel6.add(jPanel8, BorderLayout.NORTH);
    jPanel8.add(jToggleButton2, BorderLayout.WEST);
    jPanel8.add(jTextField1, BorderLayout.CENTER);
    jPanel8.add(jButton8, BorderLayout.EAST);
    jPanel5.add(jPanel7, BorderLayout.CENTER);
    jPanel7.add(jLabel2, null);
    jPanel5.add(jPanel3, BorderLayout.NORTH);
    jPanel3.add(jToggleButton1, BorderLayout.CENTER);
    jTabbedPane1.add(userDefined, "   계열   ");
    userDefined.add(jPanel12, BorderLayout.NORTH);
    jPanel12.add(jPanel13, BorderLayout.NORTH);
    jPanel13.add(jPanel33, BorderLayout.CENTER);
    jPanel33.add(jToggleButton8, null);
    jPanel12.add(jPanel11, BorderLayout.SOUTH);
    jPanel11.add(jPanel9, BorderLayout.CENTER);
    jPanel9.add(jPanel14, BorderLayout.NORTH);
    jPanel14.add(jPanel16, BorderLayout.WEST);
    jPanel16.add(jPanel25, BorderLayout.CENTER);
    jPanel25.add(jScrollPane1, BorderLayout.NORTH);
    jScrollPane1.getViewport().add(jPanel27, null);
    jPanel27.add(jToggleButton7, null);
    jPanel27.add(jToggleButton9, null);
    jPanel27.add(jToggleButton10, null);
    jPanel16.add(jPanel26, BorderLayout.SOUTH);
    jPanel26.add(jButton5, BorderLayout.WEST);
    jPanel26.add(jButton6, BorderLayout.EAST);
    jPanel14.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jPanel28, BorderLayout.WEST);
    jPanel28.add(jToggleButton11, BorderLayout.NORTH);
    jPanel28.add(jToggleButton12, BorderLayout.CENTER);
    jPanel24.add(jPanel29, BorderLayout.CENTER);
    jPanel29.add(jPanel30, BorderLayout.NORTH);
    jPanel30.add(jTextField2, BorderLayout.CENTER);
    jPanel30.add(jButton10, BorderLayout.EAST);
    jPanel29.add(jPanel31, BorderLayout.CENTER);
    jPanel31.add(jTextField3, BorderLayout.CENTER);
    jPanel31.add(jButton9, BorderLayout.EAST);
    jPanel9.add(jPanel32, BorderLayout.CENTER);
    jPanel32.add(jLabel1, null);
    jPanel11.add(jPanel23, BorderLayout.SOUTH);
    jPanel23.add(jToggleButton15, BorderLayout.WEST);
    jPanel23.add(jTextField4, BorderLayout.CENTER);
    jPanel23.add(jPanel22, BorderLayout.SOUTH);
    jPanel23.add(jButton11, BorderLayout.EAST);
    jPanel11.add(jToggleButton5, BorderLayout.NORTH);
    jPanel12.add(jPanel10, BorderLayout.CENTER);

    contentPane.add(jPanel2, BorderLayout.CENTER);
    jPanel2.add(jPanel4, BorderLayout.WEST);
    jPanel4.add(jButton1, null);
    jPanel2.add(jPanel17, BorderLayout.EAST);
    jPanel17.add(jButton7, null);
    jPanel17.add(jButton4, null);
    jPanel17.add(jButton3, null);
    jPanel17.add(jButton2, null);
    jPanel2.add(jPanel18, BorderLayout.CENTER);
  }

  void jTextField2_actionPerformed(ActionEvent e) {

  }

  void jButton9_actionPerformed(ActionEvent e) {

  }

}