
/**
 * Title:        chartwizard<p>
 * Description:  JAVA CHART v1.0<p>
 * Copyright:    Copyright (c) juney<p>
 * Company:      JCosmos<p>
 * @author juney
 * @version 1.0
 */
package jchartui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.*;

public class TendencyEditor extends Editor {
  JPanel contentPane;
  BorderLayout borderLayout1 = new BorderLayout();
  Border border1;
  JPanel jPanel1 = new JPanel();
  JPanel jPanel15 = new JPanel();
  BorderLayout borderLayout20 = new BorderLayout();
  JButton jButton2 = new JButton();
  JButton jButton1 = new JButton();
  BorderLayout borderLayout18 = new BorderLayout();
  BorderLayout borderLayout17 = new BorderLayout();
  JPanel jPanel2 = new JPanel();
  JPanel jPanel24 = new JPanel();
  JPanel jPanel23 = new JPanel();
  BorderLayout borderLayout3 = new BorderLayout();
  BorderLayout borderLayout2 = new BorderLayout();
  JTabbedPane jTabbedPane1 = new JTabbedPane();
  JPanel jPanel3 = new JPanel();
  JPanel jPanel4 = new JPanel();
  BorderLayout borderLayout4 = new BorderLayout();
  BorderLayout borderLayout5 = new BorderLayout();
  JPanel jPanel5 = new JPanel();
  JPanel jPanel6 = new JPanel();
  BorderLayout borderLayout6 = new BorderLayout();
  BorderLayout borderLayout7 = new BorderLayout();
  Border border2;
  TitledBorder titledBorder1;
  Border border3;
  JToggleButton jToggleButton1 = new JToggleButton();
  JScrollPane jScrollPane1 = new JScrollPane();
  JPanel jPanel7 = new JPanel();
  GridLayout gridLayout1 = new GridLayout();
  Border border4;
  JPanel jPanel8 = new JPanel();
  GridLayout gridLayout2 = new GridLayout();
  JPanel jPanel9 = new JPanel();
  JPanel jPanel10 = new JPanel();
  JPanel jPanel11 = new JPanel();
  JPanel jPanel12 = new JPanel();
  BorderLayout borderLayout8 = new BorderLayout();
  BorderLayout borderLayout9 = new BorderLayout();
  BorderLayout borderLayout10 = new BorderLayout();
  BorderLayout borderLayout11 = new BorderLayout();
  JPanel jPanel13 = new JPanel();
  JPanel jPanel14 = new JPanel();
  BorderLayout borderLayout12 = new BorderLayout();
  BorderLayout borderLayout13 = new BorderLayout();
  JButton jButton3 = new JButton();
  Border border5;
  Border border6;
  JButton jButton4 = new JButton();
  Border border7;
  Border border8;
  JPanel jPanel16 = new JPanel();
  JPanel jPanel17 = new JPanel();
  BorderLayout borderLayout14 = new BorderLayout();
  BorderLayout borderLayout15 = new BorderLayout();
  JButton jButton5 = new JButton();
  Border border9;
  Border border10;
  JLabel jLabel7 = new JLabel();
  JScrollPane jScrollPane2 = new JScrollPane();
  JPanel jPanel18 = new JPanel();
  GridLayout gridLayout3 = new GridLayout();
  Border border11;
  Border border12;
  JPanel jPanel19 = new JPanel();
  JPanel jPanel20 = new JPanel();
  BorderLayout borderLayout16 = new BorderLayout();
  BorderLayout borderLayout19 = new BorderLayout();
  JButton jButton6 = new JButton();
  JButton jButton7 = new JButton();
  JPanel jPanel21 = new JPanel();
  JPanel jPanel22 = new JPanel();
  BorderLayout borderLayout21 = new BorderLayout();
  BorderLayout borderLayout22 = new BorderLayout();
  JButton jButton8 = new JButton();
  JLabel jLabel11 = new JLabel();
  JScrollPane jScrollPane3 = new JScrollPane();
  JPanel jPanel25 = new JPanel();
  GridLayout gridLayout4 = new GridLayout();
  Border border13;
  Border border14;
  Border border15;
  Border border16;
  Border border17;
  Border border18;
  Border border19;
  JPanel jPanel26 = new JPanel();
  JPanel jPanel27 = new JPanel();
  JPanel jPanel28 = new JPanel();
  Border border20;
  BorderLayout borderLayout23 = new BorderLayout();
  BorderLayout borderLayout24 = new BorderLayout();
  BorderLayout borderLayout25 = new BorderLayout();
  Border border21;
  TitledBorder titledBorder2;
  JPanel jPanel29 = new JPanel();
  BorderLayout borderLayout26 = new BorderLayout();
  Border border22;
  TitledBorder titledBorder3;
  JCheckBox jCheckBox3 = new JCheckBox();
  Border border23;
  JPanel jPanel30 = new JPanel();
  BorderLayout borderLayout27 = new BorderLayout();
  JCheckBox jCheckBox1 = new JCheckBox();
  Border border24;
  JPanel jPanel31 = new JPanel();
  JPanel jPanel32 = new JPanel();
  BorderLayout borderLayout28 = new BorderLayout();
  BorderLayout borderLayout29 = new BorderLayout();
  JRadioButton jRadioButton1 = new JRadioButton();
  JLabel jLabel12 = new JLabel();
  JRadioButton jRadioButton2 = new JRadioButton();
  JTextField jTextField2 = new JTextField();
  Border border25;
  JPanel jPanel33 = new JPanel();
  JPanel jPanel34 = new JPanel();
  BorderLayout borderLayout30 = new BorderLayout();
  BorderLayout borderLayout31 = new BorderLayout();
  JToggleButton jToggleButton2 = new JToggleButton();
  JLabel jLabel13 = new JLabel();
  JScrollPane jScrollPane4 = new JScrollPane();
  JToggleButton jToggleButton3 = new JToggleButton();
  JLabel jLabel14 = new JLabel();
  JScrollPane jScrollPane5 = new JScrollPane();
  JPanel jPanel35 = new JPanel();
  GridLayout gridLayout5 = new GridLayout();
  JPanel jPanel36 = new JPanel();
  GridLayout gridLayout6 = new GridLayout();
  Border border26;
  Border border27;
  JPanel jPanel37 = new JPanel();
  BorderLayout borderLayout32 = new BorderLayout();
  Border border28;
  Border border29;
  JToggleButton jToggleButton4 = new JToggleButton();
  JToggleButton jToggleButton5 = new JToggleButton();
  JToggleButton jToggleButton6 = new JToggleButton();
  JToggleButton jToggleButton7 = new JToggleButton();
  JToggleButton jToggleButton8 = new JToggleButton();
  JToggleButton jToggleButton9 = new JToggleButton();
  JButton jButton9 = new JButton();
  JButton jButton10 = new JButton();
  JButton jButton11 = new JButton();
  BorderLayout borderLayout210 = new BorderLayout();
  JPanel jPanel38 = new JPanel();
  JCheckBox jCheckBox2 = new JCheckBox();
  JPanel jPanel39 = new JPanel();
  BorderLayout borderLayout33 = new BorderLayout();
  JTextField jTextField3 = new JTextField();
  JLabel jLabel1 = new JLabel();
  JButton jButton12 = new JButton();

  //Construct the frame
  public TendencyEditor() {
    enableEvents(AWTEvent.WINDOW_EVENT_MASK);
    try {
      jbInit();
    }
    catch(Exception e) {
      e.printStackTrace();
    }
  }

  //Component initialization
  private void jbInit() throws Exception  {
    contentPane = (JPanel) this.getContentPane();
    border1 = BorderFactory.createEmptyBorder(8,5,5,5);
    border2 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder1 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"추세/회귀 유형");
    border3 = BorderFactory.createEmptyBorder(3,3,0,10);
    border4 = BorderFactory.createEmptyBorder(2,1,43,250);
    border5 = BorderFactory.createEmptyBorder(0,0,0,17);
    border6 = BorderFactory.createCompoundBorder(titledBorder1,BorderFactory.createEmptyBorder(0,5,5,8));
    border7 = BorderFactory.createEmptyBorder(0,0,12,8);
    border8 = BorderFactory.createEmptyBorder(0,0,0,5);
    border9 = BorderFactory.createEmptyBorder(0,0,11,17);
    border10 = BorderFactory.createEmptyBorder(0,0,0,10);
    border11 = BorderFactory.createEmptyBorder(3,10,18,10);
    border12 = BorderFactory.createEmptyBorder(0,0,2,0);
    border13 = BorderFactory.createEmptyBorder(3,2,18,10);
    border14 = BorderFactory.createEmptyBorder(0,8,0,9);
    border15 = BorderFactory.createEmptyBorder(0,0,0,12);
    border16 = BorderFactory.createEmptyBorder(0,0,8,0);
    border17 = BorderFactory.createEmptyBorder(0,2,0,0);
    border18 = BorderFactory.createEmptyBorder(0,2,0,0);
    border19 = BorderFactory.createEmptyBorder();
    border20 = BorderFactory.createEmptyBorder(3,5,0,10);
    border21 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder2 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"추세선 이름");
    border22 = BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134));
    titledBorder3 = new TitledBorder(BorderFactory.createEtchedBorder(Color.white,new Color(134, 134, 134)),"예측");
    border23 = BorderFactory.createEmptyBorder(3,2,59,0);
    border24 = BorderFactory.createEmptyBorder(2,0,0,220);
    border25 = BorderFactory.createCompoundBorder(titledBorder2,BorderFactory.createEmptyBorder(0,5,3,8));
    border26 = BorderFactory.createEmptyBorder(4,0,3,0);
    border27 = BorderFactory.createCompoundBorder(titledBorder3,BorderFactory.createEmptyBorder(0,2,0,0));
    border28 = BorderFactory.createEmptyBorder(2,0,3,0);
    border29 = BorderFactory.createEmptyBorder(0,0,1,0);
    contentPane.setLayout(borderLayout1);
    this.setSize(new Dimension(429, 369));
    this.setTitle("추세선");
    contentPane.setBorder(border1);
    jPanel15.setLayout(borderLayout17);
    jPanel15.setPreferredSize(new Dimension(148, 0));
    jButton2.setText("취소");
    jButton1.setMinimumSize(new Dimension(10, 10));
    jButton1.setPreferredSize(new Dimension(55, 29));
    jButton1.setText("확인");
    borderLayout17.setHgap(5);
    jPanel2.setLayout(borderLayout3);
    jPanel2.setPreferredSize(new Dimension(0, 22));
    jPanel24.setLayout(borderLayout20);
    jPanel23.setMinimumSize(new Dimension(50, 10));
    jPanel23.setPreferredSize(new Dimension(75, 0));
    jPanel23.setLayout(borderLayout18);
    jPanel1.setLayout(borderLayout2);
    jPanel3.setLayout(borderLayout4);
    jPanel4.setLayout(borderLayout5);
    jPanel6.setLayout(borderLayout6);
    jPanel5.setLayout(borderLayout7);
    jPanel6.setBorder(border4);
    jPanel6.setPreferredSize(new Dimension(0, 115));
    jPanel5.setBorder(border6);
    jPanel5.setPreferredSize(new Dimension(401, 178));
    jPanel5.setRequestFocusEnabled(false);
    jPanel3.setBorder(border3);
    jPanel1.setBorder(border12);
    jPanel1.setPreferredSize(new Dimension(30, 148));
    borderLayout1.setVgap(5);
    jToggleButton1.setBorder(null);
    jToggleButton1.setMnemonic('S');
    jToggleButton1.setText("계열 선택(S):");
    jToggleButton1.setRequestFocusEnabled(false);
    jToggleButton1.setHorizontalAlignment(SwingConstants.LEFT);
    jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane1.setBorder(BorderFactory.createLoweredBevelBorder());
    jScrollPane1.setPreferredSize(new Dimension(61, 45));
    jPanel7.setBackground(Color.white);
    jPanel7.setBorder(border16);
    jPanel7.setMinimumSize(new Dimension(27, 40));
    jPanel7.setPreferredSize(new Dimension(41, 45));
    jPanel7.setLayout(gridLayout1);
    gridLayout1.setColumns(1);
    gridLayout1.setRows(3);
    jPanel8.setLayout(gridLayout2);
    gridLayout2.setColumns(2);
    gridLayout2.setRows(2);
    jPanel9.setLayout(borderLayout8);
    jPanel12.setLayout(borderLayout9);
    jPanel11.setLayout(borderLayout10);
    jPanel10.setLayout(borderLayout11);
    jPanel13.setLayout(borderLayout12);
    jPanel14.setLayout(borderLayout13);
    jPanel13.setBorder(border5);
    jPanel13.setPreferredSize(new Dimension(100, 0));
    jButton3.setBackground(Color.white);
    jButton3.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton3.setPreferredSize(new Dimension(70, 43));
    jButton3.setRequestFocusEnabled(false);
    jButton3.setIcon(new ImageIcon(jcosmos.Utility.getResource("tendency01.gif")));
    jButton3.setMargin(new Insets(0, 0, 0, 0));
    jButton4.setBackground(Color.white);
    jButton4.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton4.setRequestFocusEnabled(false);
    jButton4.setIcon(new ImageIcon(jcosmos.Utility.getResource("tendency02.gif")));
    jButton4.setMargin(new Insets(0, 0, 0, 0));
    jPanel14.setBorder(border8);
    jPanel16.setLayout(borderLayout14);
    jPanel16.setBorder(border10);
    jPanel16.setPreferredSize(new Dimension(100, 0));
    jPanel17.setLayout(borderLayout15);
    jButton5.setBackground(Color.white);
    jButton5.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton5.setRequestFocusEnabled(false);
    jButton5.setHorizontalTextPosition(SwingConstants.LEFT);
    jButton5.setIcon(new ImageIcon(jcosmos.Utility.getResource("tendency03.gif")));
    jButton5.setMargin(new Insets(0, 0, 0, 0));
    jLabel7.setText("차수(D):");
    jScrollPane2.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane2.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane2.setBorder(BorderFactory.createLoweredBevelBorder());
    jPanel18.setBackground(Color.white);
    jPanel18.setLayout(gridLayout3);
    jPanel17.setBorder(border11);
    jPanel8.setPreferredSize(new Dimension(376, 140));
    jPanel19.setLayout(borderLayout16);
    jPanel20.setLayout(borderLayout19);
    jPanel19.setPreferredSize(new Dimension(90, 0));
    jButton6.setBackground(Color.white);
    jButton6.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton6.setRequestFocusEnabled(false);
    jButton6.setIcon(new ImageIcon(jcosmos.Utility.getResource("tendency04.gif")));
    jButton6.setMargin(new Insets(0, 0, 0, 0));
    jButton7.setBackground(Color.white);
    jButton7.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton7.setRequestFocusEnabled(false);
    jButton7.setIcon(new ImageIcon(jcosmos.Utility.getResource("tendency05.gif")));
    jButton7.setMargin(new Insets(0, 0, 0, 0));
    jPanel22.setLayout(borderLayout21);
    jPanel21.setLayout(borderLayout22);
    jPanel21.setBorder(border15);
    jPanel21.setPreferredSize(new Dimension(110, 0));
    jButton8.setBackground(Color.white);
    jButton8.setBorder(BorderFactory.createLoweredBevelBorder());
    jButton8.setRequestFocusEnabled(false);
    jButton8.setIcon(new ImageIcon(jcosmos.Utility.getResource("tendency06.gif")));
    jButton8.setMargin(new Insets(0, 0, 0, 0));
    jLabel11.setText("구간(E):");
    jScrollPane3.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane3.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane3.setBorder(BorderFactory.createLoweredBevelBorder());
    jPanel25.setBackground(Color.white);
    jPanel25.setLayout(gridLayout4);
    jPanel22.setBorder(border13);
    jPanel20.setBorder(border14);
    borderLayout4.setVgap(2);
    jPanel12.setBorder(border17);
    jPanel10.setBorder(border18);
    jPanel9.setBorder(border19);
    jPanel4.setBorder(border20);
    jPanel26.setLayout(borderLayout23);
    jPanel27.setLayout(borderLayout24);
    jPanel28.setLayout(borderLayout25);
    jPanel26.setBorder(border25);
    jPanel26.setPreferredSize(new Dimension(0, 67));
    jPanel26.setRequestFocusEnabled(false);
    jPanel28.setBorder(border23);
    jPanel28.setPreferredSize(new Dimension(0, 128));
    jPanel29.setLayout(borderLayout26);
    jPanel29.setBorder(border27);
    jPanel29.setPreferredSize(new Dimension(195, 0));
    jPanel29.setRequestFocusEnabled(false);
    jCheckBox3.setMnemonic('E');
    jCheckBox3.setText("수식을 차트에 표시(E)");
    jPanel30.setLayout(borderLayout27);
    jPanel30.setBorder(border24);
    jPanel30.setPreferredSize(new Dimension(0, 24));
    jCheckBox1.setMargin(new Insets(0, 0, 0, 0));
    jCheckBox1.setMnemonic('S');
    jCheckBox1.setVerticalTextPosition(SwingConstants.TOP);
    jCheckBox1.setText("R-제곱 값을 차트에 표시");
    jCheckBox1.setVerticalAlignment(SwingConstants.TOP);
    jPanel31.setLayout(borderLayout28);
    jPanel32.setLayout(borderLayout29);
    jPanel31.setPreferredSize(new Dimension(0, 20));
    jRadioButton1.setMnemonic('A');
    jRadioButton1.setText("자동(A):");
    jRadioButton1.setRequestFocusEnabled(false);
    jLabel12.setRequestFocusEnabled(false);
    jLabel12.setText("    다항식 (서부)");
    jRadioButton2.setMnemonic('C');
    jRadioButton2.setText("사용자 정의(C):");
    jRadioButton2.setRequestFocusEnabled(false);
    jPanel33.setLayout(borderLayout30);
    jPanel34.setLayout(borderLayout31);
    jPanel33.setBorder(border29);
    jPanel33.setPreferredSize(new Dimension(0, 20));
    jTextField2.setRequestFocusEnabled(false);
    jToggleButton2.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton2.setBorder(null);
    jToggleButton2.setMnemonic('F');
    jToggleButton2.setText("앞으로(F):      ");
    jToggleButton2.setRequestFocusEnabled(false);
    jLabel13.setText("  구간   ");
    jScrollPane4.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane4.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane4.setBorder(BorderFactory.createLoweredBevelBorder());
    jToggleButton3.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton3.setBorder(null);
    jToggleButton3.setMnemonic('B');
    jToggleButton3.setText("뒤로(B):          ");
    jToggleButton3.setRequestFocusEnabled(false);
    jLabel14.setText("  구간   ");
    jScrollPane5.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    jScrollPane5.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    jScrollPane5.setBorder(BorderFactory.createLoweredBevelBorder());
    jPanel35.setBackground(Color.white);
    jPanel35.setLayout(gridLayout5);
    jPanel36.setBackground(Color.white);
    jPanel36.setLayout(gridLayout6);
    jPanel34.setBorder(border26);
    borderLayout31.setHgap(5);
    borderLayout30.setHgap(5);
    jPanel37.setLayout(borderLayout32);
    jPanel37.setBorder(border28);
    jPanel37.setPreferredSize(new Dimension(145, 0));
    jToggleButton4.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton4.setBorder(null);
    jToggleButton4.setMnemonic('L');
    jToggleButton4.setText("선형(L)");
    jToggleButton4.setRequestFocusEnabled(false);
    jToggleButton4.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton5.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton5.setBorder(null);
    jToggleButton5.setMnemonic('O');
    jToggleButton5.setText("로그(O)");
    jToggleButton5.setRequestFocusEnabled(false);
    jToggleButton5.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton6.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton6.setBorder(null);
    jToggleButton6.setMnemonic('P');
    jToggleButton6.setText("다항식(P)");
    jToggleButton6.setRequestFocusEnabled(false);
    jToggleButton6.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton7.setBorder(null);
    jToggleButton7.setMnemonic('W');
    jToggleButton7.setText("X의 누승(W)");
    jToggleButton7.setRequestFocusEnabled(false);
    jToggleButton7.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton8.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton8.setBorder(null);
    jToggleButton8.setMnemonic('X');
    jToggleButton8.setText("지수(X)");
    jToggleButton8.setRequestFocusEnabled(false);
    jToggleButton8.setHorizontalAlignment(SwingConstants.LEFT);
    jToggleButton9.setMargin(new Insets(0, 0, 0, 0));
    jToggleButton9.setBorder(null);
    jToggleButton9.setMnemonic('M');
    jToggleButton9.setText("이동평균(M)");
    jToggleButton9.setRequestFocusEnabled(false);
    jToggleButton9.setHorizontalAlignment(SwingConstants.LEFT);
    jButton9.setBackground(Color.white);
    jButton9.setBorder(null);
    jButton9.setRequestFocusEnabled(false);
    jButton9.setHorizontalAlignment(SwingConstants.LEFT);
    jButton9.setMargin(new Insets(0, 0, 0, 0));
    jButton9.setText(" 동부");
    jButton10.setBackground(Color.white);
    jButton10.setBorder(null);
    jButton10.setRequestFocusEnabled(false);
    jButton10.setHorizontalAlignment(SwingConstants.LEFT);
    jButton10.setMargin(new Insets(0, 0, 0, 0));
    jButton10.setText(" 북부");
    jButton11.setBackground(Color.white);
    jButton11.setBorder(null);
    jButton11.setRequestFocusEnabled(false);
    jButton11.setHorizontalAlignment(SwingConstants.LEFT);
    jButton11.setMargin(new Insets(0, 0, 0, 0));
    jButton11.setText(" 서부");
    jPanel38.setPreferredSize(new Dimension(145, 0));
    jPanel38.setBorder(border28);
    jPanel38.setLayout(borderLayout33);
    jCheckBox2.setMnemonic('S');
    jCheckBox2.setText("절편(S)  =   ");
    jCheckBox2.setVerticalAlignment(SwingConstants.BOTTOM);
    jPanel39.setLayout(borderLayout210);
    jPanel39.setBorder(border24);
    jPanel39.setPreferredSize(new Dimension(0, 24));
    jTextField3.setToolTipText("");
    jTextField3.setText(" 0");
    jButton12.setBorder(null);
    jButton12.setHorizontalAlignment(SwingConstants.LEFT);
    jButton12.setMargin(new Insets(0, 0, 0, 0));
    jButton12.setMnemonic('R');
    jButton12.setText("(R)");
    contentPane.add(jPanel1, BorderLayout.CENTER);
    jPanel1.add(jTabbedPane1, BorderLayout.CENTER);
    jTabbedPane1.add(jPanel3, "  종류   ");
    jPanel3.add(jPanel5, BorderLayout.CENTER);
    jPanel5.add(jPanel8, BorderLayout.CENTER);
    jPanel8.add(jPanel9, null);
    jPanel9.add(jPanel13, BorderLayout.WEST);
    jPanel13.add(jButton3, BorderLayout.CENTER);
    jPanel13.add(jToggleButton4, BorderLayout.SOUTH);
    jPanel9.add(jPanel14, BorderLayout.CENTER);
    jPanel14.add(jButton4, BorderLayout.CENTER);
    jPanel14.add(jToggleButton5, BorderLayout.SOUTH);
    jPanel8.add(jPanel12, null);
    jPanel12.add(jPanel16, BorderLayout.WEST);
    jPanel16.add(jButton5, BorderLayout.CENTER);
    jPanel16.add(jToggleButton6, BorderLayout.SOUTH);
    jPanel12.add(jPanel17, BorderLayout.CENTER);
    jPanel17.add(jLabel7, BorderLayout.NORTH);
    jPanel17.add(jScrollPane2, BorderLayout.CENTER);
    jScrollPane2.getViewport().add(jPanel18, null);
    jPanel8.add(jPanel11, null);
    jPanel11.add(jPanel19, BorderLayout.WEST);
    jPanel19.add(jButton6, BorderLayout.CENTER);
    jPanel19.add(jToggleButton7, BorderLayout.SOUTH);
    jPanel11.add(jPanel20, BorderLayout.CENTER);
    jPanel20.add(jButton7, BorderLayout.CENTER);
    jPanel20.add(jToggleButton8, BorderLayout.SOUTH);
    jPanel8.add(jPanel10, null);
    jPanel10.add(jPanel21, BorderLayout.WEST);
    jPanel21.add(jButton8, BorderLayout.CENTER);
    jPanel21.add(jToggleButton9, BorderLayout.SOUTH);
    jPanel10.add(jPanel22, BorderLayout.CENTER);
    jPanel22.add(jLabel11, BorderLayout.NORTH);
    jPanel22.add(jScrollPane3, BorderLayout.CENTER);
    jScrollPane3.getViewport().add(jPanel25, null);
    jPanel3.add(jPanel6, BorderLayout.SOUTH);
    jPanel6.add(jToggleButton1, BorderLayout.NORTH);
    jPanel6.add(jScrollPane1, BorderLayout.CENTER);
    jScrollPane1.getViewport().add(jPanel7, null);
    jPanel7.add(jButton9, null);
    jPanel7.add(jButton11, null);
    jPanel7.add(jButton10, null);
    jTabbedPane1.add(jPanel4, "   옵션   ");
    jPanel4.add(jPanel26, BorderLayout.NORTH);
    jPanel26.add(jPanel31, BorderLayout.NORTH);
    jPanel31.add(jRadioButton1, BorderLayout.WEST);
    jPanel31.add(jLabel12, BorderLayout.CENTER);
    jPanel26.add(jPanel32, BorderLayout.CENTER);
    jPanel32.add(jRadioButton2, BorderLayout.WEST);
    jPanel32.add(jTextField2, BorderLayout.CENTER);
    jPanel4.add(jPanel27, BorderLayout.CENTER);
    jPanel27.add(jPanel29, BorderLayout.WEST);
    jPanel29.add(jPanel33, BorderLayout.NORTH);
    jPanel33.add(jToggleButton2, BorderLayout.WEST);
    jPanel33.add(jLabel13, BorderLayout.EAST);
    jPanel33.add(jScrollPane4, BorderLayout.CENTER);
    jScrollPane4.getViewport().add(jPanel36, null);
    jPanel29.add(jPanel34, BorderLayout.CENTER);
    jPanel34.add(jToggleButton3, BorderLayout.WEST);
    jPanel34.add(jLabel14, BorderLayout.EAST);
    jPanel34.add(jScrollPane5, BorderLayout.CENTER);
    jScrollPane5.getViewport().add(jPanel35, null);
    jPanel4.add(jPanel28, BorderLayout.SOUTH);
    jPanel28.add(jCheckBox3, BorderLayout.CENTER);
    jPanel28.add(jPanel30, BorderLayout.SOUTH);
    jPanel30.add(jCheckBox1, BorderLayout.WEST);
    jPanel30.add(jPanel37, BorderLayout.CENTER);
    jPanel37.add(jLabel1, BorderLayout.NORTH);
    jPanel37.add(jButton12, BorderLayout.CENTER);
    jPanel28.add(jPanel39, BorderLayout.NORTH);
    jPanel39.add(jCheckBox2, BorderLayout.WEST);
    jPanel39.add(jPanel38, BorderLayout.CENTER);
    jPanel38.add(jTextField3, BorderLayout.CENTER);
    contentPane.add(jPanel2, BorderLayout.SOUTH);
    jPanel2.add(jPanel15, BorderLayout.EAST);
    jPanel15.add(jPanel23, BorderLayout.WEST);
    jPanel23.add(jButton1, BorderLayout.CENTER);
    jPanel15.add(jPanel24, BorderLayout.CENTER);
    jPanel24.add(jButton2, BorderLayout.CENTER);
  }


}